const state={time:null,budget:'any',tag:null}; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];

const INVENTORY_KEY='malix-inventory-v1';
const INVENTORY_UNITS=['g','kg','ml','dl','l','tsk','msk','st','skiva','bit','portion'];
const optionalWords=/^(eventuellt|gärna|valfri|valfria|rikligt|lite)\b/i;
function loadInventory(){try{const x=JSON.parse(localStorage.getItem(INVENTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveInventory(items){localStorage.setItem(INVENTORY_KEY,JSON.stringify(items));renderInventory()}
function cleanName(s=''){return String(s).toLowerCase().replace(/^(eventuellt|gärna|valfri|valfria|rikligt|lite)\s+/,'').replace(/\beller\b.*$/,'').replace(/[^a-zåäö0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function canonicalName(s=''){let n=cleanName(s);const aliases=[[/vitlöksklyft.*/,'vitlök'],[/^gul lök$/,'lök'],[/^morötter$/,'morot'],[/^kycklingdelar$/,'kyckling'],[/^grötris$/,'ris'],[/^turkisk yoghurt$/,'turkisk yoghurt'],[/^fil eller yoghurt$/,'yoghurt'],[/^mjölk eller annan bas$/,'mjölk'],[/^grädde eller valfri bas$/,'grädde']];aliases.forEach(([r,v])=>{if(r.test(n))n=v});return n}
function normalizeUnit(unit=''){unit=String(unit).toLowerCase();const aliases={skivor:'skiva',styck:'st',stycken:'st',bitar:'bit',portioner:'portion'};return aliases[unit]||unit}
function parseIngredient(text){const original=String(text).trim();if(optionalWords.test(original))return {optional:true,name:canonicalName(original),amount:null,unit:null,original};let m=original.match(/^(\d+(?:[.,]\d+)?)\s*(kg|g|l|dl|ml|tsk|msk|st|styck|stycken|skiva|skivor|bit|bitar|portion|portioner)\s+(.+)$/i);if(m)return {optional:false,amount:Number(m[1].replace(',','.')),unit:normalizeUnit(m[2]),name:canonicalName(m[3]),original};m=original.match(/^(\d+(?:[.,]\d+)?)\s+(.+)$/i);if(m)return {optional:false,amount:Number(m[1].replace(',','.')),unit:'st',name:canonicalName(m[2]),original};return {optional:false,amount:null,unit:null,name:canonicalName(original),original}}
function toBase(amount,unit){unit=normalizeUnit(unit);if(unit==='kg')return {value:amount*1000,kind:'mass'};if(unit==='g')return {value:amount,kind:'mass'};if(unit==='l')return {value:amount*1000,kind:'volume'};if(unit==='dl')return {value:amount*100,kind:'volume'};if(unit==='ml')return {value:amount,kind:'volume'};if(unit==='msk')return {value:amount*15,kind:'volume'};if(unit==='tsk')return {value:amount*5,kind:'volume'};return {value:amount,kind:`count:${unit||'st'}`}}
function fromBase(value,unit){unit=normalizeUnit(unit);if(unit==='kg')return value/1000;if(unit==='g')return value;if(unit==='l')return value/1000;if(unit==='dl')return value/100;if(unit==='ml')return value;if(unit==='msk')return value/15;if(unit==='tsk')return value/5;return value}
function sameFood(a,b){a=canonicalName(a);b=canonicalName(b);if(!a||!b)return false;return a===b||a.includes(b)||b.includes(a)||(a==='yoghurt'&&b.includes('yoghurt'))||(b==='yoghurt'&&a.includes('yoghurt'))}
function findInventoryItem(items,name){return items.find(x=>sameFood(x.name,name))}
function inventoryUnitsFor(name){const item=window.MalixFoodBank?.getItem?.(name);const units=item?.quantity?.units||[];return units.length?[...new Set(units.map(normalizeUnit))]:INVENTORY_UNITS}
function setInventoryUnitOptions(select,name,keepValue=true){if(!select)return;const current=keepValue?select.value:'';const units=inventoryUnitsFor(name);select.innerHTML=units.map(u=>`<option value="${u}">${u}</option>`).join('');if(current&&units.includes(current))select.value=current;else{const preferred=window.MalixFoodBank?.getItem?.(name)?.quantity?.unit;if(preferred&&units.includes(normalizeUnit(preferred)))select.value=normalizeUnit(preferred)}}
function injectInventoryUI(){const grid=document.querySelector('#home .choice-grid');if(grid&&!document.querySelector('[data-open="inventory"]'))grid.insertAdjacentHTML('beforeend','<button class="choice-card" data-open="inventory"><span>🧺</span><strong>Kyl, skafferi & frys</strong><small>Håll koll på vad som finns hemma och låt lagade recept minska lagret.</small></button>');const main=document.querySelector('main');if(main&&!document.querySelector('#inventory'))main.insertAdjacentHTML('beforeend',`<section id="inventory" class="view"><button class="back" data-open="home">← Tillbaka</button><h2>🧺 Kyl, skafferi & frys</h2><p class="note">Lägg in det du vill hålla koll på. Enheterna följer samma matmodell som matloggen. När du trycker ”Jag lagade detta” i ett recept minskar lagret när mängderna kan matchas.</p><form id="inventoryForm" class="panel record-form"><label>Råvara<input name="name" required placeholder="t.ex. turkisk yoghurt"></label><label>Mängd<input name="quantity" type="number" min="0" step="0.01" required></label><label>Enhet<select name="unit">${INVENTORY_UNITS.map(u=>`<option>${u}</option>`).join('')}</select></label><label>Förvaring<select name="location"><option>Kylskåp</option><option>Skafferi</option><option>Frys</option></select></label><button type="submit">Spara i lagret</button></form><p id="inventoryStatus" class="status"></p><div id="inventoryList" class="recipe-grid"></div></section>`);const f=document.querySelector('#inventoryForm');if(f){const nameInput=f.querySelector('[name="name"]'),unitSelect=f.querySelector('[name="unit"]');const refreshUnits=()=>setInventoryUnitOptions(unitSelect,nameInput.value,true);nameInput.addEventListener('change',refreshUnits);nameInput.addEventListener('blur',refreshUnits);f.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f).entries());const items=loadInventory();const existing=findInventoryItem(items,v.name);if(existing&&existing.unit===v.unit&&existing.location===v.location)existing.quantity=Number(existing.quantity||0)+Number(v.quantity||0);else items.unshift({id:Date.now().toString(),name:v.name.trim(),quantity:Number(v.quantity||0),unit:normalizeUnit(v.unit),location:v.location});saveInventory(items);f.reset();setInventoryUnitOptions(unitSelect,'',false);document.querySelector('#inventoryStatus').textContent='Sparat ✓'})}renderInventory()}
function renderInventory(){const el=document.querySelector('#inventoryList');if(!el)return;const items=loadInventory();el.innerHTML=items.length?items.map((x,i)=>`<article class="recipe-card"><h3>${x.location==='Kylskåp'?'❄️':x.location==='Frys'?'🧊':'🥫'} ${x.name}</h3><p><strong>${Number(x.quantity||0).toLocaleString('sv-SE')} ${x.unit}</strong> · ${x.location}</p><button class="secondary" type="button" onclick="removeInventoryItem(${i})">Ta bort</button></article>`).join(''):'<div class="empty">Lagret är tomt ännu.</div>'}
window.removeInventoryItem=i=>{const items=loadInventory();items.splice(i,1);saveInventory(items)};
function promptUsedInInventoryUnit(ingredient,item){const answer=prompt(`Receptet anger ${ingredient.original}, men lagret är registrerat i ${item.unit}. Hur mycket ${item.name} använde du i ${item.unit}?`,'');if(answer===null||answer.trim()==='')return null;const n=Number(answer.replace(',','.'));if(!Number.isFinite(n)||n<0)return null;const have=toBase(Number(item.quantity||0),item.unit),need=toBase(n,item.unit);return {neededBase:need.value,haveBase:have.value,kind:need.kind}}
function usedAmountFor(ingredient,item){if(ingredient.amount!=null){const need=toBase(ingredient.amount,ingredient.unit),have=toBase(Number(item.quantity||0),item.unit);if(need.kind!==have.kind)return promptUsedInInventoryUnit(ingredient,item);return {neededBase:need.value,haveBase:have.value,kind:need.kind}}const answer=prompt(`Hur mycket ${item.name} använde du? Ange mängd i ${item.unit}.`,'');if(answer===null||answer.trim()==='')return null;const n=Number(answer.replace(',','.'));if(!Number.isFinite(n)||n<0)return null;const need=toBase(n,item.unit),have=toBase(Number(item.quantity||0),item.unit);return {neededBase:need.value,haveBase:have.value,kind:need.kind}}
window.markRecipeCooked=id=>{const r=recipes.find(x=>x.id===id);if(!r)return;let items=loadInventory();const deductions=[];const skipped=[];for(const text of r.ingredients){const ing=parseIngredient(text);if(ing.optional)continue;const item=findInventoryItem(items,ing.name);if(!item){skipped.push(text);continue}const used=usedAmountFor(ing,item);if(!used){skipped.push(text);continue}if(used.neededBase>used.haveBase){const ok=confirm(`Du har ${item.quantity} ${item.unit} ${item.name}, men receptet verkar använda mer. Vill du ändå markera receptet som lagat och sätta lagret till 0?`);if(!ok){const s=document.querySelector('#recipeCookStatus');if(s)s.textContent='Inget ändrades i lagret.';return}deductions.push({item,afterBase:0,usedBase:used.haveBase})}else deductions.push({item,afterBase:used.haveBase-used.neededBase,usedBase:used.neededBase})}for(const d of deductions)d.item.quantity=Math.max(0,Number(fromBase(d.afterBase,d.item.unit).toFixed(3)));saveInventory(items);const cooked=JSON.parse(localStorage.getItem('malix-cooked-recipes')||'[]');cooked.unshift({recipeId:r.id,name:r.name,date:new Date().toISOString()});localStorage.setItem('malix-cooked-recipes',JSON.stringify(cooked.slice(0,100)));const s=document.querySelector('#recipeCookStatus');if(s){const changed=deductions.length?`${deductions.length} lagerpost${deductions.length===1?'':'er'} uppdaterades.`:'Inga lagerposter matchade receptet.';const note=skipped.length?' Ingredienser utan lagerträff lämnades oförändrade.':'';s.textContent=`Lagat ✓ ${changed}${note}`}}

function standardizeOvenChicken(){const r=recipes.find(x=>x.id==='kyckling-ugn');if(!r)return;Object.assign(r,{time:55,servings:4,prepTime:15,cookTime:40,oven:'225 °C över-/undervärme',equipment:['skärbräda','kniv','stor ugnsplåt eller långpanna','stor skål','mått'],ingredients:['800 g kycklingdelar','800 g potatis','300 g morötter','1 st gul lök','2 msk rapsolja','1 tsk torkad rosmarin','2 st vitlöksklyftor','1 tsk salt','0,25 tsk svartpeppar'],leftovers:['potatis','morot','kyckling'],tip:'Allt på samma plåt betyder mindre disk. Skär potatis och morötter i ungefär lika stora bitar så blir de klara samtidigt.',steps:['Sätt ugnen på 225 °C över-/undervärme. Ta fram en stor plåt eller långpanna.','Skölj eller skala potatis och morötter. Skär potatisen i cirka 3 cm stora bitar och morötterna i något mindre bitar. Skala löken och skär den i klyftor.','Lägg potatis, morötter och lök i en stor skål. Tillsätt rapsolja, rosmarin, pressad eller finhackad vitlök, salt och svartpeppar. Blanda så att allt täcks lätt av olja och kryddor.','Fördela rotfrukterna i ett jämnt lager på plåten. Lägg kycklingdelarna ovanpå med lite mellanrum. Tvätta händer, redskap och ytor som varit i kontakt med rå kyckling.','Tillaga mitt i ugnen cirka 35–45 minuter. Vänd gärna rotfrukterna en gång efter ungefär halva tiden.','Kontrollera den största kycklingdelen. Kycklingen ska vara helt genomlagad. Med termometer ska den tjockaste delen nå minst 72 °C utan att termometern ligger mot ben. Rotfrukterna ska vara mjuka och ha fått färg.'],doneness:'Kycklingen ska vara helt genomlagad. Med termometer: minst 72 °C i den tjockaste delen utan kontakt med ben. Potatis och morötter ska vara mjuka.',recipeStandard:2})}
standardizeOvenChicken();
injectInventoryUI();
function show(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));if(id==='recipeBank')renderBank();if(id==='foodLog')renderMeals();if(id==='inventory')renderInventory();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.open))); $('#homeButton').addEventListener('click',()=>show('home'));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state[b.dataset.filter]=b.dataset.value;$$(`[data-filter="${b.dataset.filter}"]`).forEach(x=>x.classList.toggle('active',x===b))}));
function card(r){return `<article class="recipe-card"><div class="meta"><span class="badge">${r.emoji}</span><span class="badge">⏱️ ${r.time} min</span><span class="badge">${r.budget==='low'?'💰':'💰💰'}</span></div><h3>${r.name}</h3><p>${r.tip||''}</p><button class="primary" onclick="openRecipe('${r.id}')">Öppna recept</button></article>`}
function renderCards(target,list,empty='Inga träffar ännu.'){const e=$(target);if(e)e.innerHTML=list.length?list.map(card).join(''):`<div class="empty">${empty}</div>`}
function renderBank(list=recipes){renderCards('#recipeBankResults',list)}
$('#recipeSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderBank(recipes.filter(r=>(r.name+' '+r.ingredients.join(' ')+' '+r.tags.join(' ')).toLowerCase().includes(q)))});
$$('[data-recipe-tag]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.recipeTag;renderBank(t==='alla'?recipes:recipes.filter(r=>r.tags.includes(t)))}));
function budgetOk(r){return state.budget==='any'||!state.budget||r.budget===state.budget} function timeOk(r){return !state.time||r.time<=Number(state.time)} function tagOk(r){return !state.tag||state.tag==='överraska'||r.tags.includes(state.tag)}
$('#showSuggestions')?.addEventListener('click',()=>renderCards('#suggestions',recipes.filter(r=>budgetOk(r)&&timeOk(r)&&tagOk(r)).sort(()=>Math.random()-.5).slice(0,3)));
function textMatch(r,q){q=q.toLowerCase().trim();return (r.name+' '+r.ingredients.join(' ')+' '+r.leftovers.join(' ')).toLowerCase().includes(q)}
function rescueTerms(q){return [...new Set(String(q||'').split(',').map(x=>canonicalName(x)).filter(Boolean))]}
function rescueFoodMatch(food,term){
  food=canonicalName(food);term=canonicalName(term);
  if(!food||!term)return false;
  if(food===term)return true;
  const words=food.split(' ');
  return words.includes(term);
}
function rescueNameMatch(name,term){
  name=canonicalName(name);term=canonicalName(term);
  if(!name||!term)return false;
  return name.split(' ').some(word=>word===term||word.startsWith(term));
}
function rescueTermStrength(r,term){
  const ingredients=(r.ingredients||[]).map(x=>parseIngredient(x).name).filter(Boolean);
  if(ingredients[0]&&rescueFoodMatch(ingredients[0],term))return 6;
  if(rescueNameMatch(r.name||'',term))return 5;
  return 0;
}
function rescueScore(r,terms){
  const strengths=terms.map(term=>rescueTermStrength(r,term));
  return {strongMatched:strengths.filter(Boolean).length,totalStrength:strengths.reduce((sum,x)=>sum+x,0)};
}
$('#ingredientSearch')?.addEventListener('click',()=>{const q=$('#ingredientInput').value;renderCards('#ingredientResults',q.trim()?recipes.filter(r=>textMatch(r,q)).slice(0,8):[],'Skriv en råvara först.')});
$('#leftoverSearch')?.addEventListener('click',()=>{const terms=rescueTerms($('#leftoverInput').value);if(!terms.length){renderCards('#leftoverResults',[],'Skriv vad du har över först.');return}const ranked=recipes.map((r,index)=>({r,index,...rescueScore(r,terms)})).filter(x=>x.strongMatched>0).sort((a,b)=>b.strongMatched-a.strongMatched||b.totalStrength-a.totalStrength||a.index-b.index).slice(0,12).map(x=>x.r);renderCards('#leftoverResults',ranked,'Jag hittar inget recept där det du valt är en tydlig huvudråvara ännu.')});
const lowEnergy={none:['macka','fil'],five:['macka','fil','fetaostkram'],simple:['potatissoppa','potatisbullar','fiskpanetter']};$$('[data-energy]').forEach(b=>b.addEventListener('click',()=>renderCards('#lowEnergyResults',lowEnergy[b.dataset.energy].map(id=>recipes.find(r=>r.id===id)))));
window.openRecipe=id=>{const r=recipes.find(x=>x.id===id);if(!r)return;const facts=[r.servings?`🍽️ ${r.servings} portioner`:null,r.prepTime!=null?`🔪 Förberedelse ${r.prepTime} min`:null,r.cookTime!=null?`🔥 Tillagning ${r.cookTime} min`:null,r.time?`⏱️ Totalt cirka ${r.time} min`:null,r.oven?`🌡️ Ugn ${r.oven}`:null,r.heat?`🔥 ${r.heat}`:null].filter(Boolean);const before=facts.length||r.equipment?.length?`<section class="panel calm"><h3>Innan du börjar</h3>${facts.length?`<p>${facts.join(' · ')}</p>`:''}${r.equipment?.length?`<p><strong>Ta fram:</strong> ${r.equipment.join(', ')}.</p>`:''}</section>`:'';const doneness=r.doneness?`<section class="panel calm"><h3>✓ Hur vet jag att det är klart?</h3><p>${r.doneness}</p></section>`:'';const draft=!r.recipeStandard?`<div class="note"><strong>Receptet håller på att förtydligas.</strong> Det finns i receptbanken, men mängder och steg är ännu inte genomgångna enligt den nya receptstandarden.</div>`:'';$('#recipeDetail').innerHTML=`<article class="recipe-detail"><div class="meta"><span class="badge">${r.emoji}</span><span class="badge">⏱️ ${r.time} min</span><span class="badge">${r.budget==='low'?'💰 Billigt':'💰💰 Mellan'}</span></div><h2>${r.name}</h2>${draft}${before}<p class="lead">En hel maträtt eller byggsten till en måltid. Anpassa efter smak, antal personer och det du har hemma.</p><h3>Det här behöver du</h3><ul class="ingredient-list">${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul><h3>En sak i taget</h3><ol class="steps">${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol>${r.tip?`<div class="panel calm"><strong>Malix tips</strong><p>${r.tip}</p></div>`:''}${doneness}<div class="panel calm"><h3>När maten är lagad</h3><p>Öppna receptet påverkar inte lagret. Tryck först när du faktiskt har lagat maten.</p><button class="primary" type="button" onclick="markRecipeCooked('${r.id}')">✓ Jag lagade detta</button><p id="recipeCookStatus" class="status" aria-live="polite"></p></div><h3>Vad får jag med mig?</h3><p class="note">Näringsberäkning per portion lägger vi till när receptens exakta mängder är fastställda. Här ska senare energi, protein, fiber, fett, kolhydrater samt relevanta vitaminer och mineraler visas utan att maten märks som bra eller dålig.</p></article>`;show('recipe')};
$('#mealForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());const a=JSON.parse(localStorage.getItem('malix-meals')||'[]');a.unshift({...v,date:new Date().toISOString()});localStorage.setItem('malix-meals',JSON.stringify(a.slice(0,100)));e.currentTarget.reset();$('#mealSaved').textContent='Måltiden är sparad ✓';renderMeals()});
function renderMeals(){const a=JSON.parse(localStorage.getItem('malix-meals')||'[]');const el=$('#mealHistory');if(el)el.innerHTML=a.slice(0,10).map(m=>`<article class="recipe-card"><h3>${m.meal}</h3><p>${m.food}</p><small>${m.portion||''} ${m.taste||''} ${m.satiety||''}</small></article>`).join('')}
$('#dailyReflection')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());const a=JSON.parse(localStorage.getItem('en-sak-i-taget-mat-reflections')||'[]');a.unshift({...v,date:new Date().toISOString()});localStorage.setItem('en-sak-i-taget-mat-reflections',JSON.stringify(a.slice(0,60)));$('#reflectionSaved').textContent='Sparat för idag ✓'});