const recipes=[
{id:'fiskpanetter',name:'Fiskpanetter med kalasris och filmjölkssås',emoji:'🐟',time:30,budget:'low',tags:['fisk','familj'],ingredients:['fiskpanetter','ris','ärtor','majs','paprika','filmjölk','majonnäs','bostongurka','dill','citron'],leftovers:['ris'],plants:5,tip:'Kalasris är vanligt ris som får färg och smak av ärtor, majs och paprika.',steps:['Tillaga fiskpanetterna enligt förpackningen.','Koka ris och blanda med ärtor, majs och paprika till kalasris.','Rör ihop filmjölk med lite majonnäs, bostongurka, dill och citron.','Servera allt som en hel måltid.']},
{id:'stroganoff',name:'Korvstroganoff à la Malix',emoji:'🍲',time:30,budget:'low',tags:['familj','gryta'],ingredients:['korv','lök','tomatpuré','dijonsenap','chili','buljong','grädde eller valfri bas','ris'],leftovers:['ris'],plants:3,tip:'Dijonsenap, tomatpuré och lite chili ger mer djup i smaken.',steps:['Skär korv och lök och bryn i en gryta.','Rör ner tomatpuré, dijonsenap och lite chili.','Tillsätt buljong och gräddig bas och låt puttra.','Servera med ris och gärna grönsaker.']},
{id:'kycklingmalix',name:'Krispig kyckling à la Malix med jordnötssås',emoji:'🍗',time:40,budget:'mid',tags:['kyckling','familj'],ingredients:['kyckling','majsstärkelse','ägg','eventuellt ströbröd','olja','jordnötssås','ris','ärtor','majs','paprika','wokgrönsaker'],leftovers:['ris'],plants:5,tip:'Kalasris eller vanligt ris fungerar. Wokgrönsaker vid sidan gör det till en hel måltid.',steps:['Förbered kycklingen i små bitar. Om du använder bikarbonat/bakpulver som mörningsmetod, skölj bort det före panering.','Vänd bitarna i majsstärkelse och därefter ägg; ströbröd är valfritt.','Tillaga kycklingen helt igenom i olja och hantera het olja försiktigt.','Servera med jordnötssås, ris och wokgrönsaker.']},
{id:'rotfrukter',name:'Rostade rotfrukter à la Malix',emoji:'🥕',time:45,budget:'low',tags:['vegetariskt','tillbehör','ta-vad-du-har'],ingredients:['valfria rotfrukter','gärna rödbetor','olivolja','rosmarin eller timjan','chili','vitlök','fetaost','salt','peppar'],leftovers:['fetaost','rotfrukter'],plants:5,tip:'Lägg rotfrukterna i en påse med olivolja och kryddor, skaka och häll ut på plåten. Perfekt när fetaosten behöver gå åt.',steps:['Skär de rotfrukter du har. Råa eller förkokta rödbetor kan användas.','Blanda i en påse med olivolja, örter, chili, vitlök, salt och peppar.','Häll ut på plåt och rosta tills rotfrukterna är mjuka och har fått färg.','Smula över fetaost mot slutet eller vid servering.']},
{id:'tzatziki',name:'Tzatziki à la Malix',emoji:'🥒',time:15,budget:'low',tags:['vegetariskt','tillbehör'],ingredients:['1 kg turkisk yoghurt','1 gurka','7 vitlöksklyftor','olivolja','salt','peppar','eventuellt citron'],leftovers:['gurka','yoghurt'],plants:3,tip:'Ringla gärna lite finare olivolja över vid servering. Citron är valfritt.',steps:['Riv gurkan och pressa ur en del vätska.','Blanda med turkisk yoghurt och pressad vitlök.','Smaka av med olivolja, salt, peppar och eventuellt citron.']},
{id:'fetaostkram',name:'Fetaostkräm à la Malix',emoji:'🧄',time:10,budget:'low',tags:['vegetariskt','tillbehör'],ingredients:['turkisk yoghurt','fetaost','rikligt med vitlök'],leftovers:['fetaost','yoghurt'],plants:1,tip:'Mängderna kan anpassas efter hur krämig och vitlökig du vill ha den.',steps:['Mosa fetaosten.','Blanda med turkisk yoghurt.','Pressa i rikligt med vitlök och smaka av.']},
{id:'chili',name:'Chili con carne – långkok med nötkött',emoji:'🌶️',time:180,budget:'mid',tags:['gryta','slowcooker'],ingredients:['nötkött i bitar','lök','vitlök','chili','tomat','bönor','kryddor','vitt bröd','grönsallad'],leftovers:[],plants:5,tip:'Malix tips: har du bara ätit köttfärsvarianten, prova någon gång med nötkött i bitar. Anpassa chilin efter din smak.',steps:['Bryn köttet och lägg i gryta.','Tillsätt lök, vitlök, chili, tomat, bönor och kryddor.','Låt gå långsamt tills köttet är mört.','Servera med färskt vitt bröd och en enkel grönsallad.']},
{id:'chilibillig',name:'Chili con carne – billigare köttfärsvariant',emoji:'🌶️',time:40,budget:'low',tags:['köttfärs','gryta','familj'],ingredients:['köttfärs','lök','vitlök','chili','tomat','bönor'],leftovers:[],plants:4,tip:'En vardagsvariant när du vill ha chili con carne snabbare och billigare.',steps:['Bryn köttfärs och lök.','Tillsätt vitlök, chili, tomat och bönor.','Låt puttra och smaka av.']},
{id:'kalops',name:'Klassisk kalops',emoji:'🥘',time:150,budget:'mid',tags:['gryta','slowcooker','familj'],ingredients:['nötkött','gul lök','morot','lagerblad','kryddpeppar','buljong','potatis'],leftovers:[],plants:4,tip:'Kan göras på spisen eller i slowcooker. Aktiv tid är betydligt kortare än totaltiden.',steps:['Bryn köttet och löken.','Tillsätt morot, lagerblad, kryddpeppar och buljong.','Låt sjuda långsamt tills köttet är mört.','Servera med kokt potatis.']},
{id:'pulledpork',name:'Pulled pork med cola – slowcooker',emoji:'🍖',time:480,budget:'mid',tags:['slowcooker','familj'],ingredients:['fläskkött för långkok','lök','vitlök','cola','kryddor','tomat- eller BBQ-smaksättning'],leftovers:[],plants:2,tip:'Lite aktiv tid, lång total tid. Förbered när du har ork och låt maten sköta sig.',steps:['Lägg ingredienserna i slowcookern.','Tillaga länge tills köttet är genomlagat och mycket mört.','Dra isär köttet och blanda med såsen.']},
{id:'risgryn',name:'Risgrynsgröt i slowcooker',emoji:'🥣',time:180,budget:'low',tags:['slowcooker','vegetariskt'],ingredients:['grötris','mjölk','vatten','salt'],leftovers:[],plants:1,tip:'Malix tips: rör i gröten och stäng av innan den känns helt färdigtjock – den fortsätter att tjockna.',steps:['Blanda ingredienserna i slowcookern.','Tillaga på låg värme och rör om då och då, särskilt mot slutet.','Stäng av innan gröten blivit för tjock.']},
{id:'kottbullar',name:'Köttbullar med potatis och sås',emoji:'🥔',time:45,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','lök','ägg','ströbröd','mjölk','potatis','sås','grönsaker'],leftovers:[],plants:3,tip:'Gör gärna många och frys in – då finns en enkel middag en annan dag.',steps:['Blanda köttfärssmet och forma köttbullar.','Stek eller ugnstillaga tills de är genomlagade.','Servera med potatis, sås och grönsaker.']},
{id:'pannbiff',name:'Pannbiff med lök',emoji:'🥩',time:45,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','lök','ägg','ströbröd','mjölk','potatis','sås'],leftovers:[],plants:2,tip:'Stekt lök ovanpå gör mycket för den klassiska smaken.',steps:['Blanda färsen och forma biffar.','Stek biffarna helt igenom.','Stek löken mjuk och servera med potatis och sås.']},
{id:'kottgrotta',name:'Köttgrotta à la Malix med flødeost och bacon',emoji:'🥩',time:60,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärssmet','pikant- eller vitlöksfärskost/flødeost','bacon','valfria tillbehör'],leftovers:[],plants:1,tip:'Välj pikant flødeost för kryddigare smak eller vitlöksvariant om du gillar vitlök.',steps:['Forma köttfärssmeten med en fördjupning/fyllning av flødeost i mitten.','Forma ihop och lägg bacon runt om.','Ugnstillaga tills köttet är helt genomlagat.','Servera med exempelvis potatis, rostade rotfrukter och sallad.']},
{id:'macka',name:'Smörgåsmåltid med pålägg, frukt eller grönt',emoji:'🥪',time:5,budget:'low',tags:['snabbt','familj'],ingredients:['bröd','pålägg','frukt eller grönt'],leftovers:[],plants:2,tip:'En måltid behöver inte vara komplicerad.',steps:['Ta fram bröd och pålägg.','Lägg till frukt eller grönsaker om du har.']},
{id:'fil',name:'Fil eller yoghurt med müsli och frukt',emoji:'🥣',time:3,budget:'low',tags:['snabbt','vegetariskt'],ingredients:['fil eller yoghurt','müsli','frukt eller bär'],leftovers:[],plants:2,tip:'Passar när orken är låg.',steps:['Häll upp fil eller yoghurt.','Lägg på müsli och frukt eller bär.']},
{id:'potatisbullar',name:'Potatisbullar av överblivet potatismos',emoji:'🥔',time:20,budget:'low',tags:['vegetariskt','familj'],ingredients:['potatismos','ägg','mjöl','valfria tillbehör'],leftovers:['potatismos'],plants:1,tip:'Ett enkelt sätt att ge potatismoset ett nytt liv.',steps:['Blanda kallt mos med ägg och lite mjöl till en formbar smet.','Forma och stek tills de fått fin yta.','Servera med det du tycker om.']},
{id:'potatissoppa',name:'Potatissoppa av överblivet potatismos',emoji:'🥣',time:15,budget:'low',tags:['snabbt','vegetariskt'],ingredients:['potatismos','buljong','lök','mjölk eller annan bas'],leftovers:['potatismos'],plants:2,tip:'Späd moset till soppa och smaka dig fram.',steps:['Fräs lök om du vill.','Rör ut moset med buljong och valfri mjölkbas.','Värm och smaka av.']}
];
const state={time:null,budget:'any',tag:null}; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];

const INVENTORY_KEY='malix-inventory-v1';
const optionalWords=/^(eventuellt|gärna|valfri|valfria|rikligt|lite)\b/i;
function loadInventory(){try{const x=JSON.parse(localStorage.getItem(INVENTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveInventory(items){localStorage.setItem(INVENTORY_KEY,JSON.stringify(items));renderInventory()}
function cleanName(s=''){return String(s).toLowerCase().replace(/^(eventuellt|gärna|valfri|valfria|rikligt|lite)\s+/,'').replace(/\beller\b.*$/,'').replace(/[^a-zåäö0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function canonicalName(s=''){let n=cleanName(s);const aliases=[[/vitlöksklyft.*/,'vitlök'],[/^gul lök$/,'lök'],[/^grötris$/,'ris'],[/^turkisk yoghurt$/,'turkisk yoghurt'],[/^fil eller yoghurt$/,'yoghurt'],[/^mjölk eller annan bas$/,'mjölk'],[/^grädde eller valfri bas$/,'grädde']];aliases.forEach(([r,v])=>{if(r.test(n))n=v});return n}
function parseIngredient(text){const original=String(text).trim();if(optionalWords.test(original))return {optional:true,name:canonicalName(original),amount:null,unit:null,original};let m=original.match(/^(\d+(?:[.,]\d+)?)\s*(kg|g|l|dl|ml)\s+(.+)$/i);if(m)return {optional:false,amount:Number(m[1].replace(',','.')),unit:m[2].toLowerCase(),name:canonicalName(m[3]),original};m=original.match(/^(\d+(?:[.,]\d+)?)\s+(.+)$/i);if(m)return {optional:false,amount:Number(m[1].replace(',','.')),unit:'st',name:canonicalName(m[2]),original};return {optional:false,amount:null,unit:null,name:canonicalName(original),original}}
function toBase(amount,unit){unit=(unit||'').toLowerCase();if(unit==='kg')return {value:amount*1000,kind:'mass'};if(unit==='g')return {value:amount,kind:'mass'};if(unit==='l')return {value:amount*1000,kind:'volume'};if(unit==='dl')return {value:amount*100,kind:'volume'};if(unit==='ml')return {value:amount,kind:'volume'};return {value:amount,kind:'count'}}
function fromBase(value,unit){unit=(unit||'').toLowerCase();if(unit==='kg')return value/1000;if(unit==='g')return value;if(unit==='l')return value/1000;if(unit==='dl')return value/100;if(unit==='ml')return value;return value}
function sameFood(a,b){a=canonicalName(a);b=canonicalName(b);if(!a||!b)return false;return a===b||a.includes(b)||b.includes(a)||(a==='yoghurt'&&b.includes('yoghurt'))||(b==='yoghurt'&&a.includes('yoghurt'))}
function findInventoryItem(items,name){return items.find(x=>sameFood(x.name,name))}
function injectInventoryUI(){const grid=document.querySelector('#home .choice-grid');if(grid&&!document.querySelector('[data-open="inventory"]'))grid.insertAdjacentHTML('beforeend','<button class="choice-card" data-open="inventory"><span>🧺</span><strong>Kyl, skafferi & frys</strong><small>Håll koll på vad som finns hemma och låt lagade recept minska lagret.</small></button>');const main=document.querySelector('main');if(main&&!document.querySelector('#inventory'))main.insertAdjacentHTML('beforeend',`<section id="inventory" class="view"><button class="back" data-open="home">← Tillbaka</button><h2>🧺 Kyl, skafferi & frys</h2><p class="note">Lägg in det du vill hålla koll på. När du trycker ”Jag lagade detta” i ett recept minskar lagret.</p><form id="inventoryForm" class="panel record-form"><label>Råvara<input name="name" required placeholder="t.ex. turkisk yoghurt"></label><label>Mängd<input name="quantity" type="number" min="0" step="0.01" required></label><label>Enhet<select name="unit"><option>g</option><option>kg</option><option>ml</option><option>dl</option><option>l</option><option>st</option></select></label><label>Förvaring<select name="location"><option>Kylskåp</option><option>Skafferi</option><option>Frys</option></select></label><button type="submit">Spara i lagret</button></form><p id="inventoryStatus" class="status"></p><div id="inventoryList" class="recipe-grid"></div></section>`);const f=document.querySelector('#inventoryForm');if(f)f.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f).entries());const items=loadInventory();const existing=findInventoryItem(items,v.name);if(existing&&existing.unit===v.unit&&existing.location===v.location)existing.quantity=Number(existing.quantity||0)+Number(v.quantity||0);else items.unshift({id:Date.now().toString(),name:v.name.trim(),quantity:Number(v.quantity||0),unit:v.unit,location:v.location});saveInventory(items);f.reset();document.querySelector('#inventoryStatus').textContent='Sparat ✓'});renderInventory()}
function renderInventory(){const el=document.querySelector('#inventoryList');if(!el)return;const items=loadInventory();el.innerHTML=items.length?items.map((x,i)=>`<article class="recipe-card"><h3>${x.location==='Kylskåp'?'❄️':x.location==='Frys'?'🧊':'🥫'} ${x.name}</h3><p><strong>${Number(x.quantity||0).toLocaleString('sv-SE')} ${x.unit}</strong> · ${x.location}</p><button class="secondary" type="button" onclick="removeInventoryItem(${i})">Ta bort</button></article>`).join(''):'<div class="empty">Lagret är tomt ännu.</div>'}
window.removeInventoryItem=i=>{const items=loadInventory();items.splice(i,1);saveInventory(items)};
function usedAmountFor(ingredient,item){if(ingredient.amount!=null){const need=toBase(ingredient.amount,ingredient.unit),have=toBase(Number(item.quantity||0),item.unit);if(need.kind!==have.kind)return null;return {neededBase:need.value,haveBase:have.value,kind:need.kind}}const answer=prompt(`Hur mycket ${item.name} använde du? Ange mängd i ${item.unit}.`,'');if(answer===null||answer.trim()==='')return null;const n=Number(answer.replace(',','.'));if(!Number.isFinite(n)||n<0)return null;const need=toBase(n,item.unit),have=toBase(Number(item.quantity||0),item.unit);return {neededBase:need.value,haveBase:have.value,kind:need.kind}}
window.markRecipeCooked=id=>{const r=recipes.find(x=>x.id===id);if(!r)return;let items=loadInventory();const deductions=[];const skipped=[];for(const text of r.ingredients){const ing=parseIngredient(text);if(ing.optional)continue;const item=findInventoryItem(items,ing.name);if(!item){skipped.push(text);continue}const used=usedAmountFor(ing,item);if(!used){skipped.push(text);continue}if(used.neededBase>used.haveBase){const ok=confirm(`Du har ${item.quantity} ${item.unit} ${item.name}, men receptet verkar använda mer. Vill du ändå markera receptet som lagat och sätta lagret till 0?`);if(!ok){const s=document.querySelector('#recipeCookStatus');if(s)s.textContent='Inget ändrades i lagret.';return}deductions.push({item,afterBase:0,usedBase:used.haveBase})}else deductions.push({item,afterBase:used.haveBase-used.neededBase,usedBase:used.neededBase})}for(const d of deductions)d.item.quantity=Math.max(0,Number(fromBase(d.afterBase,d.item.unit).toFixed(3)));saveInventory(items);const cooked=JSON.parse(localStorage.getItem('malix-cooked-recipes')||'[]');cooked.unshift({recipeId:r.id,name:r.name,date:new Date().toISOString()});localStorage.setItem('malix-cooked-recipes',JSON.stringify(cooked.slice(0,100)));const s=document.querySelector('#recipeCookStatus');if(s){const changed=deductions.length?`${deductions.length} lagerpost${deductions.length===1?'':'er'} uppdaterades.`:'Inga lagerposter matchade receptet.';const note=skipped.length?' Ingredienser utan match eller angiven mängd lämnades oförändrade.':'';s.textContent=`Lagat ✓ ${changed}${note}`}}

injectInventoryUI();
function show(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));if(id==='recipeBank')renderBank();if(id==='foodLog')renderMeals();if(id==='inventory')renderInventory();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.open))); $('#homeButton').addEventListener('click',()=>show('home'));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state[b.dataset.filter]=b.dataset.value;$$(`[data-filter="${b.dataset.filter}"]`).forEach(x=>x.classList.toggle('active',x===b))}));
function card(r){return `<article class="recipe-card"><div class="meta"><span class="badge">${r.emoji}</span><span class="badge">⏱️ ${r.time} min</span><span class="badge">${r.budget==='low'?'💰':'💰💰'}</span></div><h3>${r.name}</h3><p>${r.tip||''}</p><button class="primary" onclick="openRecipe('${r.id}')">Öppna recept</button></article>`}
function renderCards(target,list,empty='Inga träffar ännu.'){const e=$(target);if(e)e.innerHTML=list.length?list.map(card).join(''):`<div class="empty">${empty}</div>`}
function renderBank(list=recipes){renderCards('#recipeBankResults',list)}
$('#recipeSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderBank(recipes.filter(r=>(r.name+' '+r.ingredients.join(' ')+' '+r.tags.join(' ')).toLowerCase().includes(q)))});
$$('[data-recipe-tag]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.recipeTag;renderBank(t==='alla'?recipes:recipes.filter(r=>r.tags.includes(t)))}));
function budgetOk(r){return state.budget==='any'||!state.budget||r.budget===state.budget} function timeOk(r){return !state.time||r.time<=Number(state.time)} function tagOk(r){return !state.tag||state.tag==='överraska'||r.tags.includes(state.tag)}
$('#showSuggestions')?.addEventListener('click',()=>renderCards('#suggestions',recipes.filter(r=>budgetOk(r)&&timeOk(r)&&tagOk(r)).sort(()=>Math.random()-.5).slice(0,3)));
function textMatch(r,q){q=q.toLowerCase().trim();return (r.name+' '+r.ingredients.join(' ')+' '+r.leftovers.join(' ')).toLowerCase().includes(q)}
$('#ingredientSearch')?.addEventListener('click',()=>{const q=$('#ingredientInput').value;renderCards('#ingredientResults',q.trim()?recipes.filter(r=>textMatch(r,q)).slice(0,8):[],'Skriv en råvara först.')});
$('#leftoverSearch')?.addEventListener('click',()=>{const q=$('#leftoverInput').value;renderCards('#leftoverResults',q.trim()?recipes.filter(r=>textMatch(r,q)).slice(0,8):[],'Skriv vad du har över först.')});
const lowEnergy={none:['macka','fil'],five:['macka','fil','fetaostkram'],simple:['potatissoppa','potatisbullar','fiskpanetter']};$$('[data-energy]').forEach(b=>b.addEventListener('click',()=>renderCards('#lowEnergyResults',lowEnergy[b.dataset.energy].map(id=>recipes.find(r=>r.id===id)))));
window.openRecipe=id=>{const r=recipes.find(x=>x.id===id);$('#recipeDetail').innerHTML=`<article class="recipe-detail"><div class="meta"><span class="badge">${r.emoji}</span><span class="badge">⏱️ ${r.time} min</span><span class="badge">${r.budget==='low'?'💰 Billigt':'💰💰 Mellan'}</span></div><h2>${r.name}</h2><p class="lead">En hel maträtt eller byggsten till en måltid. Anpassa efter smak, antal personer och det du har hemma.</p><h3>Det här behöver du</h3><ul class="ingredient-list">${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul><h3>En sak i taget</h3><ol class="steps">${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol>${r.tip?`<div class="panel calm"><strong>Malix tips</strong><p>${r.tip}</p></div>`:''}<div class="panel calm"><h3>När maten är lagad</h3><p>Öppna receptet påverkar inte lagret. Tryck först när du faktiskt har lagat maten.</p><button class="primary" type="button" onclick="markRecipeCooked('${r.id}')">✓ Jag lagade detta</button><p id="recipeCookStatus" class="status" aria-live="polite"></p></div><h3>Vad får jag med mig?</h3><p class="note">Näringsberäkning per portion lägger vi till när receptens exakta mängder är fastställda. Här ska senare energi, protein, fiber, fett, kolhydrater samt relevanta vitaminer och mineraler visas utan att maten märks som bra eller dålig.</p></article>`;show('recipe')};
$('#mealForm')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());const a=JSON.parse(localStorage.getItem('malix-meals')||'[]');a.unshift({...v,date:new Date().toISOString()});localStorage.setItem('malix-meals',JSON.stringify(a.slice(0,100)));e.currentTarget.reset();$('#mealSaved').textContent='Måltiden är sparad ✓';renderMeals()});
function renderMeals(){const a=JSON.parse(localStorage.getItem('malix-meals')||'[]');const el=$('#mealHistory');if(el)el.innerHTML=a.slice(0,10).map(m=>`<article class="recipe-card"><h3>${m.meal}</h3><p>${m.food}</p><small>${m.portion||''} ${m.taste||''} ${m.satiety||''}</small></article>`).join('')}
$('#dailyReflection')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());const a=JSON.parse(localStorage.getItem('en-sak-i-taget-mat-reflections')||'[]');a.unshift({...v,date:new Date().toISOString()});localStorage.setItem('en-sak-i-taget-mat-reflections',JSON.stringify(a.slice(0,60)));$('#reflectionSaved').textContent='Sparat för idag ✓'});