(() => {
 const KEY='malix-cleaning-square-v1';
 const defaults={
  'Kök':['Plocka undan','Torka bänkar och bord','Rengör diskho','Torka spis','Dammsug golvet','Torka golvet'],
  'Vardagsrum':['Plocka undan','Damma fria ytor','Torka bord','Dammsug soffa vid behov','Dammsug golvet','Torka golvet vid behov'],
  'Sovrum':['Bädda sängen','Plocka undan','Damma fria ytor','Byt sängkläder vid behov','Dammsug golvet','Torka golvet vid behov'],
  'Badrum / toalett':['Rengör toalett','Rengör handfat','Torka spegel','Rengör dusch eller badkar','Torka fria ytor','Dammsug och torka golvet'],
  'Hall':['Plocka undan skor och ytterkläder','Torka fria ytor','Damma vid behov','Dammsug golvet','Torka golvet'],
  'Övrigt':['Plocka undan','Damma','Dammsug','Torka golvet']
 };
 const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
 const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
 function state(){const s=load();s.rooms=s.rooms||Object.fromEntries(Object.entries(defaults).map(([name,tasks])=>[name,{standard:tasks,custom:[]}]));s.done=s.done||{};return s}
 function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
 function show(id){document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));document.querySelector(`#${id}`)?.classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})}
 function addHomeCard(){const grid=document.querySelector('#home .choice-grid');if(!grid||grid.querySelector('[data-open="cleaning"]'))return;const b=document.createElement('button');b.type='button';b.className='choice-card cleaning-home-card';b.dataset.open='cleaning';b.innerHTML='<span>🧹</span><strong>Mitt hem</strong><small>Städa en sak, en fyrkant eller ett rum i taget.</small>';grid.appendChild(b)}
 function buildView(){let sec=document.querySelector('#cleaning');const main=document.querySelector('main');if(!main)return null;if(!sec){sec=document.createElement('section');sec.id='cleaning';sec.className='view';main.appendChild(sec)}sec.innerHTML=`<button type="button" class="back" data-clean-home>← Tillbaka</button><h2>🧹 Mitt hem – en sak i taget</h2><p class="note">Du behöver inte göra allt. Välj det som passar idag.</p><div class="panel calm"><h3>Vad orkar du idag?</h3><div class="chips"><button type="button">En liten sak</button><button type="button">En fyrkant</button><button type="button">Hela rummet</button></div></div><div id="cleanRooms" class="recipe-grid"></div><section class="panel"><h3>➕ Lägg till eget rum</h3><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="newRoomName" placeholder="t.ex. Tvättstuga, kontor eller barnrum"><button type="button" class="secondary" id="addRoom">Lägg till rum</button></div></section>`;return sec}
 function render(){const root=document.querySelector('#cleanRooms');if(!root)return;const s=state(),day=today();s.done[day]=s.done[day]||{};root.innerHTML=Object.entries(s.rooms).map(([room,data],ri])=>{const all=[...(data.standard||[]),...(data.custom||[])];return `<article class="recipe-card"><h3>${room}</h3>${all.map((task,i)=>{const id=`${room}::${task}`;return `<label style="display:flex;gap:10px;align-items:flex-start;margin:8px 0"><input type="checkbox" data-clean-task="${encodeURIComponent(id)}" ${s.done[day][id]?'checked':''}><span>${task}</span>${i>=(data.standard||[]).length?`<button type="button" class="secondary" data-remove-custom="${ri}:${i-(data.standard||[]).length}" style="margin-left:auto">Ta bort</button>`:''}</label>`}).join('')}<div class="panel calm" style="margin-top:12px"><strong>✏️ Mina egna saker i det här rummet</strong><p class="note">Skriv en sak per rad. Det sparas och finns kvar nästa gång.</p><textarea data-custom-text="${ri}" rows="3" placeholder="T.ex. Torka köksfläkten\nVattna blommorna"></textarea><button type="button" class="secondary" data-add-custom="${ri}">Spara mina saker</button></div></article>`}).join('');
 root.querySelectorAll('[data-clean-task]').forEach(el=>el.onchange=()=>{const st=state(),d=today();st.done[d]=st.done[d]||{};st.done[d][decodeURIComponent(el.dataset.cleanTask)]=el.checked;save(st)});
 root.querySelectorAll('[data-add-custom]').forEach(btn=>btn.onclick=()=>{const st=state(),name=Object.keys(st.rooms)[+btn.dataset.addCustom],ta=root.querySelector(`[data-custom-text="${btn.dataset.addCustom}"]`),items=ta.value.split('\n').map(x=>x.trim()).filter(Boolean);st.rooms[name].custom=[...(st.rooms[name].custom||[]),...items.filter(x=>!(st.rooms[name].custom||[]).includes(x))];save(st);render()});
 root.querySelectorAll('[data-remove-custom]').forEach(btn=>btn.onclick=()=>{const [ri,ci]=btn.dataset.removeCustom.split(':').map(Number),st=state(),name=Object.keys(st.rooms)[ri];st.rooms[name].custom.splice(ci,1);save(st);render()});
 const add=document.querySelector('#addRoom');if(add&&!add.dataset.wired){add.dataset.wired='1';add.onclick=()=>{const input=document.querySelector('#newRoomName'),name=input.value.trim();if(!name)return;const st=state();if(!st.rooms[name])st.rooms[name]={standard:[],custom:[]};save(st);input.value='';render()}}
 }
 function wire(){document.addEventListener('click',e=>{if(e.target.closest('[data-open="cleaning"]')){e.preventDefault();buildView();render();show('cleaning')}if(e.target.closest('[data-clean-home],[data-cleaning-back]')){e.preventDefault();show('home')}},true)}
 buildView();addHomeCard();render();wire();
})();