(()=>{
  const PREFIXES=['malix-'];
  const META_KEY='malix-cloud-meta-v2';
  const CONFIG=window.MALIX_CLOUD||{};
  const isAppKey=k=>PREFIXES.some(p=>String(k).startsWith(p))&&!String(k).startsWith('malix-cloud-meta');
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let client=null,user=null,syncTimer=null,applying=false,syncing=false;

  function snapshot(){const data={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(isAppKey(k))data[k]=localStorage.getItem(k)}return data}
  function applySnapshot(data){if(!data||typeof data!=='object')return;applying=true;try{const existing=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(isAppKey(k))existing.push(k)}existing.forEach(k=>{if(!(k in data))localStorage.removeItem(k)});Object.entries(data).forEach(([k,v])=>{if(isAppKey(k)){if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,String(v))}})}finally{applying=false}document.dispatchEvent(new CustomEvent('malix-cloud-updated'))}
  function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return{}}}
  function saveMeta(x){localStorage.setItem(META_KEY,JSON.stringify(x))}
  function configured(){return !!(CONFIG.url&&CONFIG.anonKey&&window.supabase?.createClient)}
  function setStatus(text,kind=''){document.querySelectorAll('[data-cloud-status]').forEach(x=>{x.textContent=text;x.dataset.kind=kind})}
  async function remoteRow(){if(!client||!user)return null;const {data,error}=await client.from('user_app_state').select('state,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
  async function push(){if(!client||!user||applying||syncing)return;syncing=true;try{const state=snapshot(),now=new Date().toISOString();const {data,error}=await client.from('user_app_state').upsert({user_id:user.id,state,updated_at:now},{onConflict:'user_id'}).select('updated_at').single();if(error)throw error;const at=data?.updated_at||now;saveMeta({userId:user.id,lastSeenRemoteAt:at,lastPushAt:at});setStatus('Synkad '+new Date(at).toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'}),'ok')}finally{syncing=false}}
  async function pull(){if(!client||!user||syncing)return 'busy';syncing=true;try{const remote=await remoteRow();if(!remote)return 'empty';const m=meta();if(remote.updated_at&&remote.updated_at!==m.lastSeenRemoteAt){applySnapshot(remote.state||{});saveMeta({...m,userId:user.id,lastSeenRemoteAt:remote.updated_at});return 'remote'}return 'same'}finally{syncing=false}}
  function queuePush(){if(!user||applying)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>push().catch(e=>{console.error(e);setStatus('Kunde inte synka just nu','error')}),700)}
  async function firstSync(){const remote=await remoteRow();if(remote){applySnapshot(remote.state||{});saveMeta({userId:user.id,lastSeenRemoteAt:remote.updated_at||''});return 'remote'}await push();return 'local'}

  async function signIn(email,password){const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;const source=await firstSync();renderAccount();setStatus(source==='remote'?'Molndata hämtad till den här enheten.':'Första synkningen är klar.','ok')}
  async function signUp(email,password){const {data,error}=await client.auth.signUp({email,password});if(error)throw error;if(!data.session){setStatus('Kontrollera din e-post och bekräfta kontot.','ok');return}user=data.user;await firstSync();renderAccount()}
  async function signOut(){await client.auth.signOut();user=null;renderAccount();setStatus('Utloggad.','')}

  function accountPanel(){let panel=document.querySelector('#malixCloudPanel');if(panel)return panel;panel=document.createElement('section');panel.id='malixCloudPanel';panel.className='panel calm';panel.style.margin='16px 0';const home=document.querySelector('#home');const target=home?.querySelector('.hero-card')||document.querySelector('main');if(target?.parentElement)target.insertAdjacentElement('afterend',panel);return panel}
  function renderAccount(){const p=accountPanel();if(!p)return;if(!configured()){p.innerHTML='<p class="eyebrow">Konto & synkning</p><h3>☁️ Synkning förberedd</h3><p data-cloud-status class="status"></p>';return}if(user){p.innerHTML=`<p class="eyebrow">Konto & synkning</p><h3>☁️ Synkad mellan dina enheter</h3><p>Inloggad som <strong>${esc(user.email||'')}</strong>.</p><div class="chips"><button type="button" class="secondary" data-cloud-pull>Hämta från molnet</button><button type="button" class="secondary" data-cloud-push>Spara till molnet</button><button type="button" class="secondary" data-cloud-logout>Logga ut</button></div><p class="note">När du ändrar något sparas det automatiskt till molnet. Hämta från molnet använder alltid den senaste gemensamma kopian.</p><p data-cloud-status class="status"></p>`;return}p.innerHTML=`<p class="eyebrow">Konto & synkning</p><h3>☁️ Logga in</h3><p>Samma konto används på mobil och dator.</p><label>E-post<input type="email" data-cloud-email autocomplete="email"></label><label>Lösenord<input type="password" data-cloud-password autocomplete="current-password" minlength="8"></label><div class="chips"><button type="button" class="primary" data-cloud-login>Logga in</button><button type="button" class="secondary" data-cloud-signup>Skapa konto</button></div><p data-cloud-status class="status"></p>`}

  function wire(){document.addEventListener('click',async e=>{const p=e.target.closest('#malixCloudPanel');if(!p)return;try{if(e.target.closest('[data-cloud-pull]')){setStatus('Hämtar…');const source=await pull();setStatus(source==='remote'?'Senaste molndata hämtad.':'Du har redan senaste molndatan.','ok');return}if(e.target.closest('[data-cloud-push]')){setStatus('Sparar…');await push();return}if(e.target.closest('[data-cloud-logout]')){await signOut();return}const email=p.querySelector('[data-cloud-email]')?.value.trim(),password=p.querySelector('[data-cloud-password]')?.value||'';if(e.target.closest('[data-cloud-login]')){if(!email||!password){setStatus('Fyll i e-post och lösenord.','error');return}setStatus('Loggar in…');await signIn(email,password);return}if(e.target.closest('[data-cloud-signup]')){if(!email||password.length<8){setStatus('Ange e-post och minst 8 tecken i lösenordet.','error');return}setStatus('Skapar konto…');await signUp(email,password)}}catch(err){console.error(err);setStatus(err?.message||'Något gick fel.','error')}});
    const origSet=Storage.prototype.setItem,origRemove=Storage.prototype.removeItem;
    Storage.prototype.setItem=function(k,v){const r=origSet.call(this,k,v);if(this===localStorage&&isAppKey(k)&&!applying)queuePush();return r};
    Storage.prototype.removeItem=function(k){const r=origRemove.call(this,k);if(this===localStorage&&isAppKey(k)&&!applying)queuePush();return r};
    window.addEventListener('focus',()=>{if(user)pull().then(s=>{if(s==='remote')setStatus('Nyare molndata hämtad.','ok')}).catch(console.error)});
    document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user)pull().then(s=>{if(s==='remote')setStatus('Nyare molndata hämtad.','ok')}).catch(console.error)});
  }

  async function init(){renderAccount();wire();if(!configured())return;client=window.supabase.createClient(CONFIG.url,CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getSession();user=data.session?.user||null;renderAccount();if(user){try{const source=await firstSync();setStatus(source==='remote'?'Molndata hämtad till den här enheten.':'Synkningen är klar.','ok')}catch(e){console.error(e);setStatus('Kunde inte läsa molndata just nu.','error')}}client.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;renderAccount()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();