(()=>{
  const PREFIX='malix-', META='malix-cloud-meta-v2', CONFIG=window.MALIX_CLOUD||{};
  const isAppKey=k=>String(k).startsWith(PREFIX)&&!String(k).startsWith('malix-cloud-meta');
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let client=null,user=null,syncTimer=null,applying=false,syncing=false;
  function snapshot(){const d={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(isAppKey(k))d[k]=localStorage.getItem(k)}return d}
  function clearAppData(){applying=true;try{const ks=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(isAppKey(k)||k===META)ks.push(k)}ks.forEach(k=>localStorage.removeItem(k))}finally{applying=false}}
  function applySnapshot(data){applying=true;try{const ks=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(isAppKey(k))ks.push(k)}ks.forEach(k=>localStorage.removeItem(k));Object.entries(data||{}).forEach(([k,v])=>{if(isAppKey(k)&&v!=null)localStorage.setItem(k,String(v))})}finally{applying=false}document.dispatchEvent(new CustomEvent('malix-cloud-updated'))}
  function meta(){try{return JSON.parse(localStorage.getItem(META)||'{}')}catch{return{}}}function saveMeta(x){localStorage.setItem(META,JSON.stringify(x))}
  function configured(){return !!(CONFIG.url&&CONFIG.anonKey&&window.supabase?.createClient)}
  function setStatus(t){document.querySelectorAll('[data-cloud-status],[data-gate-status]').forEach(x=>x.textContent=t)}
  async function remoteRow(){if(!client||!user)return null;const {data,error}=await client.from('user_app_state').select('state,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
  async function push(){if(!client||!user||applying||syncing)return;syncing=true;try{const now=new Date().toISOString();const {data,error}=await client.from('user_app_state').upsert({user_id:user.id,state:snapshot(),updated_at:now},{onConflict:'user_id'}).select('updated_at').single();if(error)throw error;const at=data?.updated_at||now;saveMeta({userId:user.id,lastSeenRemoteAt:at});setStatus('Synkad '+new Date(at).toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'}))}finally{syncing=false}}
  async function pull(force=false){if(!client||!user||syncing)return'busy';syncing=true;try{const r=await remoteRow();if(!r)return'empty';const m=meta();if(force||r.updated_at!==m.lastSeenRemoteAt){applySnapshot(r.state||{});saveMeta({userId:user.id,lastSeenRemoteAt:r.updated_at||''});return'remote'}return'same'}finally{syncing=false}}
  function queuePush(){if(!user||applying)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>push().catch(e=>setStatus(e.message||'Kunde inte synka')),700)}
  async function firstSync(){const r=await remoteRow();if(r){applySnapshot(r.state||{});saveMeta({userId:user.id,lastSeenRemoteAt:r.updated_at||''});return'remote'}await push();return'local'}
  function gate(){let g=document.querySelector('#malixAuthGate');if(!g){g=document.createElement('div');g.id='malixAuthGate';g.style.cssText='position:fixed;inset:0;z-index:99999;background:#f7f4ed;padding:20px;overflow:auto';document.body.appendChild(g)}return g}
  function showGate(){const g=gate();g.style.display='block';g.innerHTML=`<div style="max-width:520px;margin:6vh auto;background:#fff;padding:24px;border-radius:18px;box-shadow:0 8px 30px rgba(0,0,0,.08)"><p style="font-size:2rem;margin:0">🌿</p><h1>En sak i taget</h1><h2>Logga in</h2><p>Dina registreringar visas först när du är inloggad.</p><label>E-post<input type="email" data-gate-email autocomplete="email"></label><label>Lösenord<input type="password" data-gate-password autocomplete="current-password" minlength="8"></label><div class="chips"><button type="button" class="primary" data-gate-signin>Logga in</button><button type="button" class="secondary" data-gate-signup>Skapa konto</button></div><p class="status" data-gate-status></p></div>`}
  function hideGate(){const g=gate();g.style.display='none'}
  async function signIn(email,password){const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;await firstSync();hideGate();renderAccount()}
  async function signUp(email,password){const {data,error}=await client.auth.signUp({email,password});if(error)throw error;if(!data.session){setStatus('Kontrollera din e-post och bekräfta kontot.');return}user=data.user;await firstSync();hideGate();renderAccount()}
  async function signOut(){if(user)await push();await client.auth.signOut();user=null;clearAppData();renderAccount();showGate()}
  function accountPanel(){let p=document.querySelector('#malixCloudPanel');if(p)return p;p=document.createElement('section');p.id='malixCloudPanel';p.className='panel calm';p.style.margin='16px 0';const home=document.querySelector('#home'),target=home?.querySelector('.hero-card')||document.querySelector('main');target?.parentElement?.insertBefore(p,target.nextSibling);return p}
  function renderAccount(){const p=accountPanel();if(!p)return;if(!configured()){p.innerHTML='<h3>☁️ Synkning förberedd</h3>';return}if(!user){p.innerHTML='<h3>☁️ Utloggad</h3><p>Logga in för att se dina uppgifter.</p>';return}p.innerHTML=`<p class="eyebrow">Konto & synkning</p><h3>☁️ Synkad mellan dina enheter</h3><p>Inloggad som <strong>${esc(user.email||'')}</strong>.</p><div class="chips"><button type="button" class="secondary" data-cloud-pull>Hämta från molnet</button><button type="button" class="secondary" data-cloud-push>Spara till molnet</button><button type="button" class="secondary" data-cloud-logout>Logga ut</button></div><p class="status" data-cloud-status></p>`}
  function wire(){document.addEventListener('click',async e=>{try{if(e.target.closest('[data-gate-signin],[data-gate-signup]')){const g=gate(),email=g.querySelector('[data-gate-email]')?.value.trim(),password=g.querySelector('[data-gate-password]')?.value||'';if(!email||password.length<8){setStatus('Fyll i e-post och minst 8 tecken i lösenordet.');return}if(e.target.closest('[data-gate-signin]'))await signIn(email,password);else await signUp(email,password);return}if(e.target.closest('[data-cloud-pull]')){setStatus('Hämtar…');await pull(true);setStatus('Senaste molndata hämtad.');return}if(e.target.closest('[data-cloud-push]')){setStatus('Sparar…');await push();return}if(e.target.closest('[data-cloud-logout]')){await signOut();return}}catch(err){console.error(err);setStatus(err?.message||'Något gick fel.')}});
    const os=Storage.prototype.setItem,or=Storage.prototype.removeItem;Storage.prototype.setItem=function(k,v){const r=os.call(this,k,v);if(this===localStorage&&isAppKey(k)&&!applying)queuePush();return r};Storage.prototype.removeItem=function(k){const r=or.call(this,k);if(this===localStorage&&isAppKey(k)&&!applying)queuePush();return r};
    window.addEventListener('focus',()=>{if(user)pull().catch(console.error)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user)pull().catch(console.error)})}
  async function init(){wire();renderAccount();if(!configured())return;client=window.supabase.createClient(CONFIG.url,CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getSession();user=data.session?.user||null;if(!user){clearAppData();renderAccount();showGate();return}hideGate();renderAccount();try{await firstSync()}catch(e){console.error(e);setStatus('Kunde inte läsa molndata just nu.')}client.auth.onAuthStateChange((_ev,session)=>{const next=session?.user||null;if(!next){user=null;clearAppData();renderAccount();showGate()}else{user=next;hideGate();renderAccount()}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();