(()=>{
  if (typeof recipes === 'undefined' || !Array.isArray(recipes)) return;
  const add = recipe => { if (!recipes.some(r => r.id === recipe.id)) recipes.push(recipe); };
  const dessertTags = ['efterrätt','något gott','klassisk efterrätt'];

  const popup = recipes.find(r => r.id === 'popupbrod');
  if (popup) {
    popup.tags = [...new Set([...(popup.tags || []), 'efterrätt', 'något gott', 'pannkaksalternativ'])];
    popup.serving = 'Servera varmt till soppa eller gryta. Som efterrätt kan popup-bröden bli små pannkaksbullar med sylt och vispad grädde.';
    popup.swaps = '🍓 Pannkaksbullar: När du inte vill stå och steka pannkakor kan samma popup-bröd serveras med sylt och grädde. En enkel efterrätt efter till exempel soppa.';
  }

  add({id:'malix-appelpaj-pa-en-hoft',name:'Malix enkla paj – på en höft',emoji:'🍎',time:50,budget:'low',tags:[...dessertTags,'paj','äpple','päron','blåbär','rabarber','på en höft','glutenfritt alternativ','Malix-recept'],plants:2,ingredients:['ca 300 g smör','ca 1,5 dl socker','havregryn eller glutenfritt mjöl – tills det blir en deg','vaniljsocker – om du vill','kokos – om du tycker om det','valfri fyllning: äpple, päron, blåbär eller rabarber','kanel och socker till äpple/päron','socker efter smak till bär/rabarber','lite potatismjöl till saftig fyllning som blåbär eller rabarber'],leftovers:['äpplen','päron','blåbär','rabarber'],tip:'🥄 På en höft: Börja med ungefär 300 g smör och 1,5 dl socker och tillsätt havregryn eller glutenfritt mjöl tills degen känns bra att trycka ut. Vi gillar mycket deg.',serving:'Gott som det är eller med vaniljsås, glass eller grädde.',swaps:'🍐 Päronpaj: byt äpplena mot päron. 🫐 Blåbärspaj eller rabarberpaj: använd samma pajdeg men strö lite potatismjöl över den saftiga fyllningen tillsammans med socker så att pajen inte blir onödigt rinnig. Vaniljsocker och kokos är frivilligt.',steps:['Sätt ugnen på 175 grader.','Smält smöret i en kastrull.','Blanda ner socker och sedan havregryn eller glutenfritt mjöl direkt i kastrullen tills det blir en deg. Tillsätt vaniljsocker och kokos om du vill.','Tryck ut en del av degen i botten av en pajform. Spara resten.','För äpple eller päron: skala och klyfta och skaka med kanel och socker i en påse. För blåbär eller rabarber: blanda med socker efter smak och lite potatismjöl.','Fördela fyllningen över botten.','Tryck eller smula resten av degen ovanpå.','Grädda mitt i ugnen tills pajen är gyllenbrun och frukten eller bären inte längre saftar sig så mycket. Räkna ungefär 30–45 minuter, men låt färg och fyllning avgöra.']});
  add({id:'saffranspannkaka',name:'Saffranspannkaka',emoji:'💛',time:55,budget:'medium',tags:[...dessertTags,'risgrynsgröt','saffran','rester'],plants:1,ingredients:['risgrynsgröt','ägg','mjölk eller grädde','saffran','lite socker efter smak','mandel – valfritt'],leftovers:['risgrynsgröt'],tip:'Ett bra sätt att göra något nytt av risgrynsgröt. Smaka av sötman efter hur söt gröten redan är.',serving:'Servera gärna med sylt och grädde.',swaps:'Mandeln kan uteslutas.',steps:['Sätt ugnen på cirka 200 grader.','Rör ihop risgrynsgröt, ägg, saffran och lite mjölk eller grädde. Smaka av med socker.','Rör i mandel om du vill.','Häll i en smord ugnsform.','Grädda tills pannkakan har stannat och fått fin färg.']});
  add({id:'risgrynspudding',name:'Risgrynspudding',emoji:'🍚',time:45,budget:'low',tags:[...dessertTags,'risgrynsgröt','rester','ugn'],plants:1,ingredients:['risgrynsgröt','ägg','mjölk','lite socker efter smak','vaniljsocker – valfritt'],leftovers:['risgrynsgröt'],tip:'Bra restmat när det finns risgrynsgröt kvar.',serving:'Servera varm eller kall med sylt, bär, saftsås eller lite grädde.',swaps:'Vaniljsocker är valfritt.',steps:['Sätt ugnen på cirka 200 grader.','Rör ihop risgrynsgröt med ägg och lite mjölk.','Smaka av med socker och eventuellt vaniljsocker.','Häll i en smord form.','Grädda tills puddingen har stannat och fått lite färg.']});

  add({id:'farmors-appelmos',name:'Farmors äppelmos med grädde och kanel',emoji:'🍎',time:2,budget:'low',tags:[...dessertTags,'enkelt','billigt','ingen tillagning','Malix-minne'],plants:1,ingredients:['äppelmos','vanlig ovispad grädde','kanel'],leftovers:['äppelmos'],tip:'Tre enkla saker räcker. Grädden ska vara rinnande, precis som farmor serverade den.',serving:'Lägg äppelmos i en skål, häll över ovispad grädde och pudra med kanel.',steps:['Lägg äppelmos i portionsskålar.','Häll över vanlig ovispad grädde.','Strö över kanel och servera.']});
  add({id:'malix-fruktsallad',name:'Malix fruktsallad – smak av sommar',emoji:'🍓',time:10,budget:'low',tags:[...dessertTags,'frukt','bär','ta vad du har','rädda maten','på en höft','Malix-recept'],plants:5,ingredients:['frukt du har hemma','bär – färska eller tinade, om du har','russin – valfritt','kokos – valfritt','nötter eller frön – valfritt'],leftovers:['frukt','bär'],tip:'🥄 På en höft: Inga mängder behövs. Lite tråkig men fortfarande bra frukt kan bli en smak av sommar när den blandas med annan frukt eller bär.',serving:'Ät som den är eller med grädde, yoghurt eller vaniljkvarg.',swaps:'All frukt och alla bär kan varieras. Nötter kan uteslutas helt eller bytas mot frön.',steps:['Gå igenom frukten och använd bara det som fortfarande är friskt och bra.','Skär frukten i bitar och blanda med de bär du har.','Tillsätt russin, kokos, nötter eller frön om du vill.','Servera direkt eller låt stå kallt en stund.']});

  add({id:'klassisk-chokladpudding',name:'Klassisk chokladpudding',emoji:'🍫',time:20,budget:'low',tags:[...dessertTags,'pudding','choklad','billigt'],plants:0,ingredients:['mjölk','kakao','socker','majsstärkelse','vaniljsocker'],leftovers:['mjölk'],tip:'En gammal vardagsklassiker som bygger på vanliga skafferivaror. Majsstärkelse gör den naturligt glutenfri om övriga ingredienser är glutenfria.',serving:'God kall med grädde, bär eller precis som den är.',steps:['Vispa ihop mjölk, kakao, socker och majsstärkelse i en kastrull.','Värm under ständig omrörning tills puddingen tjocknar.','Ta från värmen och smaksätt med vaniljsocker.','Häll upp i skålar och låt svalna.']});
  add({id:'klassisk-vaniljpudding',name:'Klassisk vaniljpudding',emoji:'🍮',time:20,budget:'low',tags:[...dessertTags,'pudding','vanilj','billigt'],plants:0,ingredients:['mjölk','socker','majsstärkelse','vaniljsocker eller vanilj'],leftovers:['mjölk'],tip:'En enkel mjölkpudding med få ingredienser.',serving:'Servera kall med frukt, bär, sylt eller kanel.',steps:['Vispa ihop mjölk, socker och majsstärkelse i en kastrull.','Värm under omrörning tills puddingen tjocknar.','Ta från värmen och smaksätt med vanilj.','Häll upp och kyl.']});
  add({id:'mannagrynspudding',name:'Mannagrynspudding',emoji:'🥣',time:40,budget:'low',tags:[...dessertTags,'mannagryn','pudding','billigt'],plants:0,ingredients:['mjölk','mannagryn','ägg','lite socker','vaniljsocker – valfritt','smör till formen'],leftovers:['mjölk','mannagrynsgröt'],tip:'En klassisk grynpudding som gör enkla basvaror till efterrätt.',serving:'Servera gärna med sylt eller saftsås.',steps:['Koka en ganska tjock mannagrynsgröt.','Låt svalna lite och rör ner ägg, lite socker och eventuellt vaniljsocker.','Häll i smord form.','Grädda i ugn tills puddingen stannat och fått lite färg.']});
  add({id:'fruktsoppa-klassisk',name:'Fruktsoppa – ta den torkade frukt du har',emoji:'🍑',time:35,budget:'low',tags:[...dessertTags,'frukt','torkad frukt','billigt','ta vad du har'],plants:4,ingredients:['torkad frukt, till exempel katrinplommon, aprikoser, russin eller äpple','vatten','socker efter smak','potatismjöl eller majsstärkelse till lätt redning – valfritt'],leftovers:['torkad frukt'],tip:'Det här behöver inte vara en exakt fruktblandning. Använd den torkade frukt som finns hemma.',serving:'Servera varm, ljummen eller kall, gärna med en skvätt mjölk eller grädde om du tycker om det.',steps:['Skär större torkad frukt i bitar.','Koka frukten mjuk i vatten.','Smaka av med lite socker.','Vill du ha soppan lite fylligare kan den redas lätt på slutet.','Låt svalna till den temperatur du tycker om.']});
  add({id:'katrinplommonkompott',name:'Katrinplommonkompott',emoji:'🟣',time:25,budget:'low',tags:[...dessertTags,'katrinplommon','kompott','billigt'],plants:1,ingredients:['katrinplommon','vatten','lite socker efter smak'],leftovers:['katrinplommon'],tip:'Fruktkompott är en gammal enkel efterrätt där frukten får vara huvudsaken.',serving:'Servera kall eller ljummen, som den är eller med mjölk eller grädde.',steps:['Lägg katrinplommon i en kastrull med vatten.','Låt sjuda tills frukten är mjuk.','Smaka av med lite socker om det behövs.','Låt svalna före servering om du vill äta den kall.']});
  add({id:'katrinplommonsuffle',name:'Katrinplommonsufflé',emoji:'🟣',time:45,budget:'low',tags:[...dessertTags,'katrinplommon','sufflé','billigt','gammaldags efterrätt'],plants:1,ingredients:['katrinplommon','vatten','lite socker efter smak','ägg','lite potatismjöl eller majsstärkelse vid behov','smör till formen'],leftovers:['katrinplommon'],tip:'En gammaldags efterrätt där katrinplommonen får stå för smaken. Konsistensen ska vara mjuk och luftig snarare än tung.',serving:'Servera gärna ljummen med kall mjölk eller en skvätt grädde.',steps:['Koka katrinplommonen mjuka i lite vatten och låt svalna något.','Mosa eller hacka dem till en grov puré och smaka av med lite socker.','Separera äggen. Rör ner äggulorna i fruktmassan. Om massan är mycket lös kan du reda den lätt med lite potatismjöl eller majsstärkelse.','Vispa äggvitorna till ett fast skum och vänd försiktigt ner dem i fruktmassan.','Häll i en smord ugnsform.','Grädda i cirka 175–200 grader tills sufflén har rest sig och stannat. Servera ganska snart.']});
  add({id:'brodpudding-radda-brodet',name:'Enkel brödpudding – rädda brödet',emoji:'🍞',time:45,budget:'low',tags:[...dessertTags,'bröd','rädda maten','billigt','rester'],plants:0,ingredients:['torrt eller överblivet bröd','mjölk','ägg','lite socker','vaniljsocker eller kanel','russin – valfritt'],leftovers:['bröd','mjölk'],tip:'Ett gammalt sätt att göra efterrätt av bröd som annars riskerar att bli över.',serving:'Servera ljummen eller kall, gärna med lite grädde, mjölk, sylt eller frukt.',steps:['Skär brödet i mindre bitar.','Låt det suga upp en blandning av mjölk, ägg och lite socker.','Smaksätt med vanilj eller kanel och lägg i russin om du vill.','Häll i smord form och grädda tills puddingen stannat och fått färg.']});
})();