(() => {
 const REF_KEY='malix-reflection-diary-v2',CLEAN_KEY='malix-cleaning-square-v2';
 const load=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}};
 const pad=n=>String(n).padStart(2,'0'),keyOf=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,fmt=k=>new Intl.DateTimeFormat('sv-SE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${k}T12:00:00`)),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
 function cleanItems(d,k){return {checked:Object.entries(d.done?.[k]||{}).filter(([,v])=>v).map(([id])=>{const [room,...task]=id.split('::');return {room,task:task.join('::')}}),free:d.activityLog?.[k]||[],reflection:d.reflections?.[k]||null}}
 function setup(){const form=document.querySelector('#dailyReflection');if(!form||document.querySelector('#mainHistoryTabs'))return;const panel=form.closest('.daily-panel')||form.parentElement,box=document.createElement('section');box.id='mainHistoryTabs';box.className='panel calm';box.style.marginTop='18px';box.innerHTML=`<p class="eyebrow">Historik</p><h3>📖 Min historik</h3><div class="chips" data-history-tabs><button type="button" data-history-tab="reflection" class="active">🌙 Reflektioner</button><button type="button" data-history-tab="cleaning">🧹 Fyrkantstädning</button><button type="button" data-history-tab="food">🍽️ Mat</button></div><div data-history-panel="reflection"></div><div data-history-panel="cleaning" style="display:none"></div><div data-history-panel="food" style="display:none"></div>`;panel.appendChild(box);let active='reflection';
 function renderRef(){const data=load(REF_KEY),out=box.querySelector('[data-history-panel="reflection"]'),keys=Object.keys(data).sort().reverse();out.innerHTML=keys.length?keys.slice(0,31).map(k=>{const r=data[k]||{};return `<details class="history-meal"><summary><strong>${fmt(k)}</strong></summary><p><strong>Vad blev bra idag?</strong><br>${esc(r.good||'–')}</p><p><strong>Vad vill jag göra annorlunda?</strong><br>${esc(r.different||'–')}</p><p><strong>Vad vill jag behålla?</strong><br>${esc(r.keep||'–')}</p></details>`}).join(''):'<p class="empty">Ingen sparad reflektion ännu.</p>'}
 function renderClean(){const d=load(CLEAN_KEY),out=box.querySelector('[data-history-panel="cleaning"]'),keys=[...new Set([...Object.keys(d.done||{}),...Object.keys(d.activityLog||{}),...Object.keys(d.reflections||{})])].sort().reverse();out.innerHTML=keys.length?keys.slice(0,31).map(k=>{const c=cleanItems(d,k);return `<details class="history-meal"><summary><strong>${fmt(k)}</strong> · 🧹</summary>${c.checked.length?`<p><strong>Det här gjorde jag:</strong></p><ul>${c.checked.map(x=>`<li>${esc(x.room)}: ${esc(x.task)}</li>`).join('')}</ul>`:''}${c.free.length?`<p><strong>Egna saker:</strong></p><ul>${c.free.map(x=>`<li>${esc(x.room)}: ${esc(x.text)}</li>`).join('')}</ul>`:''}${c.reflection?`<p><strong>Hur kändes det?</strong> ${esc(c.reflection.feeling||'–')}</p><p><strong>Ork:</strong> ${esc(c.reflection.energy||'–')}</p>${c.reflection.extra?`<p><strong>Extra:</strong> ${esc(c.reflection.extra)}</p>`:''}${c.reflection.note?`<p><strong>Till nästa gång:</strong> ${esc(c.reflection.note)}</p>`:''}`:''}</details>`}).join(''):'<p class="empty">Ingen fyrkantstädning registrerad ännu.</p>'}
 function renderFood(){const out=box.querySelector('[data-history-panel="food"]'),meals=JSON.parse(localStorage.getItem('malix-meals')||'[]'),by={};meals.forEach(m=>{const k=keyOf(m.date?new Date(m.date):new Date());(by[k]??=[]).push(m)});const keys=Object.keys(by).sort().reverse();out.innerHTML=keys.length?keys.slice(0,31).map(k=>`<details class="history-meal"><summary><strong>${fmt(k)}</strong> · ${by[k].length} måltider</summary>${by[k].map(m=>`<p><strong>${esc(m.meal||'Måltid')}</strong><br>${esc(m.food||'')}${m.portion?` (${esc(m.portion)})`:''}</p>`).join('')}</details>`).join(''):'<p class="empty">Ingen mat registrerad ännu.</p>'}
 function showTab(name){active=name;box.querySelectorAll('[data-history-tab]').forEach(b=>b.classList.toggle('active',b.dataset.historyTab===active));box.querySelectorAll('[data-history-panel]').forEach(p=>{p.style.display=p.dataset.historyPanel===active?'block':'none'})}
 function render(){renderRef();renderClean();renderFood();showTab(active)}
 box.querySelector('[data-history-tabs]').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const b=e.target.closest('[data-history-tab]');if(!b)return;showTab(b.dataset.historyTab)});
 form.addEventListener('submit',()=>setTimeout(render,0));document.addEventListener('malix-cleaning-changed',render);document.addEventListener('malix-day-changed',render);window.addEventListener('storage',render);setInterval(render,2000);render()}
 setup();
})();