(() => {
  const localKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const mealKey=m=>window.malixMealDateKey?.(m)||(m?.date?localKey(new Date(m.date)):localKey(new Date()));
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let cursor=new Date();cursor.setDate(1);
  const months=['januari','februari','mars','april','maj','juni','juli','augusti','september','oktober','november','december'];
  function meals(){try{const a=JSON.parse(localStorage.getItem('malix-meals')||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
  function dayMeals(key){return meals().filter(m=>mealKey(m)===key)}
  function renderDay(key){const root=document.querySelector('#calendarDayDetail');if(!root)return;const list=dayMeals(key),d=new Date(key+'T12:00:00'),label=d.toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});if(!list.length){root.innerHTML=`<div class="panel calm"><h4>${label}</h4><p class="note">Ingen mat registrerad den här dagen.</p></div>`;return}const s=window.malixNutritionSummaryForMeals?.(list);root.innerHTML=`<div class="panel calm"><h4>${label}</h4><h4>🍽️ Det här åt du</h4>${list.map(m=>`<article class="recipe-card"><strong>${esc(m.meal||'Måltid')}</strong><p>${esc(m.food||'')}</p>${m.portion?`<small>${esc(m.portion)}</small>`:''}</article>`).join('')}<h4 style="margin-top:16px">🌿 Näringsöversikt</h4><div class="dashboard-grid"><article class="summary-card"><span>⚡ Energi</span><strong>${s?.matched?`≈ ${s.kcal} kcal`:'Kan inte beräknas ännu'}</strong></article><article class="summary-card"><span>💊 Vitaminer & mineraler</span><strong>${s?.micros?.length?esc(s.micros.slice(0,8).join(' · ')):'Ingen tydlig källa kunde beräknas'}</strong></article></div><p class="note">Översikten är ungefärlig och bygger på det du själv har loggat och de mängder som kunnat tolkas.</p></div>`}
  function renderCalendar(){const grid=document.querySelector('#calendarGrid'),title=document.querySelector('#calendarMonth');if(!grid||!title)return;const all=meals(),counts={};all.forEach(m=>{const k=mealKey(m);counts[k]=(counts[k]||0)+1});const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7;title.textContent=`${months[m]} ${y}`;let html='<div class="calendar-weekday">Mån</div><div class="calendar-weekday">Tis</div><div class="calendar-weekday">Ons</div><div class="calendar-weekday">Tor</div><div class="calendar-weekday">Fre</div><div class="calendar-weekday">Lör</div><div class="calendar-weekday">Sön</div>';for(let i=0;i<offset;i++)html+='<span></span>';for(let day=1;day<=last.getDate();day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,n=counts[key]||0;html+=`<button type="button" class="calendar-day${n?' has-data':''}" data-food-day="${key}"><strong>${day}</strong>${n?`<small>${n} måltid${n===1?'':'er'}</small>`:''}</button>`}grid.innerHTML=html;grid.querySelectorAll('[data-food-day]').forEach(b=>b.addEventListener('click',()=>renderDay(b.dataset.foodDay)))}
  document.querySelector('#calendarPrev')?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1);renderCalendar()});
  document.querySelector('#calendarNext')?.addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1);renderCalendar()});
  document.addEventListener('malix-meals-updated',renderCalendar);document.addEventListener('malix-day-changed',renderCalendar);window.addEventListener('storage',renderCalendar);renderCalendar();
})();