(() => {
  const MEALS_KEY='malix-meals';
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const readMeals=()=>{try{const v=JSON.parse(localStorage.getItem(MEALS_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
  const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
  const monthName=key=>{const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('sv-SE',{month:'long',year:'numeric'})};
  const changeMonth=(key,delta)=>{const [y,m]=key.split('-').map(Number);return monthKey(new Date(y,m-1+delta,1))};
  const mealDate=m=>window.malixMealDateKey?.(m)||(m?.date?`${new Date(m.date).getFullYear()}-${String(new Date(m.date).getMonth()+1).padStart(2,'0')}-${String(new Date(m.date).getDate()).padStart(2,'0')}`:'');
  const mealsFor=key=>readMeals().filter(m=>mealDate(m).slice(0,7)===key);
  const ensureView=()=>{let root=document.querySelector('#foodMonth');if(!root){root=document.createElement('section');root.id='foodMonth';root.className='view';document.querySelector('main')?.appendChild(root)}return root};
  const show=id=>{document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id)?.classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})};
  function availableMonths(){const keys=new Set(readMeals().map(mealDate).filter(Boolean).map(x=>x.slice(0,7)));keys.add(monthKey(new Date()));return [...keys].sort().reverse()}
  function cleanFood(s=''){return String(s).replace(/\s*\([^)]*\)/g,'').trim()}
  function foodItems(meals){return meals.flatMap(m=>String(m.food||'').split(/,|\n/).map(cleanFood).filter(Boolean))}
  function overview(meals){if(!meals.length)return '<p class="note">Det finns ingen registrerad mat den här månaden. Du behöver inte fylla i något i efterhand.</p>';const days=new Set(meals.map(mealDate).filter(Boolean));return `<p>Du registrerade mat vid <strong>${meals.length}</strong> tillfällen under <strong>${days.size}</strong> ${days.size===1?'dag':'dagar'}.</p><p class="note">Det här visar bara det du själv har sparat – inte allt du åt under månaden.</p>`}
  function dishes(meals){const items=foodItems(meals);if(!items.length)return '<p class="note">Det finns registreringar, men ingen mattext att sammanställa ännu.</p>';const counts={};items.forEach(x=>{const k=x.toLocaleLowerCase('sv-SE');counts[k]=(counts[k]||{label:x,n:0});counts[k].n++});const top=Object.values(counts).sort((a,b)=>b.n-a.n).slice(0,8);return `<ul>${top.map(x=>`<li>${esc(x.label)}${x.n>1?` <small>· ${x.n} gånger</small>`:''}</li>`).join('')}</ul>`}
  function patterns(meals){if(!meals.length)return '<p class="note">När det finns några registreringar kan möjliga vardagsmönster visas här.</p>';const types={};meals.forEach(m=>{const t=String(m.meal||'Måltid');types[t]=(types[t]||0)+1});const entries=Object.entries(types).sort((a,b)=>b[1]-a[1]);const text=meals.map(m=>String(m.food||'')).join(' ').toLocaleLowerCase('sv-SE');const notes=[];if(entries.length)notes.push(`Du har oftast registrerat <strong>${esc(entries[0][0].toLocaleLowerCase('sv-SE'))}</strong>.`);if(/soppa/.test(text))notes.push('Soppa finns med bland det du registrerat.');if(/rest|överbliv|potatismos/.test(text))notes.push('Några registreringar verkar innehålla mat som kan ha använts vidare, men appen kan inte säkert veta om det var rester.');return notes.length?`<p>${notes.join(' ')}</p><p class="note">Det här är möjliga mönster i det du själv har registrerat – inte ett betyg på hur du äter.</p>`:'<p>Det finns mat registrerad, men inget tydligt mönster som appen behöver slå fast.</p>'}
  function takeaway(meals){if(!meals.length)return 'En tom återblick betyder bara att det inte finns något sparat här ännu.';const days=new Set(meals.map(mealDate).filter(Boolean)).size;if(days>=8)return 'Det finns flera små matögonblick sparade från månaden. Tillsammans ger de en bild av hur maten faktiskt fick plats i vardagen.';return 'Det som är registrerat får räcka som det är. Nästa månad behöver inte bli mer eller bättre – återblicken finns för att hjälpa dig minnas.'}
  let selectedMonth=monthKey(new Date());
  function render(){const root=ensureView(),meals=mealsFor(selectedMonth),months=availableMonths();root.innerHTML=`<button type="button" class="back" data-food-month-back>← Mat & mitt kök</button><p class="eyebrow">PLUS · Månadsläsning</p><h2>🍽️ Min matåterblick – ${esc(monthName(selectedMonth))}</h2><p class="subtitle">En återblick på det du faktiskt har registrerat. Ingen bedömning av vad eller hur du borde ha ätit.</p><section class="panel"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button type="button" class="secondary" data-food-month-prev>← Föregående</button><select id="foodMonthSelect" aria-label="Välj månad">${months.map(m=>`<option value="${m}" ${m===selectedMonth?'selected':''}>${esc(monthName(m))}</option>`).join('')}</select><button type="button" class="secondary" data-food-month-next>Nästa →</button></div></section><section class="panel"><h3>🍽️ Det här registrerade jag</h3>${overview(meals)}</section><section class="panel"><h3>🍲 Mat som fick plats i vardagen</h3>${dishes(meals)}</section><section class="panel"><h3>🌿 Det här kan jag lägga märke till</h3>${patterns(meals)}</section><section class="panel calm"><h3>💚 Det här kan jag ta med mig</h3><p>${esc(takeaway(meals))}</p></section><p class="note">Återblicken bygger bara på det du själv har registrerat i appen. Den försöker inte bedöma maten som bra eller dålig.</p>`;root.querySelector('[data-food-month-back]')?.addEventListener('click',()=>show('foodHub'));root.querySelector('[data-food-month-prev]')?.addEventListener('click',()=>{selectedMonth=changeMonth(selectedMonth,-1);render()});root.querySelector('[data-food-month-next]')?.addEventListener('click',()=>{const next=changeMonth(selectedMonth,1),now=monthKey(new Date());if(next<=now){selectedMonth=next;render()}});root.querySelector('#foodMonthSelect')?.addEventListener('change',e=>{selectedMonth=e.target.value;render()})}
  window.malixOpenFoodMonth=()=>{selectedMonth=monthKey(new Date());render();show('foodMonth')};
  document.addEventListener('click',e=>{if(e.target.closest('[data-food-month-card]'))window.malixOpenFoodMonth()},true);
})();