(()=>{
 const KEY='malix-inner-compass-v1';
 const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
 const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
 const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
 const show=id=>{document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id)?.classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})};
 function addView(id,html){let v=document.querySelector('#'+id);if(!v){v=document.createElement('section');v.id=id;v.className='view';document.querySelector('main')?.appendChild(v)}v.innerHTML=html;return v}
 function init(){const home=document.querySelector('#home'),grid=home?.querySelector('.calm-main-grid');if(!home||!grid)return setTimeout(init,250);if(!grid.querySelector('[data-calm-open="compassHub"]'))grid.insertAdjacentHTML('beforeend','<button type="button" class="choice-card" data-calm-open="compassHub"><span>🌿</span><strong>Min inre kompass</strong><small>Compassion, cirklar och reflektion.</small></button>');
  addView('compassHub',`<button type="button" class="back" data-compass-home>← Hem</button><p class="eyebrow">Compassion i vardagen</p><h2>🌿 Min inre kompass</h2><p class="subtitle">Lägg märke till var du befinner dig och vad du behöver just nu.</p><div class="choice-grid"><button type="button" class="choice-card" data-compass-open="compassAbout"><span>🌿</span><strong>Vad är compassion?</strong><small>Om att möta det som är svårt med förståelse, omtanke och mod.</small></button><button type="button" class="choice-card" data-compass-open="compassCircles"><span>🟢 🔵 🔴</span><strong>Mina tre cirklar</strong><small>Trygghet, driv och hot – och varför vi vandrar mellan dem.</small></button><button type="button" class="choice-card" data-compass-open="compassReflect"><span>💚</span><strong>Stanna upp en stund</strong><small>Var är jag just nu och vad behöver jag?</small></button></div>`);
  addView('compassAbout',`<button type="button" class="back" data-compass-back>← Min inre kompass</button><h2>🌿 Vad är compassion?</h2><p>Compassion handlar om att kunna lägga märke till att något är svårt och möta det med förståelse, omtanke och mod.</p><p>Det betyder inte att allt ska kännas bra. Det handlar om att kunna fråga: <strong>Vad händer i mig just nu? Vad behöver jag? Vad skulle vara hjälpsamt?</strong></p><section class="panel calm" style="margin-top:18px"><h3>Vill du utforska det här tillsammans med någon?</h3><p>Ibland kan det vara hjälpsamt att få stöd i att förstå känslor, mönster och vad man behöver.</p><p><a class="primary" href="https://malix.se/samtal-online/" target="_blank" rel="noopener">🌿 Läs mer om samtal online</a></p></section>`);
  addView('compassCircles',`<button type="button" class="back" data-compass-back>← Min inre kompass</button><h2>🟢 🔵 🔴 Mina tre cirklar</h2><p>Vi vandrar mellan olika känslolägen under en vanlig dag. Cirklarna är inte bra eller dåliga – de hjälper oss att lägga märke till vad som händer inom oss.</p><div class="recipe-grid"><article class="recipe-card"><h3>🟢 Grön – trygghet och ro</h3><p>Lugn, trygghet, närhet och återhämtning. Vad hjälper mig att komma hit?</p></article><article class="recipe-card"><h3>🔵 Blå – driv och utforskande</h3><p>Jag gör, lär mig, undersöker, skapar eller strävar mot något. Vad driver mig just nu?</p></article><article class="recipe-card"><h3>🔴 Röd – hot och skydd</h3><p>Stress, oro, ilska, skam eller rädsla kan aktiveras. Vad hände och vad försöker mitt system skydda mig från?</p></article></div><p class="note">Fyrkanterna 🟥 🟨 🟩 🟦 hör till Min tid och planering. Cirklarna 🟢 🔵 🔴 hör till Min inre kompass.</p>`);
  addView('compassReflect',`<button type="button" class="back" data-compass-back>← Min inre kompass</button><h2>💚 Stanna upp en stund</h2><label>Vilken cirkel befinner jag mig i just nu?<select id="compassCircle"><option value="">Välj om du vill</option><option value="green">🟢 Grön – trygghet och ro</option><option value="blue">🔵 Blå – driv och utforskande</option><option value="red">🔴 Röd – hot och skydd</option></select></label><label>Vad tror jag gjorde att jag hamnade här?<textarea id="compassWhy" rows="2"></textarea></label><label>Vad märker jag i tankar, känslor och kropp?<textarea id="compassNotice" rows="2"></textarea></label><label>Vad behöver jag just nu?<textarea id="compassNeed" rows="2"></textarea></label><label>Hur kan jag möta mig själv med lite mer förståelse?<textarea id="compassCompassion" rows="2"></textarea></label><button type="button" class="primary" id="saveCompass">Spara min reflektion</button><p class="status" id="compassStatus"></p>`);
  wire();loadToday();
 }
 function loadToday(){const x=read()[today()]||{},ids={compassCircle:'circle',compassWhy:'why',compassNotice:'notice',compassNeed:'need',compassCompassion:'compassion'};Object.entries(ids).forEach(([id,k])=>{const el=document.getElementById(id);if(el)el.value=x[k]||''})}
 function wire(){document.addEventListener('click',e=>{const open=e.target.closest('[data-compass-open]');if(open){e.preventDefault();show(open.dataset.compassOpen);if(open.dataset.compassOpen==='compassReflect')loadToday();return}if(e.target.closest('[data-compass-back]')){e.preventDefault();show('compassHub');return}if(e.target.closest('[data-compass-home]')){e.preventDefault();show('home');return}if(e.target.closest('#saveCompass')){const all=read(),d=today();all[d]={circle:document.querySelector('#compassCircle')?.value||'',why:document.querySelector('#compassWhy')?.value.trim()||'',notice:document.querySelector('#compassNotice')?.value.trim()||'',need:document.querySelector('#compassNeed')?.value.trim()||'',compassion:document.querySelector('#compassCompassion')?.value.trim()||'',savedAt:new Date().toISOString()};save(all);const s=document.querySelector('#compassStatus');if(s)s.textContent='Reflektionen är sparad ✓'}},true);document.addEventListener('malix-cloud-updated',loadToday)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();