(()=>{
 function init(){const home=document.querySelector('#home');if(!home)return setTimeout(init,200);if(home.querySelector('#lifePurpose'))return;
  const purpose=document.createElement('section');purpose.id='lifePurpose';purpose.className='panel';purpose.style.marginTop='18px';purpose.innerHTML=`<p class="eyebrow">En sak i taget</p><h2 style="margin-bottom:8px">🌿 Synliggör livet medan det pågår</h2><p style="font-size:1.08rem;line-height:1.7">Det handlar inte om att hinna mer eller göra allting rätt. Det handlar om att lägga märke till det som faktiskt händer i vardagen – det du gör, det som tar energi, det som ger återhämtning och det du behöver.</p><p style="line-height:1.7">När dagen och veckan blir synliga blir det lättare att upptäcka sådant som annars glöms bort. Med mindre självkritik kan du börja se dina egna behov, val och förmågor – och bygga större tillit till dig själv.</p><p style="margin-bottom:0"><strong>En dag i taget. En sak i taget. Ett liv som får synas medan det pågår.</strong></p>`;
  const hero=home.querySelector('.hero-card');const plan=home.querySelector('.plan-preview');(plan||hero)?.insertAdjacentElement('afterend',purpose);
  addWeekly();
 }
 function addWeekly(){const target=document.querySelector('#myTime');if(!target)return setTimeout(addWeekly,300);if(target.querySelector('#weeklyLifeReflection'))return;
  const box=document.createElement('section');box.id='weeklyLifeReflection';box.className='panel';box.innerHTML=`<p class="eyebrow">När veckan får landa</p><h3>🌿 Se det som annars lätt glöms bort</h3><p>Det här är inte en bedömning av veckan. Frågorna är en hjälp att lägga märke till dig själv och det liv du faktiskt har levt.</p><div style="display:grid;gap:10px;margin-top:14px"><p><strong>Vad klarade jag den här veckan som jag lätt glömmer bort?</strong></p><p><strong>När lyssnade jag på vad jag behövde?</strong></p><p><strong>När satte jag en gräns eller gjorde ett val som var bra för mig?</strong></p><p><strong>Vad lärde jag mig om mig själv?</strong></p><p><strong>Vad vill jag ge mig själv erkännande för?</strong></p></div><p class="muted" style="margin-bottom:0">Du behöver inte svara på allt. Ibland räcker det att stanna upp och lägga märke till en enda sak.</p>`;
  const history=target.querySelector('#history')?.closest('section.panel');const week=target.querySelector('#week')?.closest('section.panel');(history||week)?.insertAdjacentElement('afterend',box);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();