(() => {
 const KEYS={care:'malix-self-care-v1',presence:'malix-presence-reflections-v1',meals:'malix-meals',cleaning:'malix-cleaning-square-v2',compass:'malix-inner-compass-v1',time:'malix-my-time-v1',sleep:'malix-sleep-reflection-v1',direction:'malix-month-direction-v1'};
 const MONTHS=['januari','februari','mars','april','maj','juni','juli','augusti','september','oktober','november','december'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const mk=d=>{const x=new Date(d);return Number.isNaN(x.getTime())?'':`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
 const label=k=>{const [y,m]=k.split('-').map(Number);return `${MONTHS[m-1]} ${y}`};
 const current=()=>mk(new Date());
 const previous=k=>{const [y,m]=k.split('-').map(Number),d=new Date(y,m-2,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
 const mealDate=m=>window.malixMealDateKey?.(m)||(m?.date?mk(m.date):'');
 function ensure(){let s=document.querySelector('#myMonth');if(!s){s=document.createElement('section');s.id='myMonth';s.className='view';document.querySelector('main')?.appendChild(s)}return s}
 function show(){document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));ensure().classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})}
 function months(){const set=new Set([current()]);read(KEYS.care,[]).forEach(x=>x.date&&set.add(String(x.date).slice(0,7)));read(KEYS.presence,[]).forEach(x=>x.date&&set.add(String(x.date).slice(0,7)));read(KEYS.meals,[]).forEach(x=>{const d=mealDate(x);if(d)set.add(String(d).slice(0,7))});read(KEYS.sleep,[]).forEach(x=>{const d=mk(x.date);if(d)set.add(d)});const c=read(KEYS.cleaning,{});[...Object.keys(c.done||{}),...Object.keys(c.reflections||{})].forEach(d=>set.add(d.slice(0,7)));Object.keys(read(KEYS.compass,{})).forEach(d=>set.add(d.slice(0,7)));read(KEYS.time,[]).forEach(x=>x.date&&set.add(String(x.date).slice(0,7)));Object.keys(read(KEYS.direction,{})).forEach(k=>set.add(k));return [...set].filter(x=>/^\d{4}-\d{2}$/.test(x)).sort().reverse()}
 function collect(key){const care=read(KEYS.care,[]).filter(x=>String(x.date||'').slice(0,7)===key),presence=read(KEYS.presence,[]).filter(x=>String(x.date||'').slice(0,7)===key),meals=read(KEYS.meals,[]).filter(x=>String(mealDate(x)||'').slice(0,7)===key),sleep=read(KEYS.sleep,[]).filter(x=>mk(x.date)===key),clean=read(KEYS.cleaning,{}),comp=read(KEYS.compass,{}),time=read(KEYS.time,[]).filter(x=>x.type==='event'&&String(x.date||'').slice(0,7)===key);let cleaning=0;Object.entries(clean.done||{}).forEach(([d,v])=>{if(d.slice(0,7)===key)cleaning+=Object.values(v||{}).filter(Boolean).length});const compass=Object.entries(comp).filter(([d])=>d.slice(0,7)===key).flatMap(([,v])=>Array.isArray(v)?v:(v?[v]:[]));return {care,presence,meals,sleep,cleaning,compass,time}}
 function summary(d){const circles={green:0,blue:0,red:0};d.compass.forEach(x=>circles[x.circle]!==undefined&&circles[x.circle]++);const tc={red:0,yellow:0,green:0,blue:0};d.time.forEach(x=>tc[x.color]!==undefined&&tc[x.color]++);const dreams=d.sleep.filter(x=>x.dream==='Ja'||x.dream==='Lite grann').length;return `<div class="recipe-grid"><article class="summary-card"><span>🌿 Omsorg</span><strong>${d.care.length+d.presence.length}</strong><small>sparade stunder</small></article><article class="summary-card"><span>🍽️ Mat</span><strong>${d.meals.length}</strong><small>registreringar</small></article><article class="summary-card"><span>🧹 Hemmet</span><strong>${d.cleaning}</strong><small>gjorda saker</small></article><article class="summary-card"><span>🧭 Kompassen</span><strong>${d.compass.length}</strong><small>avstämningar</small></article><article class="summary-card"><span>😴 Sömn</span><strong>${d.sleep.length}</strong><small>morgonreflektioner</small></article><article class="summary-card"><span>🌙 Drömmar</span><strong>${dreams}</strong><small>morgnar med drömminne</small></article></div><p class="note">🟢 ${circles.green} · 🔵 ${circles.blue} · 🔴 ${circles.red} &nbsp; | &nbsp; Min tid: 🟥${tc.red} 🟨${tc.yellow} 🟩${tc.green} 🟦${tc.blue}</p>`}
 function sleepReflection(d){if(!d.sleep.length)return '<p class="note">När du har sparat några morgonreflektioner kan appen hjälpa dig att se hur sömnen och dina behov har sett ut över månaden.</p>';const wake={},night={},needs=[];let dreamCount=0;d.sleep.forEach(x=>{if(x.wake)wake[x.wake]=(wake[x.wake]||0)+1;if(x.night)night[x.night]=(night[x.night]||0)+1;if(x.need)needs.push(x.need);if(x.dream==='Ja'||x.dream==='Lite grann')dreamCount++});const top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1])[0];const w=top(wake),n=top(night);return `${w?`<p><strong>Vanligast när du vaknade:</strong> ${esc(w[0])} (${w[1]} morgnar)</p>`:''}${n?`<p><strong>Vanligaste upplevelsen av natten:</strong> ${esc(n[0])} (${n[1]} morgnar)</p>`:''}<p><strong>Drömminne:</strong> ${dreamCount} av ${d.sleep.length} sparade morgnar.</p>${needs.length?`<p><strong>Det du skrev att du behövde:</strong></p><ul>${needs.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p class="note">Det här beskriver bara det du själv har registrerat. Appen tolkar inte vad dina drömmar betyder.</p>`}
 function patterns(d){const out=[],texts=[...d.care.map(x=>`${x.text||''} ${x.extra||''}`),...d.presence.map(x=>`${x.feel||''} ${x.notice||''} ${x.feeling||''}`),...d.compass.map(x=>`${x.why||''} ${x.notice||''} ${x.need||''} ${x.takeaway||''}`),...d.sleep.map(x=>`${x.body||''} ${x.need||''} ${x.dreamText||''}`)].map(x=>x.toLocaleLowerCase('sv-SE'));const n=re=>texts.filter(t=>re.test(t)).length;if(n(/lugn|lugnare|ro|trygg|avslapp/)>=2)out.push('Lugn, ro eller trygghet återkommer i flera av dina egna ord.');if(n(/stress|orol|press|måste|tid|hinna/)>=2)out.push('Stress, oro, krav eller tid återkommer i flera av dina avstämningar.');if(n(/ute|luft|skog|natur|promenad|cykl/)>=2)out.push('Att komma ut eller röra dig återkommer i det du har sparat.');if(d.cleaning>=8)out.push('Många små steg i hemmet blev tillsammans en tydlig del av månaden.');if(d.presence.length>=3)out.push('Du återkom till närvaro flera gånger under månaden.');const restless=d.sleep.filter(x=>x.night==='Orolig'||x.night==='Vaknade flera gånger'||x.night==='Svårt att somna').length;if(restless>=3)out.push('Flera av dina sparade nätter innehöll oro, uppvaknanden eller svårt att somna. Det kan vara värt att vara nyfiken på hur dagarna runt omkring såg ut.');return out.length?`<ul>${out.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="note">Det här är möjliga mönster, inte slutsatser om varför något hände.</p>`:'<p class="note">Det finns ännu inget tydligt återkommande mönster som appen behöver lyfta fram. Det är också ett resultat.</p>'}
 function support(d){const kinds={};d.care.forEach(x=>{const t=String(x.type||'').replace(/^[^A-Za-zÅÄÖåäö]+\s*/,'')||'Omsorg';kinds[t]=(kinds[t]||0)+1});if(d.presence.length)kinds.Närvaro=d.presence.length;const top=Object.entries(kinds).sort((a,b)=>b[1]-a[1]).slice(0,3);if(top.length)return `<p>Det du oftast valde för dig själv var <strong>${top.map(([k,n])=>`${esc(k)} (${n})`).join(', ')}</strong>. Det säger inte vad du borde göra mer av, men det kan vara värt att känna efter vad av detta som faktiskt hjälpte.</p>`;return '<p class="note">När du har några sparade stunder kan appen hjälpa dig att se vad du oftast återvände till.</p>'}
 function previousDirection(key){const p=read(KEYS.direction,{})[previous(key)];if(!p||![p.keep,p.less,p.more,p.try].some(Boolean))return'';return `<section class="panel calm"><p class="eyebrow">Från ${esc(label(previous(key)))}</p><h3>🌱 Det här ville jag ta med mig</h3>${p.keep?`<p><strong>Ha med mig:</strong><br>${esc(p.keep)}</p>`:''}${p.less?`<p><strong>Mindre av:</strong><br>${esc(p.less)}</p>`:''}${p.more?`<p><strong>Mer av:</strong><br>${esc(p.more)}</p>`:''}${p.try?`<p><strong>Prova:</strong><br>${esc(p.try)}</p>`:''}<p class="note">När du ser tillbaka på månaden: fick något av detta plats? Du behöver inte ha lyckats med allt.</p></section>`}
 function directionForm(key){const x=read(KEYS.direction,{})[key]||{};return `<section class="panel calm"><h3>🌱 Min riktning nästa månad</h3><p>Utgå gärna från det du har sett i återblicken. Det här är en riktning, inte ett krav eller något du måste lyckas med.</p><label><strong>Det här vill jag ha med mig</strong><textarea id="monthKeep" rows="2" placeholder="Något som fungerade eller kändes viktigt …">${esc(x.keep||'')}</textarea></label><label><strong>Det här vill jag göra mindre av</strong><textarea id="monthLess" rows="2" placeholder="Något som tog mer än det gav …">${esc(x.less||'')}</textarea></label><label><strong>Det här behöver jag mer av</strong><textarea id="monthMore" rows="2" placeholder="Något jag vill ge mer plats …">${esc(x.more||'')}</textarea></label><label><strong>Något jag vill prova</strong><textarea id="monthTry" rows="2" placeholder="Ett litet försök, om jag vill …">${esc(x.try||'')}</textarea></label><button type="button" class="primary" id="saveMonthDirection">Spara min riktning</button><p id="monthDirectionStatus" class="status"></p><p class="note">Alla fält är frivilliga. Det är också okej att inte välja någon riktning just nu.</p></section>`}
 let selected=current();
 function render(){const root=ensure(),d=collect(selected),ms=months();root.innerHTML=`<button type="button" class="back" data-my-month-back>← Hem</button><p class="eyebrow">Se tillbaka</p><h2>🌿 Min månad – ${esc(label(selected))}</h2><p class="subtitle">Här möts det du har sparat i appens olika delar. Syftet är att hjälpa dig se din vardag – inte att bedöma den.</p><section class="panel"><label>Visa månad <select id="myMonthSelect">${ms.map(m=>`<option value="${m}"${m===selected?' selected':''}>${esc(label(m))}</option>`).join('')}</select></label></section>${previousDirection(selected)}<section class="panel"><h3>Den här månaden i korthet</h3>${summary(d)}</section><section class="panel calm"><h3>😴 Sömn & 🌙 drömmar</h3>${sleepReflection(d)}</section><section class="panel"><h3>🧭 Mönster jag kan vara nyfiken på</h3>${patterns(d)}</section><section class="panel calm"><h3>💚 Det här återvände jag till</h3>${support(d)}</section>${directionForm(selected)}`;root.querySelector('[data-my-month-back]').onclick=()=>{root.classList.remove('active-view');document.querySelector('#home')?.classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})};root.querySelector('#myMonthSelect').onchange=e=>{selected=e.target.value;render()};root.querySelector('#saveMonthDirection').onclick=()=>{const all=read(KEYS.direction,{});all[selected]={keep:root.querySelector('#monthKeep').value.trim(),less:root.querySelector('#monthLess').value.trim(),more:root.querySelector('#monthMore').value.trim(),try:root.querySelector('#monthTry').value.trim(),savedAt:new Date().toISOString()};save(KEYS.direction,all);root.querySelector('#monthDirectionStatus').textContent='Din riktning är sparad. Nästa månad kan du se tillbaka på den här.'}}
 function addHomeCard(){const home=document.querySelector('#home');if(!home||home.querySelector('[data-my-month]'))return;const daily=home.querySelector('[data-calm-open="dailyOverview"]')?.closest('section');const sec=document.createElement('section');sec.className='panel';sec.style.marginTop='14px';sec.dataset.myMonth='1';sec.innerHTML='<p class="eyebrow">Se tillbaka</p><h3>🌿 Min månad</h3><p class="note">Se vad de små delarna av vardagen blev tillsammans och vilka mönster som kan vara värda att vara nyfiken på.</p><button type="button" class="secondary" data-open-my-month>Se min månad →</button>';daily?.after(sec)||home.appendChild(sec);sec.querySelector('[data-open-my-month]').onclick=()=>{selected=current();render();show()}}
 addHomeCard();setTimeout(addHomeCard,100);window.malixOpenMyMonth=()=>{selected=current();render();show()};
})();