(() => {
  const groups={
    protein:{title:'🥩 Det här gav protein',words:['fisk','lax','torsk','kyckling','kött','köttfärs','ägg','ost','kvarg','yoghurt','filmjölk','mjölk','bön','linser','kikärt','tofu','makrill','leverpastej']},
    fiber:{title:'🥬 Det här gav fiber',words:['havre','müsli','fullkorn','knäckebröd','bön','linser','kikärt','morot','kål','broccoli','ärtor','majs','paprika','frukt','äpple','päron','banan','bär','potatis','grönsak']},
    produce:{title:'🥦 Frukt & grönt du loggat',words:['morot','kål','broccoli','ärtor','majs','paprika','tomat','gurka','sallad','spenat','lök','rödlök','vitlök','purjolök','avokado','zucchini','aubergine','svamp','blomkål','selleri','äpple','päron','banan','bär','frukt','citron','rödbet','palsternack','potatis']},
    plants:{title:'🌈 Växter i dagens variation',words:['morot','vitkål','kål','broccoli','ärtor','majs','paprika','tomat','gurka','sallad','spenat','lök','rödlök','vitlök','purjolök','avokado','zucchini','aubergine','svamp','blomkål','selleri','äpple','päron','banan','bär','citron','rödbeta','palsternacka','potatis','ris','havre','bönor','linser','kikärtor','dill','rosmarin','timjan','chili']}
  };
  const micro={mjölk:['kalcium','B12'],filmjölk:['kalcium','B12'],yoghurt:['kalcium','B12'],kvarg:['kalcium','B12'],ost:['kalcium','B12'],ägg:['D-vitamin','B12','selen'],makrill:['D-vitamin','B12','omega-3'],fisk:['D-vitamin','B12','selen'],lax:['D-vitamin','B12','omega-3'],kött:['järn','B12','zink'],köttfärs:['järn','B12','zink'],leverpastej:['järn','A-vitamin','B12'],havregryn:['järn','magnesium','B1'],müsli:['järn','magnesium','B1'],bönor:['folat','järn','magnesium'],linser:['folat','järn','magnesium'],potatis:['C-vitamin','kalium','B6'],banan:['kalium','B6'],bär:['C-vitamin','folat'],paprika:['C-vitamin','folat'],broccoli:['C-vitamin','folat'],spenat:['folat','järn']};
  function meals(){const key=window.malixOverviewKey?.();try{return JSON.parse(localStorage.getItem('malix-meals')||'[]').filter(m=>(window.malixMealDateKey?.(m)||'')===key)}catch{return[]}}
  function foods(){return meals().flatMap(m=>String(m.food||'').split(/,\s*/)).map(x=>x.replace(/\s*\(.*?\)\s*$/,'').trim()).filter(Boolean)}
  function unique(a){return [...new Set(a)]}
  function sources(type){const fs=foods();if(type==='vitamins')return fs.map(food=>{const f=food.toLowerCase();const k=Object.keys(micro).find(k=>f.includes(k));return k?`${food} → ${micro[k].join(', ')}`:null}).filter(Boolean);const g=groups[type];return unique(fs.filter(food=>g.words.some(w=>food.toLowerCase().includes(w))))}
  function ensureBox(){let box=document.querySelector('#nutritionDetailBox');if(box)return box;const dash=document.querySelector('.dashboard-panel');if(!dash)return null;box=document.createElement('div');box.id='nutritionDetailBox';box.className='note';box.hidden=true;dash.appendChild(box);return box}
  function showDetail(type){const box=ensureBox();if(!box)return;const list=sources(type);const title=type==='vitamins'?'💊 Varifrån vitaminerna & mineralerna kommer':groups[type].title;box.hidden=false;box.innerHTML=`<strong>${title}</strong>${list.length?`<ul>${list.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>Jag hittar ännu ingen tydlig källa i det som är loggat.</p>'}<small>Översikten bygger på det du själv har loggat och är till för att visa var näringen kommer ifrån, inte för att sätta betyg på måltiden.</small>`;box.scrollIntoView({behavior:'smooth',block:'nearest'});}
  function wire(){const map={proteinSummary:'protein',fiberSummary:'fiber',produceSummary:'produce',plantSummary:'plants',vitaminSummary:'vitamins'};Object.entries(map).forEach(([id,type])=>{const strong=document.querySelector('#'+id);const card=strong?.closest('.summary-card');if(!card||card.dataset.explainable)return;card.dataset.explainable='true';card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Visa vad som bidrog till ${type}`);const hint=document.createElement('small');hint.className='nutrition-more';hint.textContent='Se vad som bidrog ›';card.appendChild(hint);card.addEventListener('click',()=>showDetail(type));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showDetail(type)}});});}
  document.addEventListener('malix-day-changed',()=>setTimeout(wire,0));wire();
  if(!document.querySelector('script[data-water-tracker]')){const s=document.createElement('script');s.src='water-tracker.js';s.dataset.waterTracker='1';document.body.appendChild(s)}
})();