(() => {
 const exercises=[
  ['👣','Känn steget','Gå långsamt några steg. Lägg märke till hur foten möter golvet. Känn hälen, fotsulan och tårna. Du behöver inte förändra något – bara lägg märke till.'],
  ['🫶','Känn kroppen','Stanna upp. Hur känns kroppen just nu? Lägg märke till om någon del känns varm, kall, tung, lätt eller avslappnad. Du behöver inte ändra känslan.'],
  ['🌬️','Tre andetag','Lägg märke till tre vanliga andetag. Du behöver inte andas på något särskilt sätt. Följ bara andetaget in och ut.'],
  ['👂','Vad hör du?','Stanna en stund och lägg märke till tre ljud. Ett nära, ett längre bort och kanske ett du inte lade märke till först.'],
  ['🌳','Ute en minut','Känn temperaturen och luften mot huden. Titta på något omkring dig. Du behöver inte göra något mer just nu.'],
  ['☕','Här är jag','Om du har en kopp kaffe, te eller något annat: känn koppen i handen, lägg märke till doften och smaken av nästa klunk.']
 ];
 function init(){const hub=document.querySelector('#careHub');if(!hub||hub.querySelector('[data-care="carePresence"]'))return;const grid=hub.querySelector('.choice-grid');if(!grid)return;const btn=document.createElement('button');btn.className='choice-card';btn.dataset.care='carePresence';btn.innerHTML='<span>🌱</span><strong>Närvaro</strong><small>Korta övningar mitt i vardagen. Ingen prestation.</small>';grid.insertBefore(btn,grid.lastElementChild);let s=document.querySelector('#carePresence');if(!s){s=document.createElement('section');s.id='carePresence';s.className='view';document.querySelector('main').appendChild(s)}s.innerHTML=`<button class="back" type="button" data-presence-back>← Ta hand om mig</button><p class="eyebrow">En sak i taget</p><h2>🌱 Närvaro</h2><p class="subtitle">Du behöver inte kunna meditera. Välj en mycket liten övning och lägg bara märke till det som redan finns.</p><div class="choice-grid">${exercises.map((x,i)=>`<button class="choice-card" type="button" data-presence="${i}"><span>${x[0]}</span><strong>${x[1]}</strong><small>En kort stund</small></button>`).join('')}</div><section id="presenceExercise" class="panel calm" style="margin-top:20px"><h3>🌿 Välj en övning</h3><p>Det räcker med en liten stund.</p></section>`;grid.addEventListener('click',e=>{const b=e.target.closest('[data-care="carePresence"]');if(!b)return;e.preventDefault();document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));s.classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})});s.querySelector('[data-presence-back]').onclick=()=>window.malixOpenCare?.();s.querySelectorAll('[data-presence]').forEach(b=>b.onclick=()=>{const x=exercises[+b.dataset.presence],box=s.querySelector('#presenceExercise');box.innerHTML=`<p class="eyebrow">${x[0]} En liten stund</p><h3>${x[1]}</h3><p>${x[2]}</p><hr><p><strong>Hur känns det nu?</strong></p><div class="chips"><button type="button" data-feel>Annorlunda</button><button type="button" data-feel>Ungefär samma</button><button type="button" data-feel>Vet inte</button></div><p class="note">Det finns inget rätt svar. Övningen handlade bara om att vara här en liten stund.</p>`})}
 setTimeout(init,100);document.addEventListener('click',e=>{if(e.target.closest('[data-calm-open="careHub"]'))setTimeout(init,50)},true)
})();