// En enda fysisk källa för receptdatan i En sak i taget.
// Recepten ligger här innan de senare skrivs om enligt den gemensamma receptstandarden.

const recipes=[
{id:'fiskpanetter',name:'Fiskpanetter med kalasris och filmjölkssås',emoji:'🐟',time:30,budget:'low',tags:['fisk','familj'],ingredients:['fiskpanetter','ris','ärtor','majs','paprika','filmjölk','majonnäs','bostongurka','dill','citron'],leftovers:['ris'],plants:5,tip:'Kalasris är vanligt ris som får färg och smak av ärtor, majs och paprika.',steps:['Tillaga fiskpanetterna enligt förpackningen.','Koka ris och blanda med ärtor, majs och paprika till kalasris.','Rör ihop filmjölk med lite majonnäs, bostongurka, dill och citron.','Servera allt som en hel måltid.']},
{id:'stroganoff',name:'Korvstroganoff à la Malix',emoji:'🍲',time:30,budget:'low',tags:['familj','gryta'],ingredients:['korv','lök','tomatpuré','dijonsenap','chili','buljong','grädde eller valfri bas','ris'],leftovers:['ris'],plants:3,tip:'Dijonsenap, tomatpuré och lite chili ger mer djup i smaken.',steps:['Skär korv och lök och bryn i en gryta.','Rör ner tomatpuré, dijonsenap och lite chili.','Tillsätt buljong och gräddig bas och låt puttra.','Servera med ris och gärna grönsaker.']},
{id:'kycklingmalix',name:'Krispig kyckling à la Malix med jordnötssås',emoji:'🍗',time:40,budget:'mid',tags:['kyckling','familj'],ingredients:['kyckling','majsstärkelse','ägg','eventuellt ströbröd','olja','jordnötssås','ris','ärtor','majs','paprika','wokgrönsaker'],leftovers:['ris'],plants:5,tip:'Kalasris eller vanligt ris fungerar. Wokgrönsaker vid sidan gör det till en hel måltid.',steps:['Förbered kycklingen i små bitar. Om du använder bikarbonat/bakpulver som mörningsmetod, skölj bort det före panering.','Vänd bitarna i majsstärkelse och därefter ägg; ströbröd är valfritt.','Tillaga kycklingen helt igenom i olja och hantera het olja försiktigt.','Servera med jordnötssås, ris och wokgrönsaker.']},
{id:'rotfrukter',name:'Rostade rotfrukter à la Malix',emoji:'🥕',time:45,budget:'low',tags:['vegetariskt','tillbehör','ta-vad-du-har'],ingredients:['valfria rotfrukter','gärna rödbetor','olivolja','rosmarin eller timjan','chili','vitlök','fetaost','salt','peppar'],leftovers:['fetaost','rotfrukter'],plants:5,tip:'Lägg rotfrukterna i en påse med olivolja och kryddor, skaka och häll ut på plåten. Perfekt när fetaosten behöver gå åt.',steps:['Skär de rotfrukter du har. Råa eller förkokta rödbetor kan användas.','Blanda i en påse med olivolja, örter, chili, vitlök, salt och peppar.','Häll ut på plåt och rosta tills rotfrukterna är mjuka och har fått färg.','Smula över fetaost mot slutet eller vid servering.']},
{id:'tzatziki',name:'Tzatziki à la Malix',emoji:'🥒',time:15,budget:'low',tags:['vegetariskt','tillbehör'],ingredients:['1 kg turkisk yoghurt','1 gurka','7 vitlöksklyftor','olivolja','salt','peppar','eventuellt citron'],leftovers:['gurka','yoghurt'],plants:3,tip:'Ringla gärna lite finare olivolja över vid servering. Citron är valfritt.',steps:['Riv gurkan och pressa ur en del vätska.','Blanda med turkisk yoghurt och pressad vitlök.','Smaka av med olivolja, salt, peppar och eventuellt citron.']},
{id:'fetaostkram',name:'Fetaostkräm à la Malix',emoji:'🧄',time:10,budget:'low',tags:['vegetariskt','tillbehör'],ingredients:['turkisk yoghurt','fetaost','rikligt med vitlök'],leftovers:['fetaost','yoghurt'],plants:1,tip:'Mängderna kan anpassas efter hur krämig och vitlökig du vill ha den.',steps:['Mosa fetaosten.','Blanda med turkisk yoghurt.','Pressa i rikligt med vitlök och smaka av.']},
{id:'chili',name:'Chili con carne – långkok med nötkött',emoji:'🌶️',time:180,budget:'mid',tags:['gryta','slowcooker'],ingredients:['nötkött i bitar','lök','vitlök','chili','tomat','bönor','kryddor','vitt bröd','grönsallad'],leftovers:[],plants:5,tip:'Malix tips: har du bara ätit köttfärsvarianten, prova någon gång med nötkött i bitar. Anpassa chilin efter din smak.',steps:['Bryn köttet och lägg i gryta.','Tillsätt lök, vitlök, chili, tomat, bönor och kryddor.','Låt gå långsamt tills köttet är mört.','Servera med färskt vitt bröd och en enkel grönsallad.']},
{id:'chilibillig',name:'Chili con carne – billigare köttfärsvariant',emoji:'🌶️',time:40,budget:'low',tags:['köttfärs','gryta','familj'],ingredients:['köttfärs','lök','vitlök','chili','tomat','bönor'],leftovers:[],plants:4,tip:'En vardagsvariant när du vill ha chili con carne snabbare och billigare.',steps:['Bryn köttfärs och lök.','Tillsätt vitlök, chili, tomat och bönor.','Låt puttra och smaka av.']},
{id:'kalops',name:'Klassisk kalops',emoji:'🥘',time:150,budget:'mid',tags:['gryta','slowcooker','familj'],ingredients:['nötkött','gul lök','morot','lagerblad','kryddpeppar','buljong','potatis'],leftovers:[],plants:4,tip:'Kan göras på spisen eller i slowcooker. Aktiv tid är betydligt kortare än totaltiden.',steps:['Bryn köttet och löken.','Tillsätt morot, lagerblad, kryddpeppar och buljong.','Låt sjuda långsamt tills köttet är mört.','Servera med kokt potatis.']},
{id:'pulledpork',name:'Pulled pork med cola – slowcooker',emoji:'🍖',time:480,budget:'mid',tags:['slowcooker','familj'],ingredients:['fläskkött för långkok','lök','vitlök','cola','kryddor','tomat- eller BBQ-smaksättning'],leftovers:[],plants:2,tip:'Lite aktiv tid, lång total tid. Förbered när du har ork och låt maten sköta sig.',steps:['Lägg ingredienserna i slowcookern.','Tillaga länge tills köttet är genomlagat och mycket mört.','Dra isär köttet och blanda med såsen.']},
{id:'risgryn',name:'Risgrynsgröt i slowcooker',emoji:'🥣',time:180,budget:'low',tags:['slowcooker','vegetariskt'],ingredients:['grötris','mjölk','vatten','salt'],leftovers:[],plants:1,tip:'Malix tips: rör i gröten och stäng av innan den känns helt färdigtjock – den fortsätter att tjockna.',steps:['Blanda ingredienserna i slowcookern.','Tillaga på låg värme och rör om då och då, särskilt mot slutet.','Stäng av innan gröten blivit för tjock.']},
{id:'kottbullar',name:'Köttbullar med potatis och sås',emoji:'🥔',time:45,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','lök','ägg','ströbröd','mjölk','potatis','sås','grönsaker'],leftovers:[],plants:3,tip:'Gör gärna många och frys in – då finns en enkel middag en annan dag.',steps:['Blanda köttfärssmet och forma köttbullar.','Stek eller ugnstillaga tills de är genomlagade.','Servera med potatis, sås och grönsaker.']},
{id:'pannbiff',name:'Pannbiff med lök',emoji:'🥩',time:45,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','lök','ägg','ströbröd','mjölk','potatis','sås'],leftovers:[],plants:2,tip:'Stekt lök ovanpå gör mycket för den klassiska smaken.',steps:['Blanda färsen och forma biffar.','Stek biffarna helt igenom.','Stek löken mjuk och servera med potatis och sås.']},
{id:'kottgrotta',name:'Köttgrotta à la Malix med flødeost och bacon',emoji:'🥩',time:60,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärssmet','pikant- eller vitlöksfärskost/flødeost','bacon','valfria tillbehör'],leftovers:[],plants:1,tip:'Välj pikant flødeost för kryddigare smak eller vitlöksvariant om du gillar vitlök.',steps:['Forma köttfärssmeten med en fördjupning/fyllning av flødeost i mitten.','Forma ihop och lägg bacon runt om.','Ugnstillaga tills köttet är helt genomlagat.','Servera med exempelvis potatis, rostade rotfrukter och sallad.']},
{id:'macka',name:'Smörgåsmåltid med pålägg, frukt eller grönt',emoji:'🥪',time:5,budget:'low',tags:['snabbt','familj'],ingredients:['bröd','pålägg','frukt eller grönt'],leftovers:[],plants:2,tip:'En måltid behöver inte vara komplicerad.',steps:['Ta fram bröd och pålägg.','Lägg till frukt eller grönsaker om du har.']},
{id:'fil',name:'Fil eller yoghurt med müsli och frukt',emoji:'🥣',time:3,budget:'low',tags:['snabbt','vegetariskt'],ingredients:['fil eller yoghurt','müsli','frukt eller bär'],leftovers:[],plants:2,tip:'Passar när orken är låg.',steps:['Häll upp fil eller yoghurt.','Lägg på müsli och frukt eller bär.']},
{id:'potatisbullar',name:'Potatisbullar av överblivet potatismos',emoji:'🥔',time:20,budget:'low',tags:['vegetariskt','familj'],ingredients:['potatismos','ägg','mjöl','valfria tillbehör'],leftovers:['potatismos'],plants:1,tip:'Ett enkelt sätt att ge potatismoset ett nytt liv.',steps:['Blanda kallt mos med ägg och lite mjöl till en formbar smet.','Forma och stek tills de fått fin yta.','Servera med det du tycker om.']},
{id:'potatissoppa',name:'Potatissoppa av överblivet potatismos',emoji:'🥣',time:15,budget:'low',tags:['snabbt','vegetariskt'],ingredients:['potatismos','buljong','lök','mjölk eller annan bas'],leftovers:['potatismos'],plants:2,tip:'Späd moset till soppa och smaka dig fram.',steps:['Fräs lök om du vill.','Rör ut moset med buljong och valfri mjölkbas.','Värm och smaka av.']}
];

recipes.push(
{id:'lasagne',name:'Klassisk lasagne',emoji:'🍝',time:70,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','gul lök','vitlök','krossade tomater','tomatpuré','lasagneplattor','mjölk','mjöl','smör','ost'],leftovers:['köttfärssås'],tip:'Gör dubbel sats köttfärssås och frys hälften.',steps:['Koka en fyllig köttfärssås.','Gör en enkel vit sås.','Varva såser och plattor.','Toppa med ost och gratinera tills lasagnen är genomvarm och fått färg.']},
{id:'kålpanna',name:'Kålpanna med köttfärs',emoji:'🥬',time:35,budget:'low',tags:['köttfärs','gryta','budget','familj'],ingredients:['vitkål','gul lök','köttfärs','buljong','grädde eller matlagningsbas','salt','peppar'],leftovers:['vitkål'],tip:'Rivna morötter passar fint till och gör tallriken mer färgrik.',steps:['Strimla kål och lök och stek mjuka.','Bryn köttfärsen.','Tillsätt buljong och gräddig bas.','Låt puttra ihop och servera med potatis eller som den är.']},
{id:'kålpudding',name:'Kålpudding med potatis och lingon',emoji:'🥬',time:70,budget:'low',tags:['köttfärs','familj','budget'],ingredients:['vitkål','köttfärs','gul lök','ägg','mjölk','ströbröd','sirap valfritt','potatis','lingon'],leftovers:['vitkål'],tip:'Stek kålen ordentligt så den blir mjuk och smakrik.',steps:['Stek strimlad kål mjuk.','Blanda köttfärssmet.','Varva kål och färs i form.','Ugnsbaka tills färsen är genomlagad och servera med potatis och lingon.']},
{id:'kycklinggryta-curry',name:'Krämig kycklinggryta med curry',emoji:'🍗',time:35,budget:'mid',tags:['kyckling','gryta','familj'],ingredients:['kyckling','gul lök','paprika','curry','buljong','grädde eller kokosmjölk','ris'],leftovers:['kyckling','paprika'],tip:'Ärtor eller broccoli kan åka ner på slutet.',steps:['Bryn kyckling och lök.','Tillsätt paprika och curry.','Häll på buljong och gräddig bas.','Låt sjuda tills kycklingen är genomlagad och servera med ris.']},
{id:'fiskgratäng',name:'Fiskgratäng med potatismos',emoji:'🐟',time:50,budget:'mid',tags:['fisk','familj'],ingredients:['vit fisk','potatismos','dill','citron','grädde eller mjölk','buljong','ärtor'],leftovers:['potatismos'],tip:'Har du mos över är det här en enkel restmiddag.',steps:['Lägg fisken i form.','Gör en enkel dillsås.','Spritsa eller bred mos runt fisken.','Baka tills fisken är klar och servera med ärtor.']},
{id:'ugnslax-dill',name:'Ugnslax med potatis, ärtor och dillsås',emoji:'🐟',time:35,budget:'mid',tags:['fisk','familj'],ingredients:['lax','potatis','ärtor','yoghurt eller crème fraîche','dill','citron'],leftovers:[],tip:'Citron och dill räcker långt – håll resten enkelt.',steps:['Koka potatis.','Baka lax i ugn tills den är klar.','Rör ihop kall dillsås.','Servera med ärtor och citron.']},
{id:'torsk-tomat',name:'Torsk i tomat med vitlök och örter',emoji:'🐟',time:30,budget:'mid',tags:['fisk'],ingredients:['torsk eller annan vit fisk','krossade tomater','vitlök','gul lök','örter','potatis eller ris'],leftovers:['tomatsås'],tip:'Kapris eller oliver passar om du har hemma.',steps:['Fräs lök och vitlök.','Tillsätt tomater och örter.','Lägg i fisken och låt sjuda försiktigt tills den är klar.','Servera med potatis eller ris.']},
{id:'fisk-soppa',name:'Enkel fisksoppa',emoji:'🥣',time:35,budget:'mid',tags:['fisk','soppa','gryta'],ingredients:['vit fisk','lax valfritt','potatis','morot','purjolök','buljong','grädde','dill'],leftovers:['fisk','potatis'],tip:'En klick crème fraîche eller tzatziki kan passa oväntat bra till soppa.',steps:['Koka potatis och morot i buljong.','Tillsätt purjolök och grädde.','Lägg i fisken sist och sjud varsamt.','Smaka av med dill.']},
{id:'tomatsoppa',name:'Tomatsoppa med basilika',emoji:'🥣',time:25,budget:'low',tags:['soppa','vegetariskt','budget'],ingredients:['krossade tomater','gul lök','vitlök','buljong','basilika','grädde valfritt'],leftovers:['tomater'],tip:'Servera med bröd eller en varm ostsmörgås.',steps:['Fräs lök och vitlök.','Häll på tomater och buljong.','Koka 15 minuter och mixa.','Smaka av med basilika och eventuell grädde.']},
{id:'broccolisoppa',name:'Broccolisoppa',emoji:'🥣',time:25,budget:'low',tags:['soppa','vegetariskt','budget'],ingredients:['broccoli','potatis','gul lök','buljong','mjölk eller grädde'],leftovers:['broccoli','potatis'],tip:'Lite ost på toppen gör soppan fylligare.',steps:['Koka broccoli, potatis och lök mjuka i buljong.','Mixa.','Tillsätt mjölk eller grädde och värm.','Smaka av.']},
{id:'morotssoppa',name:'Morotssoppa med ingefära',emoji:'🥣',time:30,budget:'low',tags:['soppa','vegetariskt','budget'],ingredients:['morötter','gul lök','ingefära','buljong','kokosmjölk eller grädde'],leftovers:['morötter'],tip:'Citron eller lime piggar upp smaken.',steps:['Fräs lök och ingefära.','Tillsätt morötter och buljong.','Koka mjukt och mixa.','Rör i kokosmjölk eller grädde.']},
{id:'blomkålssoppa',name:'Blomkålssoppa',emoji:'🥣',time:25,budget:'low',tags:['soppa','vegetariskt','budget'],ingredients:['blomkål','potatis','gul lök','buljong','mjölk eller grädde'],leftovers:['blomkål'],tip:'Toppa med rostade frön eller en klick yoghurt om du vill.',steps:['Koka blomkål, potatis och lök i buljong.','Mixa slät.','Späd till lagom konsistens.','Smaka av.']},
{id:'linssoppa',name:'Röd linssoppa',emoji:'🥣',time:30,budget:'low',tags:['soppa','vegetariskt','budget'],ingredients:['röda linser','morot','gul lök','vitlök','krossade tomater','buljong','spiskummin'],leftovers:['morötter'],tip:'Billig, mättande och bra att frysa.',steps:['Fräs lök och vitlök.','Tillsätt morot, linser, tomat och buljong.','Koka tills linserna är mjuka.','Smaka av med spiskummin.']},
{id:'gulaschsoppa',name:'Gulaschsoppa',emoji:'🥣',time:60,budget:'mid',tags:['soppa','gryta'],ingredients:['nötkött eller köttfärs','potatis','paprika','gul lök','vitlök','tomat','paprikapulver','buljong'],leftovers:['potatis','paprika'],tip:'Servera gärna med bröd och en klick gräddfil.',steps:['Bryn kött och lök.','Tillsätt paprika, kryddor och tomat.','Häll på buljong och lägg i potatis.','Koka tills allt är mört.']},
{id:'köttfärssås',name:'Köttfärssås med morot och tomat',emoji:'🍝',time:40,budget:'low',tags:['köttfärs','familj','budget'],ingredients:['köttfärs','gul lök','vitlök','morot','krossade tomater','tomatpuré','pasta'],leftovers:['morötter'],tip:'Riven morot försvinner nästan in i såsen och ger både smak och mer grönt.',steps:['Bryn köttfärs och lök.','Tillsätt vitlök och riven morot.','Rör i tomatpuré och tomater.','Låt puttra och servera med pasta.']},
{id:'makaronipudding',name:'Makaronipudding',emoji:'🍝',time:50,budget:'low',tags:['familj','budget'],ingredients:['kokta makaroner','korv eller skinka','ägg','mjölk','ost'],leftovers:['pasta','korv'],tip:'Bra när kokta makaroner behöver gå åt.',steps:['Lägg makaroner och korv i form.','Vispa ihop ägg och mjölk.','Häll över och toppa med ost.','Gratinera tills stanningen satt sig.']},
{id:'pyttipanna',name:'Pytt i panna av rester',emoji:'🍳',time:25,budget:'low',tags:['budget','ta-vad-du-har'],ingredients:['kokt potatis','kött eller korv','gul lök','ägg','rödbetor'],leftovers:['potatis','kött','korv'],tip:'Pytt är nästan byggd för rester – ta vad du har.',steps:['Tärna potatis och rester.','Stek med lök tills allt fått färg.','Stek ägg vid sidan.','Servera med rödbetor.']},
{id:'stekt-ris',name:'Stekt ris med ägg och grönsaker',emoji:'🍚',time:20,budget:'low',tags:['snabbt','budget','ta-vad-du-har'],ingredients:['kallt kokt ris','ägg','ärtor','majs','paprika','soja','valfria rester'],leftovers:['ris'],tip:'Kallt ris från dagen innan fungerar bäst.',steps:['Stek grönsaker och eventuella rester.','Tillsätt ris och hetta upp ordentligt.','Skjut åt sidan och stek ägg.','Blanda och smaka av med soja.']},
{id:'ris-sallad',name:'Rissallad med det du har',emoji:'🥗',time:15,budget:'low',tags:['snabbt','budget','ta-vad-du-har'],ingredients:['kokt kallt ris','majs','ärtor','paprika','gurka','valfritt protein','dressing'],leftovers:['ris'],tip:'Kalasris kan bli grunden till en kall lunch dagen efter.',steps:['Kyl riset ordentligt.','Blanda med grönsaker och valfritt protein.','Rör ihop en enkel dressing.','Servera kall.']},
{id:'omelett-rest',name:'Omelett med rester',emoji:'🍳',time:15,budget:'low',tags:['snabbt','budget','ta-vad-du-har'],ingredients:['ägg','en skvätt mjölk','ost','grönsaker eller andra rester'],leftovers:['grönsaker','ost'],tip:'Små mängder grönsaker, ost eller potatis passar perfekt här.',steps:['Vispa ägg och mjölk.','Lägg rester i pannan.','Häll över äggen.','Tillaga tills omeletten stannat.']},
{id:'pasta-feta',name:'Pasta med fetaost, tomat och spenat',emoji:'🍝',time:25,budget:'mid',tags:['vegetariskt'],ingredients:['pasta','fetaost','tomater','spenat','vitlök','olivolja'],leftovers:['fetaost','tomater'],tip:'Bra när fetaosten behöver användas.',steps:['Koka pasta.','Fräs vitlök, tomat och spenat.','Vänd ner pastan.','Smula över fetaost.']},
{id:'pasta-tonfisk',name:'Tonfiskpasta med citron',emoji:'🍝',time:20,budget:'low',tags:['fisk','snabbt','budget'],ingredients:['pasta','tonfisk','citron','vitlök','crème fraîche eller yoghurt','ärtor'],leftovers:['pasta'],tip:'En burk tonfisk kan räcka långt i en vardagspasta.',steps:['Koka pasta och ärtor.','Rör ihop tonfisk med citron och krämig bas.','Vänd ner pastan.','Smaka av med peppar.']},
{id:'kycklingwok',name:'Kycklingwok med grönsaker',emoji:'🍗',time:25,budget:'mid',tags:['kyckling','snabbt'],ingredients:['kyckling','wokgrönsaker','soja','vitlök','ingefära','ris eller nudlar'],leftovers:['kyckling','grönsaker'],tip:'Frysta wokgrönsaker gör den extra enkel.',steps:['Stek kycklingen genomlagad.','Tillsätt grönsaker, vitlök och ingefära.','Smaka av med soja.','Servera med ris eller nudlar.']},
{id:'kyckling-ugn',name:'Ugnskyckling med rotfrukter',emoji:'🍗',time:55,budget:'mid',tags:['kyckling','familj'],ingredients:['kycklingdelar','potatis','morötter','lök','olja','rosmarin','vitlök'],leftovers:['rotfrukter'],tip:'Allt på samma plåt betyder mindre disk.',steps:['Skär rotfrukter och lök.','Blanda med olja och kryddor.','Lägg kycklingen ovanpå.','Ugnsbaka tills kycklingen är genomlagad och rotfrukterna mjuka.']},
{id:'kyckling-pasta',name:'Krämig kycklingpasta',emoji:'🍝',time:30,budget:'mid',tags:['kyckling','familj'],ingredients:['kyckling','pasta','gul lök','vitlök','grädde','spenat','parmesan eller annan ost'],leftovers:['kyckling'],tip:'Spenat kan bytas mot broccoli eller ärtor.',steps:['Koka pasta.','Bryn kyckling och lök.','Tillsätt vitlök, grädde och grönt.','Vänd ner pasta och ost.']},
{id:'kebab-ris',name:'Kebab med ris, sallad och sås',emoji:'🥙',time:25,budget:'mid',tags:['familj'],ingredients:['kebabkött eller kycklingkebab','ris','sallad','tomat','gurka','lök','kebabsås'],leftovers:['ris'],tip:'Kalasris fungerar också fint här.',steps:['Koka ris.','Tillaga kebaben.','Hacka sallad och grönsaker.','Servera med sås.']},
{id:'kebabgryta',name:'Krämig kebabgryta',emoji:'🥘',time:30,budget:'mid',tags:['gryta','familj'],ingredients:['kebabkött','gul lök','paprika','tomatpuré','grädde','buljong','ris'],leftovers:['kebab','paprika'],tip:'Lite chili passar om du vill ha mer hetta.',steps:['Stek kebab och lök.','Tillsätt paprika och tomatpuré.','Häll på grädde och buljong.','Låt puttra och servera med ris.']},
{id:'biffstroganoff',name:'Biff Stroganoff',emoji:'🥘',time:40,budget:'mid',tags:['gryta'],ingredients:['strimlat nötkött','gul lök','champinjoner','tomatpuré','dijonsenap','grädde','ris'],leftovers:['champinjoner'],tip:'Stek köttet snabbt och låt det inte koka för länge om det är mört från början.',steps:['Bryn köttet hastigt och ta upp.','Stek lök och svamp.','Tillsätt tomatpuré, senap och grädde.','Lägg tillbaka köttet och servera med ris.']},
{id:'köttgryta-rot',name:'Köttgryta med rotfrukter',emoji:'🥘',time:150,budget:'mid',tags:['gryta','slowcooker'],ingredients:['grytbitar av nöt','morot','palsternacka','gul lök','buljong','tomatpuré','timjan'],leftovers:['rotfrukter'],tip:'Passar utmärkt i slowcooker.',steps:['Bryn köttet om du vill.','Lägg allt i gryta eller slowcooker.','Låt gå tills köttet är riktigt mört.','Smaka av och servera med potatis eller bröd.']},
{id:'veg-chili',name:'Vegetarisk chili med bönor',emoji:'🌶️',time:35,budget:'low',tags:['vegetariskt','gryta','budget'],ingredients:['kidneybönor','svarta bönor','gul lök','vitlök','paprika','tomat','majs','chili','spiskummin'],leftovers:['bönor','majs','paprika'],tip:'Gör gärna mycket – den är bra i matlåda och frys.',steps:['Fräs lök, vitlök och paprika.','Tillsätt tomat, bönor, majs och kryddor.','Låt puttra.','Servera med ris eller bröd.']},
{id:'kikärtsgryta',name:'Kikärtsgryta med kokosmjölk',emoji:'🥘',time:30,budget:'low',tags:['vegetariskt','gryta','budget'],ingredients:['kikärtor','gul lök','vitlök','tomat','kokosmjölk','curry','spenat','ris'],leftovers:['kikärtor'],tip:'Bra basgryta som tål många olika grönsaker.',steps:['Fräs lök, vitlök och curry.','Tillsätt kikärtor, tomat och kokosmjölk.','Låt puttra och rör ner spenat.','Servera med ris.']},
{id:'linsbolognese',name:'Linsbolognese',emoji:'🍝',time:35,budget:'low',tags:['vegetariskt','budget'],ingredients:['gröna eller röda linser','gul lök','morot','vitlök','krossade tomater','tomatpuré','pasta'],leftovers:['morötter'],tip:'Ett billigt alternativ till köttfärssås.',steps:['Fräs lök, morot och vitlök.','Tillsätt tomatpuré, tomater och linser.','Koka tills linserna är mjuka.','Servera med pasta.']},
{id:'halloumi-plåt',name:'Halloumi med ugnsgrönsaker',emoji:'🥕',time:40,budget:'mid',tags:['vegetariskt'],ingredients:['halloumi','potatis','paprika','zucchini','rödlök','olja','örter'],leftovers:['grönsaker'],tip:'Fetaostkräm eller tzatziki passar bra till.',steps:['Skär grönsaker och rosta i ugn.','Lägg på halloumi mot slutet.','Tillaga tills allt fått färg.','Servera med kall sås.']},
{id:'potatisgratäng',name:'Potatisgratäng',emoji:'🥔',time:70,budget:'low',tags:['vegetariskt','tillbehör','budget'],ingredients:['potatis','grädde','mjölk','vitlök','salt','peppar','ost valfritt'],leftovers:['potatis'],tip:'Kan göras dagen före och värmas.',steps:['Skiva potatis tunt.','Varva med vitlök och kryddor.','Häll över grädde och mjölk.','Gratinera tills potatisen är mjuk.']},
{id:'potatisomelett',name:'Potatisomelett av kokt potatis',emoji:'🍳',time:20,budget:'low',tags:['vegetariskt','budget','ta-vad-du-har'],ingredients:['kokt potatis','ägg','gul lök','ost valfritt','sallad'],leftovers:['potatis'],tip:'Perfekt för några ensamma kokta potatisar.',steps:['Skiva potatis och stek med lök.','Häll över vispade ägg.','Låt stanna på låg värme.','Servera med sallad.']},
{id:'brödpudding-mat',name:'Matig brödpudding med ost',emoji:'🍞',time:35,budget:'low',tags:['vegetariskt','budget','ta-vad-du-har'],ingredients:['torrt bröd','ägg','mjölk','ost','tomat eller grönsaker'],leftovers:['bröd','ost'],tip:'Ett sätt att rädda bröd som blivit torrt.',steps:['Riv eller bryt brödet i form.','Lägg på ost och grönsaker.','Häll över äggstanning.','Gratinera tills den satt sig.']},
{id:'fattiga-riddare',name:'Fattiga riddare av gammalt bröd',emoji:'🍞',time:15,budget:'low',tags:['snabbt','budget'],ingredients:['bröd','ägg','mjölk','kanel','frukt eller bär'],leftovers:['bröd'],tip:'Torrt bröd fungerar ofta bättre än helt färskt.',steps:['Vispa ägg och mjölk.','Doppa brödet.','Stek gyllene på båda sidor.','Servera med frukt eller bär.']},
{id:'smoothie-banan',name:'Smoothie med banan och bär',emoji:'🥤',time:5,budget:'low',tags:['snabbt','vegetariskt','budget'],ingredients:['banan','frysta bär','yoghurt eller mjölk','havregryn valfritt'],leftovers:['banan','bär'],tip:'Övermogna bananer kan skivas och frysas.',steps:['Lägg allt i mixer.','Mixa slätt.','Späd om det behövs.']},
{id:'overnight-oats',name:'Overnight oats',emoji:'🥣',time:5,budget:'low',tags:['snabbt','vegetariskt','budget'],ingredients:['havregryn','mjölk eller yoghurt','bär eller frukt','kanel'],leftovers:['yoghurt','frukt'],tip:'Gör kvällen före så är frukosten klar.',steps:['Blanda havre och vätska i burk.','Lägg på frukt eller bär.','Ställ kallt över natten.']},
{id:'äggmacka',name:'Äggmacka med tomat och grönt',emoji:'🥪',time:10,budget:'low',tags:['snabbt','budget'],ingredients:['bröd','ägg','tomat','sallad','ost eller färskost valfritt'],leftovers:['ägg','bröd'],tip:'En enkel måltid när du vill ha något snabbt med protein.',steps:['Koka eller stek ägg.','Lägg på bröd med tomat och grönt.','Toppa med ägg.']},
{id:'tonfiskmacka',name:'Tonfiskröra på bröd',emoji:'🥪',time:10,budget:'low',tags:['fisk','snabbt','budget'],ingredients:['tonfisk','yoghurt eller majonnäs','citron','gurka eller sallad','bröd'],leftovers:['bröd'],tip:'Röran fungerar även i wrap eller på bakad potatis.',steps:['Blanda tonfisk med krämig bas och citron.','Lägg på bröd.','Toppa med grönt.']},
{id:'bakad-potatis',name:'Bakad potatis med valfri röra',emoji:'🥔',time:60,budget:'low',tags:['budget','ta-vad-du-har'],ingredients:['bakpotatis','tonfiskröra eller kycklingröra eller fetaostkräm','sallad'],leftovers:['fetaost','kyckling'],tip:'Fyllningen kan helt styras av det som finns hemma.',steps:['Baka potatis mjuk.','Gör valfri röra.','Öppna potatisen och fyll.','Servera med sallad.']},
{id:'pannkakor',name:'Pannkakor',emoji:'🥞',time:30,budget:'low',tags:['familj','budget'],ingredients:['mjöl','ägg','mjölk eller vatten','salt','smör eller olja till stekning'],leftovers:['mjölk'],tip:'Det går att göra pannkakor med vatten och olja om det behövs.',steps:['Vispa ihop smeten.','Låt gärna vila en stund.','Stek tunna pannkakor.','Servera med valfria tillbehör.']},
{id:'ugnspannkaka',name:'Ugnspannkaka',emoji:'🥞',time:40,budget:'low',tags:['familj','budget'],ingredients:['mjöl','ägg','mjölk','salt','eventuellt bacon eller äpple'],leftovers:['mjölk'],tip:'Lite aktiv tid – ugnen gör resten.',steps:['Vispa smeten.','Häll i smord form.','Lägg i valfritt tillbehör.','Grädda tills pannkakan stannat och fått färg.']},
{id:'korvplåt',name:'Korv och rotfrukter på plåt',emoji:'🥕',time:45,budget:'low',tags:['familj','budget'],ingredients:['korv','potatis','morot','lök','paprika','olja','örter'],leftovers:['korv','rotfrukter'],tip:'En plåt, enkel disk och bra för det som finns kvar i grönsakslådan.',steps:['Skär allt i bitar.','Blanda med olja och kryddor.','Rosta tills rotfrukterna är mjuka och korven fått färg.']},
{id:'falukorv-ugn',name:'Ugnsbakad falukorv med tomat och ost',emoji:'🍽️',time:45,budget:'low',tags:['familj','budget'],ingredients:['falukorv','tomat','senap','ost','potatismos eller potatis','grönsaker'],leftovers:['korv'],tip:'Lägg gärna lök eller äpple mellan skivorna om du gillar det.',steps:['Skåra korven.','Fyll med tomat, senap och ost.','Ugnsbaka tills korven är het och osten fått färg.','Servera med potatis och grönt.']},
{id:'ärtsoppa',name:'Ärtsoppa',emoji:'🥣',time:120,budget:'low',tags:['soppa','budget','slowcooker'],ingredients:['gula ärtor','gul lök','buljong','timjan','eventuellt fläsk'],leftovers:[],tip:'Kan göras i slowcooker och fryser bra.',steps:['Blötlägg vid behov enligt förpackning.','Koka med lök och buljong tills ärtorna är mjuka.','Smaka av med timjan.']},
{id:'minestrone',name:'Minestronesoppa',emoji:'🥣',time:40,budget:'low',tags:['soppa','vegetariskt','budget','ta-vad-du-har'],ingredients:['gul lök','morot','selleri valfritt','bönor','tomat','pasta','buljong','valfria grönsaker'],leftovers:['grönsaker','pasta'],tip:'En riktig ta-vad-du-har-soppa.',steps:['Fräs lök och grönsaker.','Tillsätt tomat, buljong och bönor.','Koka och lägg i pasta mot slutet.','Smaka av med örter.']},
{id:'köttfärssoppa',name:'Köttfärssoppa med potatis',emoji:'🥣',time:40,budget:'low',tags:['soppa','köttfärs','budget'],ingredients:['köttfärs','potatis','morot','gul lök','tomat','buljong','örter'],leftovers:['potatis','morötter'],tip:'Bra vardagssoppa som kan frysas.',steps:['Bryn färs och lök.','Tillsätt potatis, morot, tomat och buljong.','Koka tills potatisen är mjuk.','Smaka av.']},
{id:'pulled-chicken',name:'Pulled chicken i slowcooker',emoji:'🍗',time:360,budget:'mid',tags:['kyckling','slowcooker','familj'],ingredients:['kyckling','gul lök','vitlök','tomat eller BBQ-sås','paprikapulver','lite buljong'],leftovers:['kyckling'],tip:'Kan bli tacos, wraps, risrätt eller matlåda.',steps:['Lägg allt i slowcooker.','Tillaga tills kycklingen är helt genomlagad och lätt faller isär.','Dra isär och blanda med såsen.']},
{id:'slow-köttfärssås',name:'Köttfärssås i slowcooker',emoji:'🍝',time:360,budget:'low',tags:['köttfärs','slowcooker','budget'],ingredients:['köttfärs','gul lök','vitlök','morot','tomat','tomatpuré','örter'],leftovers:['morötter'],tip:'Förbered när du har ork, låt sedan såsen sköta sig.',steps:['Bryn färsen om du vill.','Lägg allt i slowcookern.','Tillaga långsamt och smaka av innan servering.']},
{id:'slow-kycklinggryta',name:'Kycklinggryta i slowcooker',emoji:'🍗',time:360,budget:'mid',tags:['kyckling','slowcooker','gryta'],ingredients:['kyckling','morot','gul lök','paprika','buljong','tomat eller grädde','örter'],leftovers:['grönsaker'],tip:'Välj tomatbas eller krämig bas efter vad du har.',steps:['Lägg ingredienserna i slowcookern.','Tillaga tills kycklingen är helt genomlagad.','Smaka av och rör i eventuell grädde mot slutet.']}
);

recipes.push(
{id:'laxpasta',name:'Laxpasta med citron och spenat',emoji:'🐟',time:25,budget:'mid',tags:['fisk','snabbt'],ingredients:['lax','pasta','spenat','citron','grädde eller crème fraîche','vitlök'],leftovers:['lax','spenat'],tip:'Ärtor passar också bra i.',steps:['Koka pasta.','Stek lax i bitar.','Tillsätt vitlök, spenat och krämig bas.','Vänd ner pasta och citron.']},
{id:'lax-teriyaki',name:'Lax med teriyaki och broccoli',emoji:'🐟',time:30,budget:'mid',tags:['fisk'],ingredients:['lax','teriyakisås','broccoli','ris','sesam valfritt'],leftovers:['broccoli','ris'],tip:'Kalasris fungerar även här.',steps:['Koka ris.','Baka eller stek lax med teriyaki.','Tillaga broccoli.','Servera tillsammans.']},
{id:'torsk-äggsås',name:'Torsk med äggsås och potatis',emoji:'🐟',time:35,budget:'mid',tags:['fisk','familj'],ingredients:['torsk','potatis','ägg','mjölk','smör','mjöl','persilja','ärtor'],leftovers:['ägg','potatis'],tip:'En klassisk mild fiskmiddag.',steps:['Koka potatis och ägg.','Tillaga torsken.','Gör vit sås och hacka ner ägg och persilja.','Servera med ärtor.']},
{id:'sej-curry',name:'Sej i currysås',emoji:'🐟',time:30,budget:'low',tags:['fisk','budget'],ingredients:['sej','gul lök','curry','mjölk eller grädde','buljong','ris','ärtor'],leftovers:['ris'],tip:'Sej är ofta ett prisvärt fiskalternativ.',steps:['Fräs lök och curry.','Tillsätt vätska och buljong.','Lägg i fisken och sjud tills den är klar.','Servera med ris och ärtor.']},
{id:'fiskburgare',name:'Fiskburgare med kall sås',emoji:'🐟',time:25,budget:'mid',tags:['fisk','familj'],ingredients:['fiskburgare eller fiskfilé','hamburgerbröd','sallad','gurka','tomat','yoghurtsås'],leftovers:['bröd','sallad'],tip:'Rivna morötter passar bra vid sidan.',steps:['Tillaga fisken.','Rör ihop kall sås.','Fyll bröd med fisk och grönt.']},
{id:'räkpasta',name:'Räkpasta med vitlök och citron',emoji:'🦐',time:20,budget:'mid',tags:['fisk','snabbt'],ingredients:['räkor','pasta','vitlök','citron','chili valfritt','persilja','olivolja'],leftovers:['räkor','pasta'],tip:'Lägg i räkorna sist så de bara blir varma.',steps:['Koka pasta.','Fräs vitlök och eventuell chili.','Vänd ner pasta, citron och räkor.','Toppa med persilja.']},
{id:'musselpasta',name:'Pasta med musslor och tomat',emoji:'🦪',time:25,budget:'mid',tags:['fisk'],ingredients:['musslor','pasta','tomat','vitlök','gul lök','persilja','citron'],leftovers:['tomater'],tip:'Kontrollera och hantera musslor enligt förpackningens säkerhetsanvisningar.',steps:['Koka pasta.','Fräs lök, vitlök och tomat.','Tillaga musslorna enligt anvisning.','Blanda med pasta och citron.']},
{id:'fisk-tacos',name:'Fisktacos med kålsallad',emoji:'🌮',time:30,budget:'mid',tags:['fisk','familj'],ingredients:['vit fisk','tortillabröd','vitkål','morot','lime','yoghurt','chili'],leftovers:['vitkål','morötter'],tip:'Kål är billigt, krispigt och håller länge.',steps:['Krydda och tillaga fisken.','Strimla kål och morot.','Rör ihop limesås.','Fyll tortillas.']},
{id:'kyckling-tacos',name:'Kycklingtacos',emoji:'🌮',time:25,budget:'mid',tags:['kyckling','familj'],ingredients:['kyckling','tacokrydda','tortilla','sallad','tomat','majs','sås'],leftovers:['kyckling','majs'],tip:'Resterna kan bli wraps till lunch.',steps:['Stek kyckling genomlagad med krydda.','Hacka grönt.','Fyll tortillas med allt.']},
{id:'kyckling-citron',name:'Citronkyckling med potatis',emoji:'🍗',time:50,budget:'mid',tags:['kyckling','familj'],ingredients:['kyckling','potatis','citron','vitlök','timjan','olja','grönsaker'],leftovers:['potatis'],tip:'Allt kan lagas på samma plåt.',steps:['Lägg potatis och kyckling på plåt.','Krydda med citron, vitlök och timjan.','Ugnsbaka tills kycklingen är genomlagad.']},
{id:'kyckling-pesto',name:'Kyckling med pesto och tomat',emoji:'🍗',time:35,budget:'mid',tags:['kyckling'],ingredients:['kyckling','pesto','tomater','mozzarella eller ost','pasta eller potatis'],leftovers:['tomater','pesto'],tip:'Bra när en pestoburk behöver användas.',steps:['Lägg kyckling i form.','Toppa med pesto, tomat och ost.','Ugnsbaka tills kycklingen är genomlagad.','Servera med pasta eller potatis.']},
{id:'kyckling-senap',name:'Kycklinggryta med dijon och dragon',emoji:'🍗',time:35,budget:'mid',tags:['kyckling','gryta'],ingredients:['kyckling','gul lök','dijonsenap','dragon','grädde','buljong','ris eller potatis'],leftovers:[],tip:'Dijon ger mycket smak med liten mängd.',steps:['Bryn kyckling och lök.','Rör i dijon och dragon.','Häll på grädde och buljong.','Sjud tills kycklingen är klar.']},
{id:'kyckling-soppa',name:'Kycklingsoppa med rotfrukter',emoji:'🥣',time:40,budget:'mid',tags:['kyckling','soppa'],ingredients:['kyckling','morot','potatis','purjolök','buljong','örter'],leftovers:['kyckling','rotfrukter'],tip:'Kokt kyckling från dagen innan passar fint.',steps:['Koka rotfrukter i buljong.','Tillsätt purjolök.','Lägg i genomlagad kyckling och värm.','Smaka av med örter.']},
{id:'kyckling-caesar-wrap',name:'Kycklingwrap med sallad',emoji:'🌯',time:15,budget:'mid',tags:['kyckling','snabbt'],ingredients:['genomlagad kyckling','tortilla','sallad','tomat','gurka','dressing'],leftovers:['kyckling','sallad'],tip:'Perfekt för kycklingrester.',steps:['Skär kyckling och grönsaker.','Fyll tortilla.','Ringla över dressing och rulla ihop.']},
{id:'sjömansbiff',name:'Sjömansbiff',emoji:'🥘',time:100,budget:'mid',tags:['gryta','familj'],ingredients:['nötkött','potatis','gul lök','buljong','lagerblad','öl eller extra buljong valfritt'],leftovers:['potatis'],tip:'Långsam tillagning gör rätten mjuk och smakrik.',steps:['Bryn kött och lök.','Varva med skivad potatis.','Häll på buljong.','Sjud tills kött och potatis är möra.']},
{id:'dillkött',name:'Dillkött med potatis',emoji:'🥘',time:120,budget:'mid',tags:['gryta','familj'],ingredients:['grytkött','morot','gul lök','buljong','dill','grädde','ättika eller citron','potatis'],leftovers:['morötter'],tip:'Smaka fram balansen mellan sött, syrligt och dill.',steps:['Koka köttet mört med grönsaker.','Sila och gör sås av buljongen.','Smaksätt med dill och syra.','Servera med potatis.']},
{id:'järpar',name:'Järpar med gräddsås',emoji:'🥩',time:45,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','ägg','ströbröd','mjölk','lök','gräddsås','potatis','grönsaker'],leftovers:[],tip:'Forma avlånga biffar för variation från köttbullar.',steps:['Blanda färssmet.','Forma järpar och stek genomlagade.','Gör sås i pannan.','Servera med potatis och grönt.']},
{id:'köttfärslimpa',name:'Köttfärslimpa',emoji:'🥩',time:65,budget:'low',tags:['köttfärs','familj','budget'],ingredients:['köttfärs','ägg','ströbröd','mjölk','gul lök','kryddor','potatis','sås'],leftovers:[],tip:'Rester blir goda på smörgås eller i matlåda.',steps:['Blanda färssmet.','Forma limpa i form.','Ugnsbaka tills genomlagad.','Servera med potatis, sås och grönsaker.']},
{id:'tacogratäng',name:'Tacogratäng',emoji:'🌮',time:40,budget:'mid',tags:['köttfärs','familj'],ingredients:['köttfärs','tacokrydda','majs','paprika','tomat','crème fraîche','ost','sallad'],leftovers:['tacofärs','majs'],tip:'Bra för tacorester dagen efter.',steps:['Lägg tacofärs och grönsaker i form.','Bred över crème fraîche.','Toppa med ost.','Gratinera och servera med sallad.']},
{id:'fylld-paprika',name:'Fylld paprika med köttfärs och ris',emoji:'🫑',time:50,budget:'mid',tags:['köttfärs'],ingredients:['paprika','köttfärs','kokt ris','gul lök','tomat','ost'],leftovers:['ris','köttfärs'],tip:'Ett bra sätt att använda lite ris och färs som blivit över.',steps:['Blanda genomlagad färs med ris och tomat.','Fyll halverade paprikor.','Toppa med ost.','Baka tills paprikan är mjuk.']},
{id:'köttfärspaj',name:'Köttfärspaj',emoji:'🥧',time:60,budget:'mid',tags:['köttfärs','familj'],ingredients:['pajdeg','köttfärs','gul lök','tomatpuré','ägg','mjölk','ost','sallad'],leftovers:['köttfärs'],tip:'Paj är bra matlådemat.',steps:['Förgrädda pajskal vid behov.','Fyll med stekt färs och lök.','Häll över äggstanning och ost.','Grädda tills stanningen satt sig.']},
{id:'veg-lasagne',name:'Vegetarisk lasagne med spenat och linser',emoji:'🍝',time:70,budget:'low',tags:['vegetariskt','budget'],ingredients:['lasagneplattor','linser','spenat','tomat','gul lök','vitlök','vit sås','ost'],leftovers:['spenat'],tip:'Linser gör såsen fyllig utan kött.',steps:['Koka tomatsås med linser.','Gör vit sås.','Varva med spenat och plattor.','Gratinera med ost.']},
{id:'veg-biffar',name:'Bönbiffar med kall sås',emoji:'🫘',time:30,budget:'low',tags:['vegetariskt','budget'],ingredients:['bönor','ägg eller bindande alternativ','havregryn','gul lök','kryddor','yoghurtsås','potatis eller sallad'],leftovers:['bönor'],tip:'Bönor kan mosas grovt – lite struktur är gott.',steps:['Mosa bönor.','Blanda med lök, havre och bindning.','Forma biffar och stek.','Servera med kall sås.']},
{id:'veg-pytt',name:'Grönsakspytt med ägg',emoji:'🍳',time:25,budget:'low',tags:['vegetariskt','budget','ta-vad-du-har'],ingredients:['kokt potatis','morot','lök','andra grönsaker','ägg'],leftovers:['potatis','grönsaker'],tip:'Använd små rester från grönsakslådan.',steps:['Tärna allt.','Stek tills det fått färg.','Toppa med stekt ägg.']},
{id:'spenatpaj',name:'Spenat- och fetaostpaj',emoji:'🥧',time:55,budget:'mid',tags:['vegetariskt'],ingredients:['pajdeg','spenat','fetaost','ägg','mjölk','gul lök'],leftovers:['fetaost','spenat'],tip:'Bra när fetaost och spenat behöver gå åt.',steps:['Förbered pajskal.','Fräs spenat och lök.','Fyll med fetaost.','Häll över äggstanning och grädda.']},
{id:'grekisk-sallad',name:'Grekisk sallad med fetaost',emoji:'🥗',time:15,budget:'mid',tags:['vegetariskt','snabbt'],ingredients:['tomat','gurka','paprika','rödlök','fetaost','oliver','olivolja'],leftovers:['fetaost','tomater','gurka'],tip:'Servera med bröd för en enklare lunch.',steps:['Skär grönsaker.','Blanda med fetaost och oliver.','Ringla över olivolja.']},
{id:'pastasallad',name:'Pastasallad med det som finns',emoji:'🥗',time:20,budget:'low',tags:['budget','ta-vad-du-har'],ingredients:['kokt pasta','grönsaker','ost eller valfritt protein','dressing'],leftovers:['pasta','grönsaker','ost'],tip:'Perfekt för lite kokt pasta som inte räcker till en hel middag.',steps:['Kyl pastan.','Blanda med det gröna och protein du har.','Tillsätt dressing.']},
{id:'potatissallad-varm',name:'Varm potatissallad med senap',emoji:'🥔',time:25,budget:'low',tags:['vegetariskt','tillbehör','budget'],ingredients:['kokt potatis','rödlök','dijonsenap','olja','vinäger eller citron','örter'],leftovers:['potatis'],tip:'God till fisk, kyckling eller bönbiffar.',steps:['Dela varm eller ljummen potatis.','Rör ihop dressing.','Vänd med lök och örter.']},
{id:'bananpannkaka',name:'Bananpannkakor',emoji:'🥞',time:15,budget:'low',tags:['snabbt','vegetariskt','budget'],ingredients:['banan','ägg','havregryn valfritt','kanel'],leftovers:['banan'],tip:'Ett bra sätt att använda en mycket mogen banan.',steps:['Mosa banan.','Blanda med ägg och eventuell havre.','Stek små pannkakor.']},
{id:'gröt-äpple',name:'Havregrynsgröt med äpple och kanel',emoji:'🥣',time:8,budget:'low',tags:['snabbt','vegetariskt','budget'],ingredients:['havregryn','vatten eller mjölk','äpple','kanel'],leftovers:['äpple'],tip:'Riv äpplet direkt i gröten.',steps:['Koka havregryn med vätska.','Riv ner äpple.','Toppa med kanel.']},
{id:'kvarg-bär',name:'Kvarg med bär och müsli',emoji:'🥣',time:3,budget:'low',tags:['snabbt','vegetariskt'],ingredients:['kvarg','bär','müsli','frukt valfritt'],leftovers:['bär','kvarg'],tip:'Fungerar som frukost eller mellanmål.',steps:['Häll upp kvarg.','Toppa med bär och müsli.']},
{id:'bruschetta',name:'Bruschetta av bröd och tomater',emoji:'🍅',time:15,budget:'low',tags:['vegetariskt','snabbt','budget'],ingredients:['bröd','tomater','vitlök','olivolja','basilika'],leftovers:['bröd','tomater'],tip:'Torrt bröd får nytt liv när det rostas.',steps:['Rosta bröd.','Hacka tomat och basilika.','Gnid brödet med vitlök.','Toppa med tomat och olivolja.']},
{id:'quesadilla-rester',name:'Quesadilla med ost och rester',emoji:'🌯',time:15,budget:'low',tags:['snabbt','budget','ta-vad-du-har'],ingredients:['tortilla','ost','kyckling eller bönor eller grönsaker'],leftovers:['ost','kyckling','grönsaker'],tip:'Lite av mycket räcker fint mellan två tortillas.',steps:['Fördela fyllning och ost på tortilla.','Vik eller lägg en tortilla ovanpå.','Stek på båda sidor tills osten smält.']}
);

const addRecipe=(recipe,first=false)=>{if(recipes.some(r=>r.id===recipe.id))return;first?recipes.unshift(recipe):recipes.push(recipe)};

addRecipe({id:'tomatsas-malix',name:'Tomatsås à la Malix',emoji:'🍅',time:30,budget:'low',tags:['vegetariskt','budget','tillbehör','ta-vad-du-har','pizza','varma mackor'],ingredients:['krossade tomater','buljongtärning','vitlök','basilika','rikligt med svartpeppar','grädde valfritt','vatten vid behov','majsstärkelse eller mjöl till toppredning valfritt'],leftovers:['grillade grönsaker','grillad kyckling','grillat kött','grillad korv'],plants:3,tip:'🍅 En grundsås med många användningar: till pasta, pizza och varma mackor. Rädda också grillrester genom att skära ner dem och låta dem puttra i tomatsåsen. Servera med pasta eller ris – blanda med tomatsås och du är nästan hemma i Italien.',steps:['Häll krossade tomater i en kastrull och tillsätt buljongtärning, vitlök, basilika och rikligt med svartpeppar.','Låt såsen koka och utveckla smak en stund.','Vill du ha en rundare och krämigare sås kan du tillsätta lite grädde, men den går bra att utesluta.','Späd med lite vatten om såsen blir för tjock.','Om du vill ha den tjockare, avsluta med en liten toppredning av majsstärkelse eller mjöl utrört i kallt vatten.','Använd som pastasås, pizzasås eller bred på varma mackor före topping och gratinering.']},true);
addRecipe({id:'chalaw-afghanskt-ris',name:'Chalaw – afghanskt inspirerat ris',emoji:'🍚',time:35,budget:'low',tags:['vegetariskt','budget','tillbehör','grundrecept'],ingredients:['basmatiris','rikligt med vatten','salt'],leftovers:['ris'],tip:'Variera riset om du vill: gurkmeja ger färg och mild smak, curry ger tydligare kryddning. Du kan också prova lite spiskummin, kardemumma eller saffran. Kryddorna är variationer – de behövs inte för grundreceptet.',steps:['Skölj basmatiriset tills vattnet blir klarare.','Koka riset i rikligt med saltat vatten tills det är nästan färdigt.','Häll av vattnet ordentligt.','Lägg tillbaka riset i kastrullen och låt det ånga färdigt under lock på mycket låg värme eller med värmen avstängd.','Lufta försiktigt med en gaffel före servering.']});
const consolidatedStroganoff=recipes.find(r=>/korvstroganoff/i.test(r.name||''));if(consolidatedStroganoff){if(!consolidatedStroganoff.tags.includes('korv'))consolidatedStroganoff.tags.push('korv');if(!String(consolidatedStroganoff.tip||'').includes('chalaw'))consolidatedStroganoff.tip=(consolidatedStroganoff.tip?consolidatedStroganoff.tip+' ':'')+'Servera med vanligt ris, chalaw eller kryddat chalaw. Kryddat chalaw kan varieras med till exempel gurkmeja, curry, spiskummin, kardemumma eller saffran.';}
addRecipe({id:'kokt-korv-mos',name:'Kokt korv med potatismos',emoji:'🌭',time:25,budget:'low',tags:['korv','snabbt','familj','budget'],ingredients:['grillkorv eller kokkorv','potatis','mjölk','smör','ärtor','senap eller ketchup'],leftovers:['potatismos','korv'],plants:2,tip:'En enkel vardagsrätt. Har du färdigt mos går den ännu snabbare.',steps:['Koka potatisen mjuk och gör potatismos med mjölk och smör.','Värm korven försiktigt enligt förpackningens anvisning.','Värm ärtor.','Servera med senap eller ketchup efter smak.']});
addRecipe({id:'falukorv-makaroner',name:'Stekt falukorv med makaroner',emoji:'🌭',time:20,budget:'low',tags:['korv','snabbt','familj','budget'],ingredients:['falukorv','makaroner','grönsaker','ketchup eller senap'],leftovers:['falukorv','makaroner'],plants:1,tip:'Kokta makaroner från dagen innan gör middagen ännu snabbare.',steps:['Koka makaronerna.','Skiva falukorven och stek den.','Lägg till de grönsaker du vill ha.','Servera med ketchup eller senap om du tycker om det.']});
addRecipe({id:'falukorv-ugn',name:'Ugnsbakad falukorv med potatismos',emoji:'🌭',time:45,budget:'low',tags:['korv','familj','budget'],ingredients:['falukorv','tomat','gul lök','senap','ost','potatis','mjölk','smör'],leftovers:['falukorv','potatismos'],plants:3,tip:'Fyll snitten med det du tycker om – tomat, lök, senap och ost är en klassisk kombination.',steps:['Skär snitt i falukorven utan att skära hela vägen igenom.','Fyll med tomat, lök, senap och ost.','Baka i ugn tills korven är genomvarm och osten fått färg.','Servera med potatismos.']});
addRecipe({id:'flaskkorv-rotmos',name:'Fläskkorv med rotmos',emoji:'🌭',time:50,budget:'mid',tags:['korv','familj'],ingredients:['fläskkorv','potatis','kålrot','morot','smör','buljong','senap'],leftovers:['rotmos'],plants:3,tip:'Rotmos kan göras i större sats och användas till en annan måltid dagen efter.',steps:['Skala och koka potatis, kålrot och morot mjuka.','Mosa med lite kokspad eller buljong och smör.','Tillaga fläskkorven enligt förpackningens anvisning tills den är genomvarm.','Servera med senap.']});
addRecipe({id:'kottkorv-potatis',name:'Köttkorv med kokt potatis och senapssås',emoji:'🌭',time:35,budget:'mid',tags:['korv','familj'],ingredients:['köttkorv','potatis','mjölk','smör','mjöl','senap','grönsaker'],leftovers:['potatis','korv'],plants:2,tip:'Senapssåsen kan göras mild eller stark efter smak.',steps:['Koka potatisen.','Tillaga köttkorven enligt förpackningens anvisning.','Gör en enkel vit sås och smaka av med senap.','Servera med valfria grönsaker.']});
addRecipe({id:'prinskorv-stekt-potatis',name:'Prinskorv med stekt potatis och ägg',emoji:'🌭',time:25,budget:'mid',tags:['korv','snabbt','familj','ta-vad-du-har'],ingredients:['prinskorv','kokt potatis','ägg','gul lök','grönsaker'],leftovers:['potatis','prinskorv'],plants:2,tip:'Passar särskilt bra när det finns kokt potatis kvar.',steps:['Skiva den kokta potatisen och stek med lök.','Stek prinskorven genomvarm.','Stek ägg.','Servera med grönsaker.']});
addRecipe({id:'tacos-blandfars',name:'Vanliga tacos med blandfärs',emoji:'🌮',time:30,budget:'mid',tags:['familj','köttfärs','snabbt'],ingredients:['500 g blandfärs','tacokrydda','tacoskal','crème fraîche eller gräddfil','tomat','gurka','gul lök','sallad','majs','pepperoni','tacosås','riven ost'],leftovers:['tacofärs','grönsaker','riven ost'],plants:6,tip:'Ställ fram allt i små skålar så kan var och en bygga sin taco med de tillbehör den tycker om. Det som blir över kan bli tacotallrik eller lunch nästa dag.',steps:['Bryn blandfärsen tills den är helt genomstekt.','Tillsätt tacokrydda och den mängd vatten som behövs enligt kryddningen. Låt puttra några minuter.','Hacka tomat, gurka, lök och sallad. Ställ fram majs, pepperoni, tacosås, ost och crème fraîche eller gräddfil.','Värm tacoskalen och låt var och en fylla sin taco med det den tycker om.']});
addRecipe({id:'popupbrod',name:'Glutenfritt popup-bröd',emoji:'🥖',time:35,budget:'low',tags:['vegetariskt','bröd','tillbehör','soppa','gryta','glutenfritt'],ingredients:['3 ägg','3 dl mjölk','1 nypa salt','150 g glutenfri mjölmix','40 g smält smör','1 tsk fiberhusk – kan uteslutas'],leftovers:[],plants:1,tip:'Påminner om Yorkshire pudding men bakas i muffinsformar. Gott till soppa, gryta, chili con carne, kålpudding eller som ett luftigare bröd till sallad.',serving:'Servera gärna varmt till soppa eller gryta. Det passar också till chili con carne och kålpudding, där brödet kan suga upp sås eller sky.',steps:['Sätt ugnen på 220 grader.','Vispa ihop ägg, mjölk och salt.','Tillsätt glutenfri mjölmix och fiberhusk. Vispa till en slät smet.','Låt smeten vila 5–10 minuter.','Smält smöret och fördela det i muffinsformar.','Häll i smeten till cirka hälften av formarna.','Grädda mitt i ugnen i cirka 20–25 minuter tills bröden puffat upp och fått fin färg.']});
addRecipe({id:'pannkakor-grund',name:'Pannkakor – grundrecept',emoji:'🥞',time:30,budget:'low',tags:['pannkaka','vegetariskt','vardag'],plants:1,ingredients:['ägg','mjölk','vetemjöl','lite salt','smör eller annat matfett till stekning'],leftovers:[],tip:'Låt gärna smeten stå en liten stund om du har tid. Servera sött eller matigt efter vad som finns hemma.',serving:'Sylt och bär passar fint, men pannkakor kan också fyllas med matiga rester.',swaps:'Behöver du glutenfritt, använd en glutenfri pannkaksmix/mjölmix avsedd för pannkakor och följ mängden för just den produkten.',steps:['Vispa ihop mjöl och en del av mjölken till en slät smet.','Vispa ner resten av mjölken, äggen och saltet.','Stek tunna pannkakor i lite matfett.']});
addRecipe({id:'ugnspannkaka',name:'Ugnspannkaka',emoji:'🥞',time:40,budget:'low',tags:['pannkaka','ugn','familj','budget','vardag'],plants:1,ingredients:['mjöl','ägg','mjölk','salt','eventuellt bacon eller äpple'],leftovers:['mjölk'],tip:'Lite aktiv tid – ugnen gör resten. Gör den naturell eller lägg till bacon eller äpple om du vill.',serving:'Servera efter smak, till exempel med sylt eller andra tillbehör du brukar tycka om.',swaps:'Behöver du glutenfritt kan du använda en glutenfri mjölmix som passar till pannkakor och anpassa mängden efter produkten.',steps:['Vispa ihop smeten.','Häll i en smord ugnsform.','Lägg i bacon eller äpple om du vill ha en sådan variant.','Grädda tills ugnspannkakan har stannat och fått fin färg.']});
addRecipe({id:'ugnsomelett-malix',name:'Fluffig ugnsomelett',emoji:'🍳',time:40,budget:'low',tags:['omelett','ugn','glutenfritt alternativ','vardag'],plants:0,ingredients:['ägg','mjölk','lite salt och peppar','lite Maizena/majsstärkelse för glutenfri redning – eller vetemjöl om du tål gluten','smör till formen'],leftovers:[],tip:'Varm mjölk och en lätt redning ger en mjuk och luftig ugnsomelett. Lägg gärna till en stuvning eller fyllning efter vad du har hemma.',serving:'Kan serveras som den är eller med exempelvis svamp-, räk- eller grönsaksstuvning och bröd.',swaps:'För glutenfri variant: red med majsstärkelse. Om gluten fungerar för dig kan du använda vanligt vetemjöl som redning.',steps:['Sätt ugnen på cirka 200 grader och smörj en ugnsform.','Värm mjölken. Gör en liten slät redning av Maizena/majsstärkelse och lite kall mjölk, eller använd vetemjöl om du tål gluten. Vispa ner redningen i den varma mjölken och låt den tjockna lätt.','Låt mjölkblandningen svalna något. Vispa upp äggen försiktigt med salt och peppar.','Vispa ner mjölkblandningen i äggen.','Häll i formen och grädda tills omeletten har stannat och blivit luftig.']});
[
{id:'carbonara',name:'Pasta carbonara',emoji:'🍝',time:25,budget:'medium',tags:['pasta','snabbt','vardag'],plants:1,ingredients:['pasta','bacon eller pancetta','ägg','parmesan','svartpeppar'],leftovers:['bacon'],tip:'Spara lite pastavatten och använd för att få såsen blank och krämig.',serving:'Gott med extra parmesan, vitt bröd och något grönt vid sidan.',swaps:'Bacon kan bytas mot annan rökt/skivad rest som passar. Parmesan kan bytas mot annan lagrad hårdost.',steps:['Koka pastan.','Stek bacon/pancetta.','Vispa ihop ägg, parmesan och svartpeppar.','Vänd ner varm pasta och bacon. Ta från värmen och rör ner äggblandningen. Späd försiktigt med lite pastavatten.']},
{id:'pastamexicana',name:'Pasta Mexicana',emoji:'🌶️',time:35,budget:'medium',tags:['pasta','mexicana','vardag','kött'],plants:5,ingredients:['pasta','Tomatsås à la Malix eller annan tomatsås','fläskkött eller nötkött i bitar','lök i bitar','paprika i bitar','vitlök','chili','svartpeppar','gärna buljong','majs – om du vill'],leftovers:['kött','paprika','majs','tomatsås'],tip:'Stek kött, lök och paprika ordentligt först. Tomatsåsen binder ihop rätten och chili, vitlök, svartpeppar och lite buljong ger mer smak.',serving:'Parmesan, vitt bröd eller popup-bröd kan passa till om du vill.',swaps:'Välj fläsk eller nöt efter vad du har. Majs är valfritt. Tomatsås à la Malix fungerar fint som bas.',steps:['Koka pastan.','Skär köttet i bitar och bryn det.','Lägg i lök och paprika i bitar och stek vidare. Tillsätt rikligt med vitlök, chili och svartpeppar.','Häll på tomatsåsen och smaka gärna upp med lite buljong. Lägg i majs om du vill.','Låt allt puttra ihop och servera med pastan.']},
{id:'fruttidimare',name:'Pasta Frutti del mare',emoji:'🦐',time:30,budget:'medium',tags:['pasta','fisk','skaldjur','frutti del mare'],plants:3,ingredients:['pasta','blandade skaldjur','vitlök','tomat','olivolja','persilja','citron'],leftovers:[],tip:'Skaldjuren behöver bara bli varma så att de inte tillagas för länge.',serving:'Citron, persilja, vitt bröd och en enkel sallad passar bra till.',swaps:'Använd den blandning av skaldjur du har. Tomat kan vara färsk eller från burk.',steps:['Koka pastan.','Fräs vitlök försiktigt i olja och tillsätt tomat.','Vänd ner skaldjuren mot slutet.','Blanda med pasta och avsluta med persilja och citron.']},
{id:'pastamurklor',name:'Pasta à la murklor',emoji:'🍄',time:30,budget:'medium',tags:['pasta','svamp','krämigt'],plants:2,ingredients:['pasta','förvällda/tillagade murklor','lök','grädde','parmesan','svartpeppar'],leftovers:['svamp'],tip:'Använd endast murklor som är korrekt förberedda för matlagning.',serving:'Parmesan och något grönt vid sidan passar bra. Stekt grönkål eller svartkål kan vara ett alternativ.',swaps:'Murklor kan bytas mot annan matsvamp.',steps:['Koka pastan.','Fräs lök och de färdigförberedda murklorna.','Tillsätt grädde och låt såsen gå ihop.','Vänd ner pastan och avsluta med parmesan och svartpeppar.']},
{id:'pastacapri',name:'Pasta Capri',emoji:'🍝',time:30,budget:'medium',tags:['pasta','vardag','fläskkotlett'],plants:3,ingredients:['pasta','benfri kotlett','lök','svartpeppar','basilika','oregano','Tomatsås à la Malix eller grädde'],leftovers:['kotlett','tomatsås'],tip:'Pasta Capri kan göras på två sätt: tomatvarianten med Tomatsås à la Malix eller en enkel krämig variant med grädde.',serving:'Servera som den är eller med parmesan, vitt bröd eller något grönt vid sidan.',swaps:'Välj Tomatsås à la Malix för en tomatigare rätt eller grädde för en mildare, krämig variant.',steps:['Koka pastan.','Skär den benfria kotletten i mindre bitar eller strimlor och stek den.','Tillsätt lök och låt den mjukna. Krydda med svartpeppar, basilika och oregano.','Välj Tomatsås à la Malix eller grädde och låt såsen gå ihop.','Vänd ihop med pastan och servera.']},
{id:'kasslergorgonzolapasta',name:'Pasta med kassler och gorgonzola',emoji:'🧀',time:30,budget:'medium',tags:['pasta','krämigt','vardag'],plants:2,ingredients:['pasta','kassler','lök','gorgonzola','grädde','svartpeppar'],leftovers:['kassler'],tip:'Smaka innan du saltar – både kassler och gorgonzola ger mycket sälta.',serving:'Något grönt passar bra till, till exempel stekt grönkål eller svartkål.',swaps:'Kassler kan bytas mot en lämplig köttrest. Gorgonzola kan bytas mot annan smakrik ost.',steps:['Koka pastan.','Fräs lök och kassler.','Tillsätt grädde och gorgonzola och låt osten smälta.','Vänd ner pastan och krydda med svartpeppar.']},
{id:'pastatomatsasmalix',name:'Pasta med Tomatsås à la Malix',emoji:'🍅',time:25,budget:'low',tags:['pasta','rester','billigt','vegetariskt'],plants:5,ingredients:['pasta','Tomatsås à la Malix'],leftovers:['grillrester','tonfisk','grönsaker'],tip:'Tomatsåsen och pasta räcker som rätt. Vill du förändra den kan du använda det som redan finns hemma.',serving:'Vitt bröd, popup-bröd eller parmesan kan passa till.',swaps:'Rör ner tonfisk mot slutet, eller använd grillrester, svamp, paprika, zucchini eller andra grönsaksrester. Lite grädde ger en mildare och krämigare sås.',steps:['Koka pastan.','Värm Tomatsås à la Malix.','Välj om du vill äta den som den är eller lägga till tonfisk, grillrester eller grönsaker.','Blanda med pastan och servera.']},
{id:'stektkalbacon',name:'Stekt grönkål eller svartkål med bacon',emoji:'🥬',time:20,budget:'low',tags:['tillbehör','grönkål','svartkål','rester'],plants:1,ingredients:['grönkål eller svartkål','bacon','lite grädde – valfritt','svartpeppar'],leftovers:['bacon','grönkål','svartkål'],tip:'Lite grädde gör kålen mjukare och krämigare.',serving:'Passar som varmt tillbehör till många pastarätter och andra vardagsrätter.',swaps:'Grönkål och svartkål kan bytas mot varandra. Bacon kan uteslutas. Lite parmesan eller vitlök kan läggas till om du vill.',steps:['Strimla kålen.','Stek bacon och låt kålen steka med tills den mjuknar.','Tillsätt eventuellt lite grädde och låt den koka in.','Avsluta med svartpeppar.']},
{id:'makaronpuddingpizza',name:'Restpizza på makaronpudding',emoji:'🍕',time:25,budget:'low',tags:['rester','pizza','makaronpudding','rädda maten'],plants:2,ingredients:['kall makaronpudding','lite tomatsås – valfritt','skinka','lök','det du har hemma','rikligt med riven ost'],leftovers:['makaronpudding','skinka','ost','grönsaker'],tip:'Här är makaronpuddingen själva pizzabottnen – ett sätt att göra en helt ny rätt av rester.',serving:'Servera som den är eller med något grönt vid sidan.',swaps:'Skinka och lök är bara en början. Använd till exempel svamp, paprika, tomat, majs, grillrester eller andra pizzavänliga rester. Toppa ordentligt med ost.',steps:['Sätt ugnen på cirka 225 grader.','Lägg kall makaronpudding i en smord form eller på bakplåtspapper och tryck ut den till en stadig, jämn botten.','Bred eventuellt på lite tomatsås.','Lägg på skinka, lök och det du har hemma.','Täck med rikligt med ost.','Grädda tills allt är genomvarmt och osten har smält och fått färg.']}
].forEach(r=>addRecipe(r));

const dessertTags=['efterrätt','något gott','klassisk efterrätt'];
const popup=recipes.find(r=>r.id==='popupbrod');if(popup){popup.tags=[...new Set([...(popup.tags||[]),'efterrätt','något gott','pannkaksalternativ'])];popup.serving='Servera varmt till soppa eller gryta. Som efterrätt kan popup-bröden bli små pannkaksbullar med sylt och vispad grädde.';popup.swaps='🍓 Pannkaksbullar: När du inte vill stå och steka pannkakor kan samma popup-bröd serveras med sylt och grädde. En enkel efterrätt efter till exempel soppa.';}
addRecipe({id:'malix-appelpaj-pa-en-hoft',name:'Malix enkla paj – på en höft',emoji:'🍎',time:50,budget:'low',tags:[...dessertTags,'paj','äpple','päron','blåbär','rabarber','på en höft','glutenfritt alternativ','Malix-recept'],plants:2,ingredients:['ca 300 g smör','ca 1,5 dl socker','havregryn eller glutenfritt mjöl – tills det blir en deg','vaniljsocker – om du vill','kokos – om du tycker om det','valfri fyllning: äpple, päron, blåbär eller rabarber','kanel och socker till äpple/päron','socker efter smak till bär/rabarber','lite potatismjöl till saftig fyllning som blåbär eller rabarber'],leftovers:['äpplen','päron','blåbär','rabarber'],tip:'🥄 På en höft: Börja med ungefär 300 g smör och 1,5 dl socker och tillsätt havregryn eller glutenfritt mjöl tills degen känns bra att trycka ut. Vi gillar mycket deg.',serving:'Gott som det är eller med vaniljsås, glass eller grädde.',swaps:'🍐 Päronpaj: byt äpplena mot päron. 🫐 Blåbärspaj eller rabarberpaj: använd samma pajdeg men strö lite potatismjöl över den saftiga fyllningen tillsammans med socker så att pajen inte blir onödigt rinnig. Vaniljsocker och kokos är frivilligt.',steps:['Sätt ugnen på 175 grader.','Smält smöret i en kastrull.','Blanda ner socker och sedan havregryn eller glutenfritt mjöl direkt i kastrullen tills det blir en deg. Tillsätt vaniljsocker och kokos om du vill.','Tryck ut en del av degen i botten av en pajform. Spara resten.','För äpple eller päron: skala och klyfta och skaka med kanel och socker i en påse. För blåbär eller rabarber: blanda med socker efter smak och lite potatismjöl.','Fördela fyllningen över botten.','Tryck eller smula resten av degen ovanpå.','Grädda mitt i ugnen tills pajen är gyllenbrun och frukten eller bären inte längre saftar sig så mycket. Räkna ungefär 30–45 minuter, men låt färg och fyllning avgöra.']});
addRecipe({id:'saffranspannkaka',name:'Saffranspannkaka',emoji:'💛',time:55,budget:'medium',tags:[...dessertTags,'risgrynsgröt','saffran','rester'],plants:1,ingredients:['risgrynsgröt','ägg','mjölk eller grädde','saffran','lite socker efter smak','mandel – valfritt'],leftovers:['risgrynsgröt'],tip:'Ett bra sätt att göra något nytt av risgrynsgröt. Smaka av sötman efter hur söt gröten redan är.',serving:'Servera gärna med sylt och grädde.',swaps:'Mandeln kan uteslutas.',steps:['Sätt ugnen på cirka 200 grader.','Rör ihop risgrynsgröt, ägg, saffran och lite mjölk eller grädde. Smaka av med socker.','Rör i mandel om du vill.','Häll i en smord ugnsform.','Grädda tills pannkakan har stannat och fått fin färg.']});
addRecipe({id:'risgrynspudding',name:'Risgrynspudding',emoji:'🍚',time:45,budget:'low',tags:[...dessertTags,'risgrynsgröt','rester','ugn'],plants:1,ingredients:['risgrynsgröt','ägg','mjölk','lite socker efter smak','vaniljsocker – valfritt'],leftovers:['risgrynsgröt'],tip:'Bra restmat när det finns risgrynsgröt kvar.',serving:'Servera varm eller kall med sylt, bär, saftsås eller lite grädde.',swaps:'Vaniljsocker är valfritt.',steps:['Sätt ugnen på cirka 200 grader.','Rör ihop risgrynsgröt med ägg och lite mjölk.','Smaka av med socker och eventuellt vaniljsocker.','Häll i en smord form.','Grädda tills puddingen har stannat och fått lite färg.']});
addRecipe({id:'farmors-appelmos',name:'Farmors äppelmos med grädde och kanel',emoji:'🍎',time:2,budget:'low',tags:[...dessertTags,'enkelt','billigt','ingen tillagning','Malix-minne'],plants:1,ingredients:['äppelmos','vanlig ovispad grädde','kanel'],leftovers:['äppelmos'],tip:'Tre enkla saker räcker. Grädden ska vara rinnande, precis som farmor serverade den.',serving:'Lägg äppelmos i en skål, häll över ovispad grädde och pudra med kanel.',steps:['Lägg äppelmos i portionsskålar.','Häll över vanlig ovispad grädde.','Strö över kanel och servera.']});
addRecipe({id:'malix-fruktsallad',name:'Malix fruktsallad – smak av sommar',emoji:'🍓',time:10,budget:'low',tags:[...dessertTags,'frukt','bär','ta vad du har','rädda maten','på en höft','Malix-recept'],plants:5,ingredients:['frukt du har hemma','bär – färska eller tinade, om du har','russin – valfritt','kokos – valfritt','nötter eller frön – valfritt'],leftovers:['frukt','bär'],tip:'🥄 På en höft: Inga mängder behövs. Lite tråkig men fortfarande bra frukt kan bli en smak av sommar när den blandas med annan frukt eller bär.',serving:'Ät som den är eller med grädde, yoghurt eller vaniljkvarg.',swaps:'All frukt och alla bär kan varieras. Nötter kan uteslutas helt eller bytas mot frön.',steps:['Gå igenom frukten och använd bara det som fortfarande är friskt och bra.','Skär frukten i bitar och blanda med de bär du har.','Tillsätt russin, kokos, nötter eller frön om du vill.','Servera direkt eller låt stå kallt en stund.']});
addRecipe({id:'klassisk-chokladpudding',name:'Klassisk chokladpudding',emoji:'🍫',time:20,budget:'low',tags:[...dessertTags,'pudding','choklad','billigt'],plants:0,ingredients:['mjölk','kakao','socker','majsstärkelse','vaniljsocker'],leftovers:['mjölk'],tip:'En gammal vardagsklassiker som bygger på vanliga skafferivaror. Majsstärkelse gör den naturligt glutenfri om övriga ingredienser är glutenfria.',serving:'God kall med grädde, bär eller precis som den är.',steps:['Vispa ihop mjölk, kakao, socker och majsstärkelse i en kastrull.','Värm under ständig omrörning tills puddingen tjocknar.','Ta från värmen och smaksätt med vaniljsocker.','Häll upp i skålar och låt svalna.']});
addRecipe({id:'klassisk-vaniljpudding',name:'Klassisk vaniljpudding',emoji:'🍮',time:20,budget:'low',tags:[...dessertTags,'pudding','vanilj','billigt'],plants:0,ingredients:['mjölk','socker','majsstärkelse','vaniljsocker eller vanilj'],leftovers:['mjölk'],tip:'En enkel mjölkpudding med få ingredienser.',serving:'Servera kall med frukt, bär, sylt eller kanel.',steps:['Vispa ihop mjölk, socker och majsstärkelse i en kastrull.','Värm under omrörning tills puddingen tjocknar.','Ta från värmen och smaksätt med vanilj.','Häll upp och kyl.']});
addRecipe({id:'mannagrynspudding',name:'Mannagrynspudding',emoji:'🥣',time:40,budget:'low',tags:[...dessertTags,'mannagryn','pudding','billigt'],plants:0,ingredients:['mjölk','mannagryn','ägg','lite socker','vaniljsocker – valfritt','smör till formen'],leftovers:['mjölk','mannagrynsgröt'],tip:'En klassisk grynpudding som gör enkla basvaror till efterrätt.',serving:'Servera gärna med sylt eller saftsås.',steps:['Koka en ganska tjock mannagrynsgröt.','Låt svalna lite och rör ner ägg, lite socker och eventuellt vaniljsocker.','Häll i smord form.','Grädda i ugn tills puddingen stannat och fått lite färg.']});
addRecipe({id:'fruktsoppa-klassisk',name:'Fruktsoppa – ta den torkade frukt du har',emoji:'🍑',time:35,budget:'low',tags:[...dessertTags,'frukt','torkad frukt','billigt','ta vad du har'],plants:4,ingredients:['torkad frukt, till exempel katrinplommon, aprikoser, russin eller äpple','vatten','socker efter smak','potatismjöl eller majsstärkelse till lätt redning – valfritt'],leftovers:['torkad frukt'],tip:'Det här behöver inte vara en exakt fruktblandning. Använd den torkade frukt som finns hemma.',serving:'Servera varm, ljummen eller kall, gärna med en skvätt mjölk eller grädde om du tycker om det.',steps:['Skär större torkad frukt i bitar.','Koka frukten mjuk i vatten.','Smaka av med lite socker.','Vill du ha soppan lite fylligare kan den redas lätt på slutet.','Låt svalna till den temperatur du tycker om.']});
addRecipe({id:'katrinplommonkompott',name:'Katrinplommonkompott',emoji:'🟣',time:25,budget:'low',tags:[...dessertTags,'katrinplommon','kompott','billigt'],plants:1,ingredients:['katrinplommon','vatten','lite socker efter smak'],leftovers:['katrinplommon'],tip:'Fruktkompott är en gammal enkel efterrätt där frukten får vara huvudsaken.',serving:'Servera kall eller ljummen, som den är eller med mjölk eller grädde.',steps:['Lägg katrinplommon i en kastrull med vatten.','Låt sjuda tills frukten är mjuk.','Smaka av med lite socker om det behövs.','Låt svalna före servering om du vill äta den kall.']});
addRecipe({id:'katrinplommonsuffle',name:'Katrinplommonsufflé – gammaldags',emoji:'🟣',time:40,budget:'low',tags:[...dessertTags,'katrinplommon','sufflé','mandel','billigt','gammaldags efterrätt'],plants:1,ingredients:['ca 200 g mjuka kärnfria katrinplommon','4–5 äggvitor','2–3 msk strösocker','ca 10 sötmandlar, grovt hackade','smör till formen'],leftovers:['katrinplommon'],tip:'Den klassiska varianten är enklare än många moderna suffléer: katrinplommon, vispad äggvita, lite socker och hackad mandel. Är katrinplommonen redan mjuka behöver de inte kokas.',serving:'Servera varm direkt ur ugnen, gärna med kall tunn eller ovispad grädde.',steps:['Sätt ugnen på 175 grader och smörj en suffléform med raka kanter.','Om katrinplommonen är mjuka: hacka dem direkt. Är de mycket torra kan de först blötläggas kort och sedan torkas av.','Hacka mandeln grovt.','Vispa äggvitorna till ett fast skum. Tillsätt sockret lite i taget och fortsätt vispa tills skummet är blankt och toppigt.','Vänd försiktigt ner hackad mandel och katrinplommon i äggvitesmeten.','Fördela smeten i formen.','Grädda cirka 30 minuter, tills sufflén har rest sig och fått fin färg. Öppna helst inte ugnsluckan under gräddningen.','Servera direkt, gärna med kall rinnande grädde.']});
addRecipe({id:'brodpudding-radda-brodet',name:'Enkel brödpudding – rädda brödet',emoji:'🍞',time:45,budget:'low',tags:[...dessertTags,'bröd','rädda maten','billigt','rester'],plants:0,ingredients:['torrt eller överblivet bröd','mjölk','ägg','lite socker','vaniljsocker eller kanel','russin – valfritt'],leftovers:['bröd','mjölk'],tip:'Ett gammalt sätt att göra efterrätt av bröd som annars riskerar att bli över.',serving:'Servera ljummen eller kall, gärna med lite grädde, mjölk, sylt eller frukt.',steps:['Skär brödet i mindre bitar.','Låt det suga upp en blandning av mjölk, ägg och lite socker.','Smaksätt med vanilj eller kanel och lägg i russin om du vill.','Häll i smord form och grädda tills puddingen stannat och fått färg.']});

// Kataloginformation används av inventering och kommande städning.
window.malixRecipeCatalog=recipes;
window.malixRecipeCatalogInfo={totalLoaded:recipes.length,uniqueRecipes:new Set(recipes.map(r=>r.id)).size,duplicateIds:[]};
