(() => {
  if (typeof recipes === 'undefined' || !Array.isArray(recipes)) return;
  const add = (recipe, first = false) => {
    if (recipes.some(r => r.id === recipe.id)) return;
    first ? recipes.unshift(recipe) : recipes.push(recipe);
  };

  add({id:'tomatsas-malix',name:'Tomatsås à la Malix',emoji:'🍅',time:30,budget:'low',tags:['vegetariskt','budget','tillbehör','ta-vad-du-har','pizza','varma mackor'],ingredients:['krossade tomater','buljongtärning','vitlök','basilika','rikligt med svartpeppar','grädde valfritt','vatten vid behov','majsstärkelse eller mjöl till toppredning valfritt'],leftovers:['grillade grönsaker','grillad kyckling','grillat kött','grillad korv'],plants:3,tip:'🍅 En grundsås med många användningar: till pasta, pizza och varma mackor. Rädda också grillrester genom att skära ner dem och låta dem puttra i tomatsåsen. Servera med pasta eller ris – blanda med tomatsås och du är nästan hemma i Italien.',steps:['Häll krossade tomater i en kastrull och tillsätt buljongtärning, vitlök, basilika och rikligt med svartpeppar.','Låt såsen koka och utveckla smak en stund.','Vill du ha en rundare och krämigare sås kan du tillsätta lite grädde, men den går bra att utesluta.','Späd med lite vatten om såsen blir för tjock.','Om du vill ha den tjockare, avsluta med en liten toppredning av majsstärkelse eller mjöl utrört i kallt vatten.','Använd som pastasås, pizzasås eller bred på varma mackor före topping och gratinering.']}, true);

  add({id:'chalaw-afghanskt-ris',name:'Chalaw – afghanskt inspirerat ris',emoji:'🍚',time:35,budget:'low',tags:['vegetariskt','budget','tillbehör','grundrecept'],ingredients:['basmatiris','rikligt med vatten','salt'],leftovers:['ris'],tip:'Variera riset om du vill: gurkmeja ger färg och mild smak, curry ger tydligare kryddning. Du kan också prova lite spiskummin, kardemumma eller saffran. Kryddorna är variationer – de behövs inte för grundreceptet.',steps:['Skölj basmatiriset tills vattnet blir klarare.','Koka riset i rikligt med saltat vatten tills det är nästan färdigt.','Häll av vattnet ordentligt.','Lägg tillbaka riset i kastrullen och låt det ånga färdigt under lock på mycket låg värme eller med värmen avstängd.','Lufta försiktigt med en gaffel före servering.']});
  const stroganoff=recipes.find(r=>/korvstroganoff/i.test(r.name||''));
  if(stroganoff&&!String(stroganoff.tip||'').includes('chalaw')) stroganoff.tip=(stroganoff.tip?stroganoff.tip+' ':'')+'Servera med vanligt ris, chalaw eller kryddat chalaw. Kryddat chalaw kan varieras med till exempel gurkmeja, curry, spiskummin, kardemumma eller saffran.';

  add({id:'tacos-blandfars',name:'Vanliga tacos med blandfärs',emoji:'🌮',time:30,budget:'mid',tags:['familj','köttfärs','snabbt'],ingredients:['500 g blandfärs','tacokrydda','tacoskal','crème fraîche eller gräddfil','tomat','gurka','gul lök','sallad','majs','pepperoni','tacosås','riven ost'],leftovers:['tacofärs','grönsaker','riven ost'],plants:6,tip:'Ställ fram allt i små skålar så kan var och en bygga sin taco med de tillbehör den tycker om. Det som blir över kan bli tacotallrik eller lunch nästa dag.',steps:['Bryn blandfärsen tills den är helt genomstekt.','Tillsätt tacokrydda och den mängd vatten som behövs enligt kryddningen. Låt puttra några minuter.','Hacka tomat, gurka, lök och sallad. Ställ fram majs, pepperoni, tacosås, ost och crème fraîche eller gräddfil.','Värm tacoskalen och låt var och en fylla sin taco med det den tycker om.']});

  add({id:'popupbrod',name:'Glutenfritt popup-bröd',emoji:'🥖',time:35,budget:'low',tags:['vegetariskt','bröd','tillbehör','soppa','gryta','glutenfritt'],ingredients:['3 ägg','3 dl mjölk','1 nypa salt','150 g glutenfri mjölmix','40 g smält smör','1 tsk fiberhusk – kan uteslutas'],leftovers:[],plants:1,tip:'Påminner om Yorkshire pudding men bakas i muffinsformar. Gott till soppa, gryta, chili con carne, kålpudding eller som ett luftigare bröd till sallad.',serving:'Servera gärna varmt till soppa eller gryta. Det passar också till chili con carne och kålpudding, där brödet kan suga upp sås eller sky.',steps:['Sätt ugnen på 220 grader.','Vispa ihop ägg, mjölk och salt.','Tillsätt glutenfri mjölmix och fiberhusk. Vispa till en slät smet.','Låt smeten vila 5–10 minuter.','Smält smöret och fördela det i muffinsformar.','Häll i smeten till cirka hälften av formarna.','Grädda mitt i ugnen i cirka 20–25 minuter tills bröden puffat upp och fått fin färg.']});

  add({id:'pannkakor-grund',name:'Pannkakor – grundrecept',emoji:'🥞',time:30,budget:'low',tags:['pannkaka','vegetariskt','vardag'],plants:1,ingredients:['ägg','mjölk','vetemjöl','lite salt','smör eller annat matfett till stekning'],leftovers:[],tip:'Låt gärna smeten stå en liten stund om du har tid. Servera sött eller matigt efter vad som finns hemma.',serving:'Sylt och bär passar fint, men pannkakor kan också fyllas med matiga rester.',swaps:'Behöver du glutenfritt, använd en glutenfri pannkaksmix/mjölmix avsedd för pannkakor och följ mängden för just den produkten.',steps:['Vispa ihop mjöl och en del av mjölken till en slät smet.','Vispa ner resten av mjölken, äggen och saltet.','Stek tunna pannkakor i lite matfett.']});
  add({id:'ugnsomelett-malix',name:'Fluffig ugnsomelett',emoji:'🍳',time:40,budget:'low',tags:['omelett','ugn','glutenfritt alternativ','vardag'],plants:0,ingredients:['ägg','mjölk','lite salt och peppar','lite Maizena/majsstärkelse för glutenfri redning – eller vetemjöl om du tål gluten','smör till formen'],leftovers:[],tip:'Varm mjölk och en lätt redning ger en mjuk och luftig ugnsomelett. Lägg gärna till en stuvning eller fyllning efter vad du har hemma.',serving:'Kan serveras som den är eller med exempelvis svamp-, räk- eller grönsaksstuvning och bröd.',swaps:'För glutenfri variant: red med majsstärkelse. Om gluten fungerar för dig kan du använda vanligt vetemjöl som redning.',steps:['Sätt ugnen på cirka 200 grader och smörj en ugnsform.','Värm mjölken. Gör en liten slät redning av Maizena/majsstärkelse och lite kall mjölk, eller använd vetemjöl om du tål gluten. Vispa ner redningen i den varma mjölken och låt den tjockna lätt.','Låt mjölkblandningen svalna något. Vispa upp äggen försiktigt med salt och peppar.','Vispa ner mjölkblandningen i äggen.','Häll i formen och grädda tills omeletten har stannat och blivit luftig.']});

  [
    {id:'carbonara',name:'Pasta carbonara',emoji:'🍝',time:25,budget:'medium',tags:['pasta','snabbt','vardag'],plants:1,ingredients:['pasta','bacon eller pancetta','ägg','parmesan','svartpeppar'],leftovers:['bacon'],tip:'Spara lite pastavatten och använd för att få såsen blank och krämig.',serving:'Gott med extra parmesan, vitt bröd och något grönt vid sidan.',swaps:'Bacon kan bytas mot annan rökt/skivad rest som passar. Parmesan kan bytas mot annan lagrad hårdost.',steps:['Koka pastan.','Stek bacon/pancetta.','Vispa ihop ägg, parmesan och svartpeppar.','Vänd ner varm pasta och bacon. Ta från värmen och rör ner äggblandningen. Späd försiktigt med lite pastavatten.']},
    {id:'pastamexicana',name:'Pasta Mexicana',emoji:'🌶️',time:35,budget:'medium',tags:['pasta','mexicana','vardag','kött'],plants:5,ingredients:['pasta','Tomatsås à la Malix eller annan tomatsås','fläskkött eller nötkött i bitar','lök i bitar','paprika i bitar','vitlök','chili','svartpeppar','gärna buljong','majs – om du vill'],leftovers:['kött','paprika','majs','tomatsås'],tip:'Stek kött, lök och paprika ordentligt först. Tomatsåsen binder ihop rätten och chili, vitlök, svartpeppar och lite buljong ger mer smak.',serving:'Parmesan, vitt bröd eller popup-bröd kan passa till om du vill.',swaps:'Välj fläsk eller nöt efter vad du har. Majs är valfritt. Tomatsås à la Malix fungerar fint som bas.',steps:['Koka pastan.','Skär köttet i bitar och bryn det.','Lägg i lök och paprika i bitar och stek vidare. Tillsätt rikligt med vitlök, chili och svartpeppar.','Häll på tomatsåsen och smaka gärna upp med lite buljong. Lägg i majs om du vill.','Låt allt puttra ihop och servera med pastan.']},
    {id:'fruttidimare',name:'Pasta Frutti del mare',emoji:'🦐',time:30,budget:'medium',tags:['pasta','fisk','skaldjur','frutti del mare'],plants:3,ingredients:['pasta','blandade skaldjur','vitlök','tomat','olivolja','persilja','citron'],leftovers:[],tip:'Skaldjuren behöver bara bli varma så att de inte tillagas för länge.',serving:'Citron, persilja, vitt bröd och en enkel sallad passar bra till.',swaps:'Använd den blandning av skaldjur du har. Tomat kan vara färsk eller från burk.',steps:['Koka pastan.','Fräs vitlök försiktigt i olja och tillsätt tomat.','Vänd ner skaldjuren mot slutet.','Blanda med pasta och avsluta med persilja och citron.']},
    {id:'pastamurklor',name:'Pasta à la murklor',emoji:'🍄',time:30,budget:'medium',tags:['pasta','svamp','krämigt'],plants:2,ingredients:['pasta','förvällda/tillagade murklor','lök','grädde','parmesan','svartpeppar'],leftovers:['svamp'],tip:'Använd endast murklor som är korrekt förberedda för matlagning.',serving:'Parmesan och något grönt vid sidan passar bra. Stekt grönkål eller svartkål kan vara ett alternativ.',swaps:'Murklor kan bytas mot annan matsvamp.',steps:['Koka pastan.','Fräs lök och de färdigförberedda murklorna.','Tillsätt grädde och låt såsen gå ihop.','Vänd ner pastan och avsluta med parmesan och svartpeppar.']},
    {id:'pastacapri',name:'Pasta Capri',emoji:'🍝',time:30,budget:'medium',tags:['pasta','vardag','fläskkotlett'],plants:3,ingredients:['pasta','benfri kotlett','lök','svartpeppar','basilika','oregano','Tomatsås à la Malix eller grädde'],leftovers:['kotlett','tomatsås'],tip:'Pasta Capri kan göras på två sätt: tomatvarianten med Tomatsås à la Malix eller en enkel krämig variant med grädde.',serving:'Servera som den är eller med parmesan, vitt bröd eller något grönt vid sidan.',swaps:'Välj Tomatsås à la Malix för en tomatigare rätt eller grädde för en mildare, krämig variant.',steps:['Koka pastan.','Skär den benfria kotletten i mindre bitar eller strimlor och stek den.','Tillsätt lök och låt den mjukna. Krydda med svartpeppar, basilika och oregano.','Välj Tomatsås à la Malix eller grädde och låt såsen gå ihop.','Vänd ihop med pastan och servera.']},
    {id:'kasslergorgonzolapasta',name:'Pasta med kassler och gorgonzola',emoji:'🧀',time:30,budget:'medium',tags:['pasta','krämigt','vardag'],plants:2,ingredients:['pasta','kassler','lök','gorgonzola','grädde','svartpeppar'],leftovers:['kassler'],tip:'Smaka innan du saltar – både kassler och gorgonzola ger mycket sälta.',serving:'Något grönt passar bra till, till exempel stekt grönkål eller svartkål.',swaps:'Kassler kan bytas mot en lämplig köttrest. Gorgonzola kan bytas mot annan smakrik ost.',steps:['Koka pastan.','Fräs lök och kassler.','Tillsätt grädde och gorgonzola och låt osten smälta.','Vänd ner pastan och krydda med svartpeppar.']},
    {id:'pastatomatsasmalix',name:'Pasta med Tomatsås à la Malix',emoji:'🍅',time:25,budget:'low',tags:['pasta','rester','billigt','vegetariskt'],plants:5,ingredients:['pasta','Tomatsås à la Malix'],leftovers:['grillrester','tonfisk','grönsaker'],tip:'Tomatsåsen och pasta räcker som rätt. Vill du förändra den kan du använda det som redan finns hemma.',serving:'Vitt bröd, popup-bröd eller parmesan kan passa till.',swaps:'Rör ner tonfisk mot slutet, eller använd grillrester, svamp, paprika, zucchini eller andra grönsaksrester. Lite grädde ger en mildare och krämigare sås.',steps:['Koka pastan.','Värm Tomatsås à la Malix.','Välj om du vill äta den som den är eller lägga till tonfisk, grillrester eller grönsaker.','Blanda med pastan och servera.']},
    {id:'stektkalbacon',name:'Stekt grönkål eller svartkål med bacon',emoji:'🥬',time:20,budget:'low',tags:['tillbehör','grönkål','svartkål','rester'],plants:1,ingredients:['grönkål eller svartkål','bacon','lite grädde – valfritt','svartpeppar'],leftovers:['bacon','grönkål','svartkål'],tip:'Lite grädde gör kålen mjukare och krämigare.',serving:'Passar som varmt tillbehör till många pastarätter och andra vardagsrätter.',swaps:'Grönkål och svartkål kan bytas mot varandra. Bacon kan uteslutas. Lite parmesan eller vitlök kan läggas till om du vill.',steps:['Strimla kålen.','Stek bacon och låt kålen steka med tills den mjuknar.','Tillsätt eventuellt lite grädde och låt den koka in.','Avsluta med svartpeppar.']},
    {id:'makaronpuddingpizza',name:'Restpizza på makaronpudding',emoji:'🍕',time:25,budget:'low',tags:['rester','pizza','makaronpudding','rädda maten'],plants:2,ingredients:['kall makaronpudding','lite tomatsås – valfritt','skinka','lök','det du har hemma','rikligt med riven ost'],leftovers:['makaronpudding','skinka','ost','grönsaker'],tip:'Här är makaronpuddingen själva pizzabottnen – ett sätt att göra en helt ny rätt av rester.',serving:'Servera som den är eller med något grönt vid sidan.',swaps:'Skinka och lök är bara en början. Använd till exempel svamp, paprika, tomat, majs, grillrester eller andra pizzavänliga rester. Toppa ordentligt med ost.',steps:['Sätt ugnen på cirka 225 grader.','Lägg kall makaronpudding i en smord form eller på bakplåtspapper och tryck ut den till en stadig, jämn botten.','Bred eventuellt på lite tomatsås.','Lägg på skinka, lök och det du har hemma.','Täck med rikligt med ost.','Grädda tills allt är genomvarmt och osten har smält och fått färg.']}
  ].forEach(add);

  if (typeof renderBank === 'function') renderBank();
})();