(() => {
 const KEY='malix-self-care-v1';
 const main=document.querySelector('main');if(!main)return;
 const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
 function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
 function show(id){document.querySelectorAll('main > .view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id)?.classList.add('active-view');if(id==='careReflection')renderHistory();if(id==='careKind')renderKindHistory();window.scrollTo({top:0,behavior:'smooth'})}
 function ensure(id){let s=document.querySelector('#'+id);if(!s){s=document.createElement('section');s.id=id;s.className='view';main.appendChild(s)}return s}
 function group(id,title,lead,items){const s=ensure(id);s.innerHTML=`<button type="button" class="back" data-care-group-back>← Ta hand om mig</button><p class="eyebrow">En sak i taget</p><h2>${title}</h2><p class="subtitle">${lead}</p><div class="choice-grid">${items.map(x=>`<button type="button" class="choice-card" data-care="${x[0]}"><span>${x[1]}</span><strong>${x[2]}</strong><small>${x[3]}</small></button>`).join('')}</div>`;return s}
 function hub(){const s=ensure('careHub');s.innerHTML=`<button type="button" class="back" data-calm-home>← Hem</button><p class="eyebrow">En sak i taget</p><h2>🌿 Ta hand om mig</h2><p class="subtitle">Vad skulle vara hjälpsamt för dig just nu?</p><div class="choice-grid"><button type="button" class="choice-card" data-care="careMoveHub"><span>🚶</span><strong>Rörelse</strong><small>Träning eller vardagsrörelse.</small></button><button type="button" class="choice-card" data-care="careRecoverHub"><span>🌤️</span><strong>Återhämtning</strong><small>Frisk luft, vila och stillhet.</small></button><button type="button" class="choice-card" data-calm-open="compassHub"><span>🟢 🔵 🔴</span><strong>Min inre kompass</strong><small>Compassion, cirklar och reflektion.</small></button><button type="button" class="choice-card" data-care="careMindHub"><span>💚</span><strong>Mjuka tankar & reflektion</strong><small>Stanna upp och ta med dig det du märker.</small></button></div><section class="panel calm" style="margin-top:18px"><p><strong>Vet du inte vad du behöver?</strong></p><p class="note">Du behöver inte lösa det först. Välj den ruta som känns minst krävande – eller lämna det här för stunden.</p></section>`;return s}
 function section(id,title,lead,body){const s=ensure(id);s.innerHTML=`<button class="back" type="button" data-care-back>← Tillbaka</button><p class="eyebrow">En sak i taget</p><h2>${title}</h2><p class="subtitle">${lead}</p>${body}`;return s}
 const activity=(id,title,lead,examples)=>section(id,title,lead,`<section class="panel calm"><h3>Välj det som passar</h3><div class="chips">${examples.map(x=>`<button type="button" data-activity="${esc(x)}">${esc(x)}</button>`).join('')}</div><label style="display:block;margin-top:14px">Eller skriv själv<input id="${id}Other" placeholder="Vad gjorde du?"></label><button class="primary" data-save-activity="${id}" type="button">Spara min stund</button><p class="status" data-care-status></p></section><section class="panel calm" style="margin-top:16px"><p class="note">Det behöver inte bli mer bara för att du började. Det du gjorde räknas.</p></section>`);
 function build(){
   hub();
   group('careMoveHub','🚶 Rörelse','Välj bara vilken sorts rörelse du vill tänka på.',[['careTraining','🏃','Träning','Promenad, cykling, simning eller annan planerad rörelse.'],['careEveryday','🚶','Vardagsrörelse','Trädgård, städning, trappor och annat som kroppen gör i vardagen.']]);
   group('careRecoverHub','🌤️ Återhämtning','Återhämtning behöver inte vara en prestation.',[['careAir','🌤️','Frisk luft','En stund ute räknas även utan motion.'],['careQuiet','🧘','Stilla stund','Sitt, läs, lyssna, vila eller bara var en stund.']]);
   group('careMindHub','💚 Mjuka tankar & reflektion','Stanna upp utan att behöva analysera allt.',[['careKind','💚','Mjuka tankar','Möt dig själv lite vänligare just nu.'],['careReflection','🌙','Reflektion','Vad gjorde jag för mig själv och vad vill jag ta med mig?']]);
   activity('careTraining','🏃 Träning','Planerad rörelse får vara på din nivå idag.',['Promenad','Cykling','Simning','Träning hemma','Gym','Annat']);
   activity('careEveryday','🚶 Vardagsrörelse','Vardagen räknas också.',['Trädgårdsarbete','Städning','Gå till affären','Trappor','Bära och fixa','Lek och aktivitet']);
   activity('careAir','🌤️ Frisk luft','Du behöver inte motionera för att en stund ute ska räknas.',['Sitta ute','Trädgården','Skogen','Promenad','Balkong eller altan','Öppet fönster en stund']);
   activity('careQuiet','🧘 Stilla stund','En stund utan krav kan också vara något du gör för dig själv.',['Sitta i tystnad','Läsa','Lyssna på bok eller musik','Vila','Titta på himlen','Dricka något varmt i lugn och ro']);
   section('careKind','💚 Mjuka tankar','Compassion handlar inte om att låtsas att allt är lätt.',`<section class="panel calm"><h3>Vad skulle du säga till någon du tycker om?</h3><textarea id="kindFriend" rows="3" placeholder="Jag skulle säga …"></textarea><h3 style="margin-top:18px">Kan något av det få gälla även mig?</h3><textarea id="kindMe" rows="3" placeholder="En mjukare tanke till mig själv …"></textarea><button class="primary" id="saveKind" type="button">Spara min mjuka tanke</button><p class="status" data-care-status></p></section><div id="kindHistory" class="recipe-grid" style="margin-top:18px"></div>`);
   section('careReflection','🌙 Reflektion','Stanna upp och se det du faktiskt gjorde för dig själv.',`<section class="panel calm"><label>Vad gjorde jag för mig själv idag?<textarea id="careDid" rows="2"></textarea></label><label>Hur känns det nu?<select id="careFeel"><option>Bättre</option><option>Ungefär samma</option><option>Tröttare</option><option>Vet inte</option></select></label><label>Vad vill jag ta med mig?<textarea id="careTake" rows="2"></textarea></label><button class="primary" id="saveCareReflection" type="button">Spara reflektionen</button><p class="status" data-care-status></p></section><div id="careHistory" class="recipe-grid" style="margin-top:18px"></div>`);
   wire();renderKindHistory();
 }
 function add(type,text,extra=''){const a=load();a.unshift({id:Date.now(),date:new Date().toISOString(),type,text,extra});save(a)}
 function parentFor(id){if(['careTraining','careEveryday'].includes(id))return'careMoveHub';if(['careAir','careQuiet'].includes(id))return'careRecoverHub';if(['careKind','careReflection'].includes(id))return'careMindHub';return'careHub'}
 function wire(){
   main.addEventListener('click',e=>{
     const groupBack=e.target.closest('[data-care-group-back]');if(groupBack){e.preventDefault();e.stopPropagation();show('careHub');return}
     const back=e.target.closest('[data-care-back]');if(back){e.preventDefault();e.stopPropagation();show(parentFor(back.closest('.view')?.id));return}
     const nav=e.target.closest('[data-care]');if(nav){e.preventDefault();e.stopPropagation();show(nav.dataset.care);return}
     const choice=e.target.closest('#careTraining [data-activity],#careEveryday [data-activity],#careAir [data-activity],#careQuiet [data-activity]');if(choice){e.preventDefault();e.stopPropagation();const sec=choice.closest('.view');sec.dataset.chosen=choice.dataset.activity||choice.textContent.trim();sec.querySelectorAll('[data-activity]').forEach(x=>x.classList.toggle('selected',x===choice));const status=sec.querySelector('[data-care-status]');if(status)status.textContent=`Valt: ${sec.dataset.chosen}`;return}
     const del=e.target.closest('[data-kind-delete]');if(del){e.preventDefault();e.stopPropagation();const id=del.dataset.kindDelete;save(load().filter(x=>String(x.id)!==String(id)));renderKindHistory();return}
     const b=e.target.closest('[data-save-activity]');if(b){e.preventDefault();e.stopPropagation();const sec=b.closest('.view'),chosen=sec.dataset.chosen||'',other=sec.querySelector('input')?.value.trim()||'',text=other||chosen,status=sec.querySelector('[data-care-status]');if(!text){if(status)status.textContent='Välj en aktivitet eller skriv vad du gjorde.';return}add(sec.querySelector('h2').textContent,text);sec.dataset.chosen='';sec.querySelectorAll('[data-activity]').forEach(x=>x.classList.remove('selected'));if(sec.querySelector('input'))sec.querySelector('input').value='';if(status)status.textContent='Sparat. Det du gjorde räknas.';return}
   },true);
   document.querySelector('#saveKind').onclick=()=>{const f=document.querySelector('#kindFriend').value.trim(),m=document.querySelector('#kindMe').value.trim();if(!f&&!m)return;add('💚 Mjuka tankar',m||f,f);document.querySelector('#careKind [data-care-status]').textContent='Sparat. Din mjuka tanke finns nedanför.';renderKindHistory()};
   document.querySelector('#saveCareReflection').onclick=()=>{const d=document.querySelector('#careDid').value.trim(),f=document.querySelector('#careFeel').value,t=document.querySelector('#careTake').value.trim();add('🌙 Reflektion',d,`${f}${t?' · '+t:''}`);document.querySelector('#careReflection [data-care-status]').textContent='Reflektionen är sparad.';renderHistory()};
 }
 function renderKindHistory(){const box=document.querySelector('#kindHistory');if(!box)return;const a=load().filter(x=>x.type==='💚 Mjuka tankar').slice(0,20);box.innerHTML=a.length?`<h3>💚 Mina mjuka tankar</h3>`+a.map(x=>`<article class="recipe-card"><p class="eyebrow">${new Date(x.date).toLocaleDateString('sv-SE')}</p>${x.extra?`<p class="note"><strong>Till någon jag tycker om:</strong><br>${esc(x.extra)}</p>`:''}<p><strong>Det som får gälla även mig:</strong><br>${esc(x.text)}</p><button type="button" class="secondary" data-kind-delete="${x.id}">Ta bort</button></article>`).join(''):'<p class="note">När du sparar en mjuk tanke kan du se den här.</p>'}
 function renderHistory(){const box=document.querySelector('#careHistory');if(!box)return;const a=load().slice(0,20);box.innerHTML=a.length?`<h3>Det jag gjort för mig själv</h3>`+a.map(x=>`<article class="recipe-card"><p class="eyebrow">${new Date(x.date).toLocaleDateString('sv-SE')}</p><h3>${esc(x.type)}</h3><p>${esc(x.text)}</p>${x.extra?`<p class="note">${esc(x.extra)}</p>`:''}</article>`).join(''):'<p class="note">Här kommer du kunna se dina sparade stunder och reflektioner.</p>'}
 build();window.malixOpenCare=()=>show('careHub');
})();