(() => {
 const KEY='malix-smart-kitchen-v1';
 const load=()=>{try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return {stock:Array.isArray(s.stock)?s.stock:[],shopping:Array.isArray(s.shopping)?s.shopping:[]}}catch{return {stock:[],shopping:[]}}};
 const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
 const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(kg|g|dl|ml|st|stycken|paket|burk|burkar)\b/g,' ').replace(/\d+[\d,.]*/g,' ').replace(/[^a-zåäö ]/gi,' ').replace(/\s+/g,' ').trim();
 const words=s=>norm(s).split(' ').filter(w=>w.length>2&&!['eller','valfri','valfria','garna','lite','eventuellt','med','och','for'].includes(w));
 const recipeList=()=>typeof recipes!=='undefined'?recipes:[];
 const stockMatches=(stockItem,ingredient)=>{const a=words(stockItem),b=words(ingredient);return a.some(x=>b.some(y=>x.includes(y)||y.includes(x)))};
 function addShopping(st,item,source=''){const clean=String(item||'').trim();if(!clean)return;if(!st.shopping.some(x=>norm(x.item)===norm(clean)&&!x.done))st.shopping.push({id:Date.now()+Math.random(),item:clean,done:false,source});}
 function recipeScore(r,stock){const ing=r.ingredients||[];const matches=ing.filter(i=>stock.some(s=>stockMatches(s.item,i))).length;return {matches,total:ing.length,ratio:ing.length?matches/ing.length:0};}
 function parseAmount(s){const m=String(s||'').toLowerCase().replace(',','.').match(/(\d+(?:\.\d+)?)\s*(kg|g|dl|ml|st|stycken|paket)?/);if(!m)return null;let n=Number(m[1]),u=m[2]||'';if(u==='kg'){n*=1000;u='g'}if(u==='dl'){n*=100;u='ml'}if(u==='stycken')u='st';return {n,u}}
 function formatAmount(a){if(!a)return'';if(a.u==='g'&&a.n>=1000&&a.n%1000===0)return `${a.n/1000} kg`;if(a.u==='ml'&&a.n>=1000&&a.n%1000===0)return `${a.n/1000} l`;return `${Math.round(a.n*100)/100} ${a.u}`.trim()}
 function askedUsage(stockItem,ingredient){const fromRecipe=parseAmount(ingredient);if(fromRecipe&&fromRecipe.u)return fromRecipe;const current=parseAmount(stockItem.amount);if(!current||!current.u)return null;const answer=prompt(`Hur mycket ${stockItem.item.toLowerCase()} använde du till receptet?\nDu har ${stockItem.amount} hemma.`,current.u==='g'?'500 g':current.u==='ml'?'5 dl':current.u==='st'?'1 st':`1 ${current.u}`);if(answer===null)return {cancel:true};return parseAmount(answer)}
 function subtract(stockItem,used){const current=parseAmount(stockItem.amount);if(!current||!used||!current.u||!used.u||current.u!==used.u)return {known:false,depleted:false};const remain=Math.max(0,current.n-used.n);stockItem.amount=formatAmount({n:remain,u:current.u});return {known:true,depleted:remain<=0,remain};}
 function addHomeCard(){const grid=document.querySelector('#home .choice-grid');if(!grid||document.querySelector('[data-open="smartKitchen"]'))return;const b=document.createElement('button');b.className='choice-card';b.dataset.open='smartKitchen';b.innerHTML='<span>🧊</span><strong>Mitt kök</strong><small>Vad kan jag laga av det jag har? Kyl, frys, skafferi och handlingslista.</small><span class="tier-tag tier-plus">PLUS</span>';grid.appendChild(b);b.addEventListener('click',()=>{show('smartKitchen');render()});}
 function addView(){if(document.querySelector('#smartKitchen'))return;const main=document.querySelector('main');const s=document.createElement('section');s.id='smartKitchen';s.className='view';s.innerHTML=`<button class="back" data-open="home">← Tillbaka</button><p class="eyebrow">PLUS</p><h2>🧊 Mitt kök</h2><p>Appen jämför det du har hemma med recepten, räknar ner det du använder och lägger sådant som tar slut på handlingslistan.</p><section class="panel calm"><h3>🍲 Vad kan jag laga av det jag har?</h3><p>Ju fler ingredienser du redan har hemma, desto högre hamnar receptet.</p><div id="cookFromHome" class="recipe-grid"></div></section><div class="plan-grid"><section class="panel"><h3>🧊 Kyl, frys & skafferi</h3><form id="stockForm" class="record-form"><label>Vara<input name="item" placeholder="t.ex. köttfärs, socker, mjölk" required></label><label>Var finns den?<select name="place"><option>Kyl</option><option>Frys</option><option>Skafferi</option></select></label><label>Mängd<input name="amount" placeholder="t.ex. 1 kg, 2 kg, 6 st" required></label><button class="primary">Lägg till hemma</button></form><div id="stockList"></div></section><section class="panel"><h3>🛒 Handlingslista</h3><form id="shoppingForm" class="record-form"><label>Lägg till något<input name="item" placeholder="t.ex. kaffe eller toalettpapper" required></label><button class="primary">Lägg till</button></form><div id="shoppingList"></div></section></div><section class="panel calm"><h3>💰 När något är billigt</h3><div class="chips"><button type="button" data-buy-tip="freeze">Köp extra & frys in</button><button type="button" data-buy-tip="two">Köp extra & laga två rätter</button><button type="button" data-buy-tip="one">Köp bara till en rätt</button></div><p id="buyTip" class="note">Välj ett alternativ när du planerar ett bra köp.</p></section>`;main.appendChild(s);s.querySelector('.back').addEventListener('click',()=>show('home'));
 s.querySelector('#stockForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();const item=d.get('item').trim(),existing=st.stock.find(x=>norm(x.item)===norm(item)&&x.place===d.get('place'));if(existing){existing.amount=d.get('amount').trim()}else st.stock.push({id:Date.now(),item,place:d.get('place'),amount:d.get('amount').trim()});save(st);e.target.reset();render()});
 s.querySelector('#shoppingForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();addShopping(st,d.get('item').trim());save(st);e.target.reset();render()});
 s.querySelectorAll('[data-buy-tip]').forEach(b=>b.addEventListener('click',()=>{const t={freeze:'Köp extra bara när du vet att det går åt. Lägg den extra mängden direkt i frysen och skriv in den i Mitt kök.',two:'Välj en råvara och låt appen hitta två recept som använder den. Då blir ett bra pris två planerade måltider.',one:'Om du inte vet vad resten ska bli är det ofta bättre att köpa till en rätt.'};s.querySelector('#buyTip').textContent=t[b.dataset.buyTip]}));}
 function addRecipeToShopping(recipe){const st=load(),missing=(recipe.ingredients||[]).filter(i=>!st.stock.some(x=>stockMatches(x.item,i)));missing.forEach(i=>addShopping(st,i,recipe.name));save(st);render();alert(missing.length?`${missing.length} saker som saknas för ${recipe.name} lades i handlingslistan.`:`Du verkar redan ha ingredienserna till ${recipe.name} hemma.`)}
 function cookRecipe(recipe){const st=load();const usedNames=[],depleted=[],missing=[];for(const ing of (recipe.ingredients||[])){const idx=st.stock.findIndex(x=>stockMatches(x.item,ing));if(idx<0){missing.push(ing);continue}const item=st.stock[idx],used=askedUsage(item,ing);if(used&&used.cancel)return;const result=subtract(item,used);if(result.known){usedNames.push(`${item.item}: ${formatAmount(used)} använt`);if(result.depleted){depleted.push(item.item);addShopping(st,item.item,`Tog slut när du lagade ${recipe.name}`);st.stock.splice(idx,1)}}else{const takeAll=confirm(`Jag kan inte räkna mängden för ${item.item}.\nVill du markera att den tog slut när du lagade ${recipe.name}?`);if(takeAll){depleted.push(item.item);addShopping(st,item.item,`Tog slut när du lagade ${recipe.name}`);st.stock.splice(idx,1)}}}
 missing.forEach(i=>addShopping(st,i,`Saknas till ${recipe.name}`));save(st);render();const left=st.stock.filter(x=>usedNames.some(u=>u.toLowerCase().startsWith(x.item.toLowerCase()+':'))).map(x=>`${x.item}: ${x.amount} kvar`);alert([`${recipe.name} är markerad som lagad.`,left.length?`Kvar hemma:\n${left.join('\n')}`:'',depleted.length?`Tog slut och lades på handlingslistan:\n${depleted.join('\n')}`:'',missing.length?`Saknades och lades på handlingslistan:\n${missing.join('\n')}`:''].filter(Boolean).join('\n\n'))}
 function renderSuggestions(st){const e=document.querySelector('#cookFromHome');if(!e)return;if(!st.stock.length){e.innerHTML='<div class="empty">Lägg in några saker i kyl, frys eller skafferi så visas recept som passar.</div>';return}const ranked=recipeList().map(r=>({r,...recipeScore(r,st.stock)})).filter(x=>x.matches>0).sort((a,b)=>b.ratio-a.ratio||b.matches-a.matches).slice(0,8);e.innerHTML=ranked.length?ranked.map(x=>`<article class="recipe-card"><h3>${x.r.emoji||'🍲'} ${x.r.name}</h3><p><strong>${x.matches} av ${x.total}</strong> ingredienser matchar det du har hemma.</p><div class="chips"><button type="button" class="primary" data-k-open="${x.r.id}">Öppna recept</button><button type="button" class="secondary" data-k-shop="${x.r.id}">Lägg det som saknas i handlingslistan</button><button type="button" class="secondary" data-k-cook="${x.r.id}">Jag lagade detta</button></div></article>`).join(''):'<div class="empty">Inget recept matchar ännu. Lägg till fler råvaror hemma.</div>';e.querySelectorAll('[data-k-open]').forEach(b=>b.onclick=()=>window.openRecipe?.(b.dataset.kOpen));e.querySelectorAll('[data-k-shop]').forEach(b=>b.onclick=()=>{const r=recipeList().find(x=>String(x.id)===b.dataset.kShop);if(r)addRecipeToShopping(r)});e.querySelectorAll('[data-k-cook]').forEach(b=>b.onclick=()=>{const r=recipeList().find(x=>String(x.id)===b.dataset.kCook);if(r&&confirm(`Markera ${r.name} som lagad? Det du använder räknas ner från Mitt kök. Bara sådant som tar slut läggs på handlingslistan.`))cookRecipe(r)});}
 function render(){const st=load(),stock=document.querySelector('#stockList'),shop=document.querySelector('#shoppingList');renderSuggestions(st);if(stock){stock.innerHTML=st.stock.length?st.stock.map(x=>`<div class="history-meal"><strong>${x.item}</strong><small>${x.place} · ${x.amount}</small><button class="secondary" data-stock-use="${x.id}" type="button">Ta bort</button></div>`).join(''):'<p class="empty">Inget inlagt hemma ännu.</p>';stock.querySelectorAll('[data-stock-use]').forEach(b=>b.onclick=()=>{const s=load();s.stock=s.stock.filter(x=>x.id!=b.dataset.stockUse);save(s);render()})}if(shop){shop.innerHTML=st.shopping.length?st.shopping.map(x=>`<div class="history-meal"><label><input type="checkbox" data-shop-done="${x.id}" ${x.done?'checked':''}> <strong>${x.item}</strong></label>${x.source?`<small>${x.source}</small>`:''}<button class="secondary" data-shop-remove="${x.id}" type="button">Ta bort</button></div>`).join(''):'<p class="empty">Handlingslistan är tom.</p>';shop.querySelectorAll('[data-shop-done]').forEach(c=>c.onchange=()=>{const s=load(),x=s.shopping.find(v=>v.id==c.dataset.shopDone);if(x)x.done=c.checked;save(s);render()});shop.querySelectorAll('[data-shop-remove]').forEach(b=>b.onclick=()=>{const s=load();s.shopping=s.shopping.filter(x=>x.id!=b.dataset.shopRemove);save(s);render()})}}
 window.malixAddRecipeMissingToShopping=addRecipeToShopping;window.malixCookRecipeFromKitchen=cookRecipe;window.malixRenderSmartKitchen=render;addView();addHomeCard();render();
})();