(() => {
 const KEY='malix-smart-kitchen-v1';
 const load=()=>{try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return {stock:Array.isArray(s.stock)?s.stock:[],shopping:Array.isArray(s.shopping)?s.shopping:[]}}catch{return {stock:[],shopping:[]}}};
 const save=s=>{localStorage.setItem(KEY,JSON.stringify(s));document.dispatchEvent(new CustomEvent('malix-smart-kitchen-updated'))};
 const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(kg|g|dl|ml|st|stycken|paket|burk|burkar)\b/g,' ').replace(/\d+[\d,.]*/g,' ').replace(/[^a-zåäö ]/gi,' ').replace(/\s+/g,' ').trim();
 const words=s=>norm(s).split(' ').filter(w=>w.length>2&&!['eller','valfri','valfria','garna','lite','eventuellt','med','och','for'].includes(w));
 const recipesList=()=>typeof recipes!=='undefined'?recipes:[];
 const matches=(stockItem,ingredient)=>{const a=words(stockItem),b=words(ingredient);return a.some(x=>b.some(y=>x.includes(y)||y.includes(x)))};
 const categoryFor=item=>{const n=norm(item);if(/tomat|gurka|paprika|morot|potatis|lök|vitlök|kål|broccoli|sallad|spenat|frukt|äpple|banan|citron|lime|avokado|zucchini|aubergine|selleri|rödbet|palsternack/.test(n))return'🥦 Frukt & grönt';if(/kött|köttfärs|kyckling|fisk|lax|torsk|sej|räk|mussl|korv|ägg|tofu/.test(n))return'🥩 Protein';if(/mjölk|grädde|yoghurt|filmjölk|kvarg|ost|smör|crème|feta/.test(n))return'🥛 Mejeri';if(/toalett|disk|tvätt|papper|schampo|tvål/.test(n))return'🧻 Övrigt';return'🥫 Skafferi & övrigt'};
 function addPlusShopping(st,item,source=''){const clean=String(item||'').trim();if(!clean)return;if(!st.shopping.some(x=>norm(x.item)===norm(clean)&&!x.done))st.shopping.push({id:'plus-shop-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),item:clean,source,category:categoryFor(clean),done:false})}
 function addStock(st,item,place,amount){const clean=String(item||'').trim();if(!clean)return;const existing=st.stock.find(x=>norm(x.item)===norm(clean)&&x.place===place);if(existing)existing.amount=String(amount||existing.amount||'1 st').trim();else st.stock.push({id:'stock-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),item:clean,place,amount:String(amount||'1 st').trim()})}
 function ensureView(){let s=document.querySelector('main > #smartKitchen');if(!s){s=document.createElement('section');s.id='smartKitchen';s.className='view';document.querySelector('main')?.appendChild(s)}return s}
 function renderView(){const s=ensureView();s.innerHTML=`<button type="button" class="back" data-open="home">← Tillbaka</button><p class="eyebrow">PLUS</p><h2>🧊 Kyl, frys & skafferi</h2><p class="subtitle">PLUS håller reda på vad du har hemma. Den vanliga handlingslistan är en separat gratis funktion.</p><section class="panel calm"><h3>🍲 Vad kan jag laga av det jag har?</h3><div id="plusCookFromHome" class="recipe-grid"></div></section><div class="plan-grid"><section class="panel"><h3>🧊 Det jag har hemma</h3><form id="plusStockForm" class="record-form"><label>Vara<input name="item" placeholder="t.ex. mjölk eller potatis" required></label><label>Var finns den?<select name="place"><option>Kyl</option><option>Frys</option><option>Skafferi</option></select></label><label>Mängd<input name="amount" placeholder="t.ex. 1 kg eller 6 st" required></label><button class="primary">Lägg till hemma</button></form><div id="plusStockList"></div></section><section class="panel"><h3>🛒 PLUS-lista</h3><p class="note">Den här listan hör bara till PLUS och används när något saknas eller tar slut i ditt inventerade kök.</p><form id="plusShoppingForm" class="record-form"><label>Lägg till något<input name="item" placeholder="t.ex. kaffe" required></label><button class="primary">Lägg till</button></form><div id="plusShoppingList"></div></section></div>`;
 wireForms(s);renderData();document.dispatchEvent(new CustomEvent('malix-plus-view-ready'))}
 function wireForms(s){s.querySelector('#plusStockForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();addStock(st,d.get('item'),d.get('place'),d.get('amount'));save(st);e.target.reset();renderData()});s.querySelector('#plusShoppingForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();addPlusShopping(st,d.get('item'));save(st);e.target.reset();renderData()})}
 function recipeScore(r,stock){const ing=r.ingredients||[],found=ing.filter(i=>stock.some(s=>matches(s.item,i))).length;return {found,total:ing.length,ratio:ing.length?found/ing.length:0}}
 function renderSuggestions(st){const root=document.querySelector('#plusCookFromHome');if(!root)return;if(!st.stock.length){root.innerHTML='<p class="empty">Lägg in några saker i kyl, frys eller skafferi så visas recept som passar.</p>';return}const ranked=recipesList().map(r=>({r,...recipeScore(r,st.stock)})).filter(x=>x.found>0).sort((a,b)=>b.ratio-a.ratio||b.found-a.found).slice(0,8);root.innerHTML=ranked.length?ranked.map(x=>`<article class="recipe-card"><h3>${x.r.emoji||'🍲'} ${x.r.name}</h3><p><strong>${x.found} av ${x.total}</strong> ingredienser matchar det du har hemma.</p><div class="chips"><button type="button" class="primary" data-plus-open="${x.r.id}">Öppna recept</button><button type="button" class="secondary" data-plus-missing="${x.r.id}">Lägg det som saknas i PLUS-listan</button></div></article>`).join(''):'<p class="empty">Inget recept matchar ännu.</p>';root.querySelectorAll('[data-plus-open]').forEach(b=>b.onclick=()=>window.openRecipe?.(b.dataset.plusOpen));root.querySelectorAll('[data-plus-missing]').forEach(b=>b.onclick=()=>{const r=recipesList().find(x=>String(x.id)===String(b.dataset.plusMissing));if(!r)return;const s=load(),missing=(r.ingredients||[]).filter(i=>!s.stock.some(x=>matches(x.item,i)));missing.forEach(i=>addPlusShopping(s,i,r.name));save(s);renderData()})}
 function renderData(){const st=load(),stock=document.querySelector('#plusStockList'),shop=document.querySelector('#plusShoppingList');renderSuggestions(st);if(stock){stock.innerHTML=st.stock.length?st.stock.map(x=>`<div class="history-meal"><strong>${x.item}</strong><small>${x.place} · ${x.amount}</small><button type="button" class="secondary" data-plus-stock-remove="${x.id}">Ta bort</button></div>`).join(''):'<p class="empty">Inget inlagt hemma ännu.</p>';stock.querySelectorAll('[data-plus-stock-remove]').forEach(b=>b.onclick=()=>{const s=load();s.stock=s.stock.filter(x=>String(x.id)!==String(b.dataset.plusStockRemove));save(s);renderData()})}if(shop){const groups={};st.shopping.forEach(x=>(groups[x.category||categoryFor(x.item)]||(groups[x.category||categoryFor(x.item)]=[])).push(x));shop.innerHTML=st.shopping.length?Object.entries(groups).map(([cat,items])=>`<div class="shopping-group"><h4>${cat}</h4>${items.map(x=>`<div class="history-meal"><strong>${x.item}</strong>${x.source?`<small>${x.source}</small>`:''}<button type="button" class="secondary" data-plus-shop-remove="${x.id}">Ta bort</button></div>`).join('')}</div>`).join(''):'<p class="empty">PLUS-listan är tom.</p>';shop.querySelectorAll('[data-plus-shop-remove]').forEach(b=>b.onclick=()=>{const s=load();s.shopping=s.shopping.filter(x=>String(x.id)!==String(b.dataset.plusShopRemove));save(s);renderData()})}}
 window.malixRenderSmartKitchen=()=>{if(!document.querySelector('main > #smartKitchen'))renderView();else renderData()};
 window.malixAddRecipeMissingToPlusShopping=recipe=>{const st=load(),missing=(recipe?.ingredients||[]).filter(i=>!st.stock.some(x=>matches(x.item,i)));missing.forEach(i=>addPlusShopping(st,i,recipe?.name||'recept'));save(st);renderData();return missing.length};
 renderView();
})();