(() => {
 const KEY='malix-smart-kitchen-v1';
 const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"stock":[],"shopping":[]}')}catch{return {stock:[],shopping:[]}}};
 const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
 function addHomeCard(){const grid=document.querySelector('#home .choice-grid');if(!grid||document.querySelector('[data-open="smartKitchen"]'))return;const b=document.createElement('button');b.className='choice-card';b.dataset.open='smartKitchen';b.innerHTML='<span>🧊</span><strong>Mitt kök</strong><small>Kyl, frys, skafferi och smart handlingslista.</small><span class="tier-tag tier-plus">PLUS</span>';grid.appendChild(b);b.addEventListener('click',()=>show('smartKitchen'));}
 function addView(){if(document.querySelector('#smartKitchen'))return;const main=document.querySelector('main');const s=document.createElement('section');s.id='smartKitchen';s.className='view';s.innerHTML=`<button class="back" data-open="home">← Tillbaka</button><p class="eyebrow">PLUS</p><h2>🧊 Mitt kök</h2><p>Se vad som finns hemma och bygg handlingslistan utifrån det du faktiskt behöver.</p><div class="plan-grid"><section class="panel"><h3>🧊 Kyl, frys & skafferi</h3><form id="stockForm" class="record-form"><label>Vara<input name="item" placeholder="t.ex. potatis, mjölk, kyckling" required></label><label>Var finns den?<select name="place"><option>Kyl</option><option>Frys</option><option>Skafferi</option></select></label><label>Mängd<input name="amount" placeholder="t.ex. 6 st, 500 g, 1 paket"></label><button class="primary">Lägg till hemma</button></form><div id="stockList"></div></section><section class="panel"><h3>🛒 Handlingslista</h3><form id="shoppingForm" class="record-form"><label>Lägg till något<input name="item" placeholder="t.ex. kaffe eller toalettpapper" required></label><button class="primary">Lägg till</button></form><div id="shoppingList"></div></section></div><section class="panel calm"><h3>💰 När något är billigt</h3><p>Här kan du tänka ett steg längre utan att köpa mer än du behöver.</p><div class="chips"><button type="button" data-buy-tip="freeze">Köp extra & frys in</button><button type="button" data-buy-tip="two">Köp extra & laga två rätter</button><button type="button" data-buy-tip="one">Köp bara till en rätt</button></div><p id="buyTip" class="note">Välj ett alternativ när du planerar ett bra köp.</p></section><section class="panel"><h3>🍲 Från recept till kök</h3><p>Nästa koppling använder receptets ingredienser: sådant du redan har hemma hoppas över och resten läggs i handlingslistan. När maten är lagad kan ingredienser minskas och extra portioner sparas i kyl eller frys.</p><div class="note"><strong>Testversion:</strong> lager och handlingslista fungerar nu. Receptkopplingen byggs ovanpå detta så att vi kan kontrollera varje steg innan varor räknas bort automatiskt.</div></section>`;main.appendChild(s);s.querySelector('.back').addEventListener('click',()=>show('home'));
 s.querySelector('#stockForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();st.stock.push({id:Date.now(),item:d.get('item').trim(),place:d.get('place'),amount:d.get('amount').trim()});save(st);e.target.reset();render()});
 s.querySelector('#shoppingForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),st=load();st.shopping.push({id:Date.now(),item:d.get('item').trim(),done:false});save(st);e.target.reset();render()});
 s.querySelectorAll('[data-buy-tip]').forEach(b=>b.addEventListener('click',()=>{const t={freeze:'Bra när varan går att frysa och du vet att den kommer användas. Lägg den extra mängden i frysen direkt.',two:'Välj två recept som använder samma huvudråvara. Då kan ett bra pris ge två olika måltider.',one:'Bra val när du inte har en tydlig plan för det extra. Billigt är bara billigt om maten används.'};s.querySelector('#buyTip').textContent=t[b.dataset.buyTip]}));}
 function render(){const s=load(),stock=document.querySelector('#stockList'),shop=document.querySelector('#shoppingList');if(stock){stock.innerHTML=s.stock.length?s.stock.map(x=>`<div class="history-meal"><strong>${x.item}</strong><small>${x.place}${x.amount?' · '+x.amount:''}</small><button class="secondary" data-stock-use="${x.id}" type="button">Använd / ta bort</button></div>`).join(''):'<p class="empty">Inget inlagt hemma ännu.</p>';stock.querySelectorAll('[data-stock-use]').forEach(b=>b.onclick=()=>{const st=load();st.stock=st.stock.filter(x=>x.id!=b.dataset.stockUse);save(st);render()})}if(shop){shop.innerHTML=s.shopping.length?s.shopping.map(x=>`<div class="history-meal"><label><input type="checkbox" data-shop-done="${x.id}" ${x.done?'checked':''}> <strong>${x.item}</strong></label><button class="secondary" data-shop-remove="${x.id}" type="button">Ta bort</button></div>`).join(''):'<p class="empty">Handlingslistan är tom.</p>';shop.querySelectorAll('[data-shop-done]').forEach(c=>c.onchange=()=>{const st=load(),x=st.shopping.find(v=>v.id==c.dataset.shopDone);if(x)x.done=c.checked;save(st);render()});shop.querySelectorAll('[data-shop-remove]').forEach(b=>b.onclick=()=>{const st=load();st.shopping=st.shopping.filter(x=>x.id!=b.dataset.shopRemove);save(st);render()})}}
 addView();addHomeCard();render();
})();