(() => {
 const KEY='malix-water-v1';
 const dateKey=()=>window.malixOverviewKey?.()||window.malixLocalDateKey?.(new Date())||new Date().toISOString().slice(0,10);
 const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
 const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
 function total(){const d=load();return Number(d[dateKey()]||0)}
 function add(ml){const d=load(),k=dateKey();d[k]=Math.max(0,Number(d[k]||0)+ml);save(d);render()}
 function ensure(){const grid=document.querySelector('.dashboard-grid');if(!grid||document.querySelector('#waterSummary'))return;const card=document.createElement('article');card.className='summary-card';card.innerHTML='<span>💧 Vatten</span><strong id="waterSummary">0 ml idag</strong><small>Tryck för att logga eller läsa varför vätska behövs ›</small>';grid.appendChild(card);card.tabIndex=0;card.setAttribute('role','button');card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};
 const box=document.createElement('div');box.id='waterPanel';box.className='panel';box.hidden=true;box.style.marginTop='16px';box.innerHTML='<div class="dashboard-heading"><div><p class="eyebrow">Dagens vätska</p><h3>💧 Vatten</h3></div><button type="button" class="secondary" id="waterClose">Stäng</button></div><p id="waterPanelTotal"></p><div class="chips"><button type="button" data-water="200">+ 1 glas (2 dl)</button><button type="button" data-water="250">+ 2,5 dl</button><button type="button" data-water="500">+ 5 dl</button><button type="button" data-water="-200">− 2 dl</button></div><form id="waterCustom" class="record-form" style="margin-top:12px"><label>Egen mängd i ml<input name="ml" type="number" min="1" step="10" placeholder="t.ex. 330"></label><button class="secondary">Lägg till</button></form><div class="note"><strong>Varför behöver kroppen vätska?</strong><p>Vätska behövs för kroppens normala funktioner, bland annat för temperaturreglering, blodcirkulation och matsmältning. Behovet varierar mellan personer och kan öka till exempel vid fysisk aktivitet och varmt väder. Även annan dryck och vätska i maten bidrar.</p><p>Appen använder därför inte ett hårt mål som passar alla. Här kan du följa ditt intag utan att göra det till ännu en prestation.</p></div>';document.querySelector('.dashboard-panel').appendChild(box);box.querySelector('#waterClose').onclick=()=>box.hidden=true;box.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>add(Number(b.dataset.water)));box.querySelector('#waterCustom').onsubmit=e=>{e.preventDefault();const n=Number(new FormData(e.target).get('ml'));if(n>0)add(n);e.target.reset()};render()}
 function open(){const b=document.querySelector('#waterPanel');if(!b)return;b.hidden=false;render();b.scrollIntoView({behavior:'smooth',block:'nearest'})}
 function render(){ensure();const ml=total(),s=document.querySelector('#waterSummary'),p=document.querySelector('#waterPanelTotal');const text=ml>=1000?`${(ml/1000).toLocaleString('sv-SE',{maximumFractionDigits:2})} liter idag`:`${ml} ml idag`;if(s)s.textContent=text;if(p)p.innerHTML=`Du har registrerat <strong>${text}</strong>.`}
 document.addEventListener('malix-day-changed',()=>setTimeout(render,0));window.addEventListener('storage',render);setTimeout(render,0);
})();